### ISSUE TITLE
Support for adding products to a subscription

### ISSUE THREAD

**Issue by dmseaton** [Prospress/woocommerce-subscribe-all-the-things#100]
Given the nature of SATT it seems like it'd be useful to somehow permit users to add products to a subscription instead of just removing them - perhaps with a Change Subscription option which dumps/replicates a subscription into the cart, then updates the subscription on purchase (preferably against the same ID, but I'm not sure whether this is achievable in practice).

Any thoughts on this? Has it been considered already?

**Comment by piersline** [comment]
Yes, swapping items in an existing subscription would be most useful

**Comment by GAPP99** [comment]
It's already been requested in this thread: https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/12

**Comment by franticpsyx** [comment]
Closing in favor of #12 -- this is something we have in mind 👍
