### ISSUE TITLE
Free or Zero Price Product exclusion

### ISSUE THREAD

**Issue by JohnLauber** [Prospress/woocommerce-subscribe-all-the-things#104]
Is there some code I can add to my functions to exclude a free or zero price item being part of a cart subscription? Thought I would ask before hunting and pecking through the code. Or is it the "one time only" option? 

Thank you.

**Comment by seb86** [comment]
We don't have any code snippets at this time.

**Comment by seb86** [comment]
Why do you want to exclude products that are free?

**Comment by JohnLauber** [comment]
If a customer orders a free sample, they don't want that as part of a subscription. However, they would want the other cart items to be subscriptions. Not a huge deal, as it could be the processor paying attention to the order, but it would be a nice to exclude it as a subscription option.

**Comment by franticpsyx** [comment]
Closing -- idea noted! However, this is not a place to discuss customization requests.
