### ISSUE TITLE
One Time Shipping/Free Shipping

### ISSUE THREAD

**Issue by JojoSimz** [Prospress/woocommerce-subscribe-all-the-things#107]
On WC Subscriptions, one has the option of choosing "one-time shipping" as a form of a discount for a variable subscription product... 

Wondering if this is on the radar at all for single-products (Would be a great feature as shipping costs are one of our most expensive operating expenses).

**Comment by franticpsyx** [comment]
Hey @JojoSimz -- the **One Time Shipping** box is also available when you attach Subscription Schemes to a product using the **Product Data > Subscriptions** tab.

Does this answer your question?

**Comment by JojoSimz** [comment]
Yes, Thank you tons.
