### ISSUE TITLE
WC 3.0.3 error = "every array" instead of "every month"

### ISSUE THREAD

**Issue by jessejones2** [Prospress/woocommerce-subscribe-all-the-things#111]
Since upgrading to WooCommerce 3.0.1, instead of the option to for “every month” it says “every array” and instead of “every year” it says “every array.” When I downgrade back to WooCommerce 2.6.14 there is not a problem.

**Comment by thenbrent** [comment]
SATT does not support WC 3.0 yet. See #96.

**Comment by jessejones2** [comment]
thank you! sorry to have missed the other posts. I was not aggressive enough with my searches. I love SATT and it is such an important part of my web sites. I will wait patiently for the upgrade and continue with WC 2.6.14

**Comment by thenbrent** [comment]
@jessejones2 I'm sorry it's not done yet and hopefully we won't keep you waiting too long. We of course wanted to get it done prior to 3.0's release, but just getting our commercial extensions compatible has taken all our time.

**Comment by franticpsyx** [comment]
@jessejones2 we are currently working on version `2.0` (currently in alpha), which should work with WC 3.0 + WCS 2.2. You can give it a spin on a staging site, but note that the Product Bundles, Composite Products and Mix-and-Match integrations are still being worked on :)

**Comment by franticpsyx** [comment]
^ Link: https://github.com/Prospress/woocommerce-subscribe-all-the-things/tree/2.0
