### ISSUE TITLE
Bundled Products Pricing

### ISSUE THREAD

**Issue by piersline** [Prospress/woocommerce-subscribe-all-the-things#112]
I've upgraded to WC3.0 and the pricing on the bundled products is now incorrect.  

It worked fine on WC2.6 but now it adds the bundled product price to the price of the subscription.

**Comment by franticpsyx** [comment]
@piersline -- v1 is not compatible with WC 3.0 or WCS 2.2. See https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/96 for details.
