### ISSUE TITLE
Composite Product + Priced Individually not generating subscription total

### ISSUE THREAD

**Issue by lsab** [Prospress/woocommerce-subscribe-all-the-things#113]
I'm trying to generate a subscription from a composite product with priced individually components.
However, though the initial payment is correct, the subscription renewal total is always £0.00 - Which I guess is taken from the base price of the composite product, since that's empty.

The subscription is set to: Price -  Inherit from product.  Does that mean base price, or configured price?
Have I configured this correctly?  Or this this not possible?

**Comment by franticpsyx** [comment]
Hey @lsab -- Which versions of WooCommerce / Subscriptions / SATT are you running? Thanks!

**Comment by lsab** [comment]
WooCommerce - 3.0.1
Subscriptions - 2.2.3
SATT - 2.0
Composite Products - 3.9.0

**Comment by thenbrent** [comment]
@lsab SATT does not support WC 3.0 yet. See #96 or #111 for more details and options for bleeding edge code you can test with.

**Comment by lsab** [comment]
Ahh no problem, I'll revert to WC 2.6 for now.
Thanks.

**Comment by thenbrent** [comment]
@lsab be sure you also restore the database to a backup prior to running the 3.0 upgrade routine, as that changes how data is stored in the database.
