### ISSUE TITLE
Plugin breaks cart in WooCommerce 3.0.3

### ISSUE THREAD

**Issue by kraelik** [Prospress/woocommerce-subscribe-all-the-things#114]
I just updated to the latest version of WooCommerce, and on the cart page, all that showed in the sidebar was this error message. Any help is appreciated!

> Fatal error: Uncaught exception 'Exception' with message 'Invalid product.' in /nas/content/themename/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php:133 Stack trace: #0 /nas/content/themename/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(143): WC_Product_Data_Store_CPT->read(Object(WC_Product)) #1 /nas/content/themename/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php(126): WC_Data_Store->read(Object(WC_Product)) #2 /nas/content/themename/wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/class-wcsatt-display.php(390): WC_Product->__construct('1') #3 [internal function]: WCS_ATT_Display::show_subscribe_to_cart_prompt('') #4 /nas/content/themename/wp-includes/class-wp-hook.php(298): call_user_func_array(Array, Array) #5 /nas/content/themename/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #6 /nas/content/themename/wp-includes/plugin.php(453): in /nas/content/themename/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php on line 133

**Comment by franticpsyx** [comment]
@kraelik -- v1 is not compatible with WC 3.0 or WCS 2.2. See #96 for details.
