### ISSUE TITLE
Not compatible with new versions of WooCommerce and Subscriptions 

### ISSUE THREAD

**Issue by baalvik** [Prospress/woocommerce-subscribe-all-the-things#115]
After updating to the newest versions of these plugins, the discount doesn't apply and the time frames don't translate to the product page.  will there be an update of this plugin to fix this?  Just hoping the development of this plugin is still happening.

Best,
Ben

**Comment by thenbrent** [comment]
@baalvik yes we're aware and working on it, see #96 (or discussion on #111 or #114)
