### ISSUE TITLE
The discount is not applied on the cart page

### ISSUE THREAD

**Issue by dimijazz** [Prospress/woocommerce-subscribe-all-the-things#117]
I tried to deactivate all plugins and also change theme. But the price issue is not gone.
I can choose on product page the 10% discounted subscription (price is discounted) but on cart its displayed
 $27.00	
$27.00 / month
Everything else seems to work ok.	
Any Ideas ??? 
Thanks 
Dimitris

WC version:		3.0.4
Log directory writable:		 /www/wp-content/uploads/wc-logs/
WP version:		4.7.3
WP multisite:		–
WP memory limit:		128 MB
WP debug mode:		–
WP cron:		
Language:		en_US
Server environment
Server info:		Flywheel/4.1.0
PHP version:		5.6.30-7+deb.sury.org~precise+1
PHP post max size:		100 MB
PHP time limit:		1000
PHP max input vars:		5000
cURL version:		7.22.0, OpenSSL/1.0.1
SUHOSIN installed:		–
MySQL version:		5.6.32
Max upload size:		100 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
WCS_DEBUG:		 No
Subscriptions Mode:		 Staging
Database
WC database version:		3.0.4
Database prefix	 	wp_
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
Security
Secure connection (HTTPS):		Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors		
Active plugins (40)
Gravity Forms	 	by rocketgenius – 2.2.1.2
Ninja Popups	 	by ArsCode – 4.4.1
Cmssuperheroes	 	by Luan Nguyen, Cong Nguyen – 1.0.9.2
Contact Form 7 MailChimp Extension	 	by Renzo Johnson – 0.4.43
Contact Form 7	 	by Takayuki Miyoshi – 4.7
Disable Comments	 	by Samir Shah – 1.6
Gravity Forms MailChimp Add-On	 	by rocketgenius – 4.2
WPBakery Visual Composer	 	by Michael M - WPBakery.com – 5.1.1
Login Logo	 	by Mark Jaquith – 0.7
MailChimp	 	by MailChimp – 1.5.7
Meta Box Conditional Logic	 	by Tan Nguyen – 1.3.4
Meta Box	 	by Anh Tran – 4.11
Nitro Gallery	 	by WooRockets – 1.0.4
Nitro Toolkit	 	by WooRockets Team – 1.1.4
Order / Coupon / Subscription Export Import Plugin for WooCommerce (BASIC)	 	by HikeForce – 1.1.8
PixelYourSite PRO	 	by PixelYourSite – 6.0.4
Quick Page/Post Redirect Plugin	 	by anadnet – 5.1.8
Slider Revolution	 	by ThemePunch – 5.4.1
TinyMCE Advanced	 	by Andrew Ozz – 4.5.6
WooCommerce Advanced Free Shipping	 	by Jeroen Sormani – 1.1.0
WooCommerce Customer/Order/Coupon CSV Import Suite	 	by SkyVerge – 3.3.1
WooCommerce Stripe Gateway	 	by WooCommerce – 3.1.7
WooCommerce Google Analytics Integration	 	by WooThemes – 1.4.0
WooCommerce Review for Discount	 	by 75nineteen Media – 1.5.8 – 1.6.3 is available
WooCommerce Shipment Tracking	 	by WooCommerce – 1.6.3 – 1.6.4 is available
WooCommerce Smart Coupons-Null24.Net	 	by WooThemes – 3.0.16 – 3.3.0 is available
WooCommerce - Store Exporter Deluxe	 	by Visser Labs – 2.0.7
WooCommerce - Store Toolkit	 	by Visser Labs – 1.7.1
WooCommerce Subscribe All the Things	 	by Prospress Inc. – 1.1.2
WooCommerce Subscriptions	 	by Prospress Inc. – 2.1.4 – 2.2.5 is available
WooCommerce	 	by Automattic – 3.0.4
WooCommerce Helper	 	by WooCommerce – 1.7.2 – Network enabled
WordPress Importer	 	by wordpressdotorg – 0.6.3
Yoast SEO	 	by Team Yoast – 4.6
WP Store Locator	 	by Tijmen Smit – 2.2.7
WR In Stock Alert	 	by WooRockets – 1.0.3
WR Live Search	 	by WooRockets – 1.0.6
WR Share for Discounts	 	by WooRockets – 1.0.6
Easy Forms for MailChimp	 	by YIKES, Inc. – 6.3.14
YITH WooCommerce Wishlist	 	by YITHEMES – 2.1.0

**Comment by thenbrent** [comment]
> WC version:	3.0.4

SATT is not compatible with WC 3.0. Please see #96 (or discussion on #111 or #114) for more details. I suspect this is just one of many issues you'll see while running 3.0
