### ISSUE TITLE
If i select every 2 week in product detail page it show default only now on cart page

### ISSUE THREAD

**Issue by umang-dev** [Prospress/woocommerce-subscribe-all-the-things#118]
I have recently update my  site with woocommerce 3.0. i have trouble when If i select every 2 week or any other in product detail page it show every time default only now on cart page. please help me to fix this issue

**Comment by willgorham** [comment]
@umang-dev I would try the 2.0 branch and see if that works. But do note that there hasn't been an official WC 3.0 compatible release for SATT yet. See issue #96

**Comment by umang-dev** [comment]
I have installed 2.0 branch. when i select any option like every 3 week option in product detail page, it will always show default only now option in cart page. please help me to solve this issue. we have multiple production site running with this. and we cannot remove this plugin. thank you in advance.

**Comment by franticpsyx** [comment]
@umang-dev -- Have you updated to the latest version on WooCommerce Subscriptions?

Could you please share some details about:

- The product that exhibits this problem. Is it a simple/variable product?
- The **Subscription** settings created using SATT -- can you share a screenshot of the **Product Data > Subscriptions** panel?

Finally, is there a staging/live site affected this issue that we can access?

**Comment by umang-dev** [comment]
I am using variable product and simple product data type for products

Here is product link : http://www.petwants.com/petwantsmason/product/salmon-brown-rice/. I also want to remove price on subscription option. i only want to show every 2 week like it showing on cart page.

everything is working fine the problem is on cart page. it show default only now option selected after i set subscription like 2 week.

I have attached screenshot for product data.
![subscription options for variable product](https://cloud.githubusercontent.com/assets/18212842/25527739/b6c846de-2c37-11e7-9a4b-3b768750c753.png)

**Comment by umang-dev** [comment]
Previously it works fine on wsatt 1.2 . when i update woocommerce 3.0 then it show every array on product detail. it there any solution to update on old version plugin code. are you working on new version?

**Comment by franticpsyx** [comment]
Thanks @umang-dev -- version 2.0 has not been tested with the Variable product type yet. 

At the moment we are actually refactoring the existing integrations with complex product types and plan to make a final testing round to track down and fix any major issues that have slipped through, like this one.

When done, we'll officially tag 2.0 beta :)

**Comment by umang-dev** [comment]
okay thanks a lot,  i am waiting for this update. how much around time taking this plugin to release?

**Comment by umang-dev** [comment]
it that possible to switching subscription from customers view? currently it  is only possible if product type is variable subscription. my client want to make subscription editable from client view

**Comment by franticpsyx** [comment]
Hard to say, @umang-dev -- ideally we'd like to have a beta ready early in May, but would also like our teams to review the new [SATT Product API](https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/2.0/includes/class-wcsatt-product.php) together before v2.0 hits beta.

At the moment our top priority is to ensure that our extensions (and especially WC Subscriptions, which SATT depends on) work trouble-free with WC 3.0.

If you depend on SATT, please postpone the update to WC 3.0.

Closing as this is a known issue.
