### ISSUE TITLE
Frequency Returning as Array

### ISSUE THREAD

**Issue by sitesforchrist** [Prospress/woocommerce-subscribe-all-the-things#119]
Since updating Woocommerce Subscriptions to latest version (2.2.5) the frequency in the bullet list is displaying as an array rather than the frequency. Example: What used to say "Every Month" and "Every Week" now says "Every Array" for both. Also in the cart it says the "price / array" rather than "price / month".

**Comment by thenbrent** [comment]
Hi @sitesforchrist please see https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/118#issuecomment-297979972 and #96
