### ISSUE TITLE
Error showing with YITH Abandoned Cart plugin

### ISSUE THREAD

**Issue by ImportantlyMe** [Prospress/woocommerce-subscribe-all-the-things#120]
Hi there

Error message appears in Abandoned Cart plugin admin screen

Warning: Invalid argument supplied for foreach() in /home/aquaamor/public_html/wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/class-wcsatt-schemes.php on line 300

![1pasted image at 2017_05_03 04_19 pm fw](https://cloud.githubusercontent.com/assets/28385604/25697816/5f5aa38e-30b4-11e7-9b6a-28d6159ec71c.png)

Plugin working on front end OK

**Comment by franticpsyx** [comment]
Hey @ImportantlyMe -- we are not planning to release another v1 version. You are encouraged to try out the v2 branch and report issues for us to look into before the final release.

Also, note that our capacity to test and fix issues with 3rd party plugins is very limited, as SATT is still a free project that's limited in scope.
