### ISSUE TITLE
Fatal error on cart page

### ISSUE THREAD

**Issue by davescol** [Prospress/woocommerce-subscribe-all-the-things#121]
I have woocomerce 3.05 and subscriptions 2.2.6 I am getting an error on the cart page of: 

Fatal error: Uncaught Exception: Invalid product. in /homepages/19/d674124826/htdocs/app674393108/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php:133 Stack trace: #0 /homepages/19/d674124826/htdocs/app674393108/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(143): WC_Product_Data_Store_CPT->read(Object(WC_Product)) #1 /homepages/19/d674124826/htdocs/app674393108/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php(126): WC_Data_Store->read(Object(WC_Product)) #2 /homepages/19/d674124826/htdocs/app674393108/wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/class-wcsatt-display.php(392): WC_Product->__construct('1') #3 /homepages/19/d674124826/htdocs/app674393108/wp-includes/class-wp-hook.php(298): WCS_ATT_Display::show_subscribe_to_cart_prompt('') #4 /homepages/19/d674124826/htdocs/app674393108/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #5 /homepages/19/d674124826/htdocs/app674393108/wp-includes/plu in /homepages/19/d674124826/htdocs/app674393108/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php on line 133

**Comment by thenbrent** [comment]
Hi @davescol SATT does not support WC 3.0 yet. See #96 or #111 for more details and options for bleeding edge code you can test with.
