### ISSUE TITLE
Issue with subscription discount prices not displaying

### ISSUE THREAD

**Issue by pucelles** [Prospress/woocommerce-subscribe-all-the-things#122]
Site: ReddRemedies.com

Please view a video describing the issue here: https://www.dropbox.com/s/a7sbqd30lit4rvn/WCSATT_error.mp4?dl=0

--

To be brief, the subscription discount is not displaying, seemingly at random.

Any help is greatly appreciated.

**Comment by seb86** [comment]
@pucelles I replied to your email.

**Comment by franticpsyx** [comment]
@seb86 -- It would be really appreciated if you could please use the issue tracker to report (or help with) actual issues. Using it for private comm doesn't offer much to the repo, or to SATT users and devs reading this. Thanks!
