### ISSUE TITLE
WC 3 with SATT 2.0 - Product Bundles

### ISSUE THREAD

**Issue by llamedia** [Prospress/woocommerce-subscribe-all-the-things#123]
http://learn.lemonlimeadventures.com/product/the-worries-workshop-toolkit/

product bundle setup to do one time payment for 97$ and payment plan for 3 payments of 32.33

One Time Product Purchase is showing as "none" on the product page. If you add to cart and continue to the cart there are 3 options showing 97$ and then 2 32.33 options. 

Any thoughts?

**Comment by franticpsyx** [comment]
Hey @llamedia -- could you please specify which versions of WC, WCS and SATT you are running? Thanks!

**Comment by llamedia** [comment]
`
### WordPress Environment ###

Home URL: http://learn.lemonlimeadventures.com
Site URL: http://learn.lemonlimeadventures.com
WC Version: 3.0.6
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.18
PHP Post Max Size: 54 MB
PHP Time Limit: 300
PHP Max Input Vars: 4000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 52 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.6
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (39) ###

ManageWP - Worker: by ManageWP – 4.2.18
AffiliateWP - Recurring Referrals: by Pippin Williamson and Andrew Munro – 1.6.1
AffiliateWP: by AffiliateWP
LLC – 2.0.8

Beaver Builder Plugin (Standard Version): by The Beaver Builder Team – 1.10.2
Beaver Themer: by The Beaver Builder Team – 1.0
Ultimate Addon for Beaver Builder: by Brainstorm Force – 1.4.4
Beaver Tunnels: by FireTree Design
LLC  – 2.1.3

Contact Form 7: by Takayuki Miyoshi – 4.7
Duplicate Post: by Enrico Battocchi – 3.2
Genesis Dambuster: by Russell Jamieson – 1.6
Genesis Simple Edits: by StudioPress – 2.2.0
Genesis Simple Hooks: by Nathan Rice – 2.2.0
Leadpages Connector: by Leadpages – 2.1.6.3
LifterLMS WooCommerce: by Thomas Patrick Levy – 1.0.2
LifterLMS: by Thomas Patrick Levy
codeBOX LLC – 3.7.6

Metorik Helper: by Metorik – 0.9.0
PixelYourSite PRO: by PixelYourSite – 6.0.7
Redirection: by John Godley – 2.5
Simple Custom CSS: by John Regan
Danny Van Kooten – 3.3

Social Warfare - Pro: by Warfare Plugins – 2.2.5
Social Warfare: by Warfare Plugins – 2.2.5
Compress JPEG & PNG images: by TinyPNG – 2.2.2
User Switching: by John Blackbourn – 1.0.9
WooCommerce Composite Products: by SomewhereWarm – 3.9.4
WooCommerce Customer/Order CSV Export: by SkyVerge – 4.3.0
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooCommerce – 4.4.7
WooCommerce Stripe Gateway: by WooCommerce – 3.1.8
WooCommerce One Page Checkout: by Prospress Inc. – 1.4.1
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.6.5
WooCommerce Product Bundles: by SomewhereWarm – 5.2.4
WooCommerce Subscribe All the Things: by Prospress Inc. – 2.0.0
WooCommerce Subscriptions: by Prospress Inc. – 2.2.6
WooCommerce: by Automattic – 3.0.6
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO: by Team Yoast – 4.7.1
WP Fusion: by Very Good Plugins – 3.1.2
WP Menu Cart Pro: by Jeremiah Prummer
Ewout Fernhout – 3.1.0

WP Rocket: by WP Media – 2.9.11
WP Overnight Sidekick: by Jeremiah Prummer – 1.0.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
featured (featured-2)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-3 (rated-3-2)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #1699 - /shop/
Cart: #1700 - /cart/
Checkout: #1701 - /checkout/
My account: #1702 - /my-account/

### Theme ###

Name: Maker Pro
Version: 1.0.0
Author URL: http://www.jtgrauke.com
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 2.5.0
Parent Theme Author URL: https://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Customer/Order CSV Export ###

Order Export Format: default
Customer Export Format: default
Automatically Export Orders: disabled
Automatically Export Customers: disabled
`

**Comment by franticpsyx** [comment]
Hey @llamedia -- can you re-download the latest SATT version from https://github.com/Prospress/woocommerce-subscribe-all-the-things/tree/2.0 and re-test?

Using `v2` on a production environment is not recommended as the `2.0` branch is **not stable**. We are pushing new code to that branch as we continue working on version 2.0, so if you have to use it I would strongly recommend you re-download and update on a regular basis.

Please keep in mind this is alpha code!

**Comment by llamedia** [comment]
yeah, 100% know and agree. we had to upgrade to wc3 because 2 was causing a problem and 3 fixed that problem. but now it's created this problem. 

we might end up having to utilize the lifterlms payment gateway for this launch. 

but ultimately love the SATT Woo for shopping cart experience. 

thank you for all of the whard work you put into this plugin. It is greatly appreciated and fills a HUGE hole in the woo stratosphere.

**Comment by franticpsyx** [comment]
Thanks @llamedia -- we really appreciate the kind words 👍 

So, did you try the latest version of https://github.com/Prospress/woocommerce-subscribe-all-the-things/tree/2.0 ? Did it fix the issue?

**Comment by llamedia** [comment]
yes. i am using 2.0.

**Comment by franticpsyx** [comment]
Did you re-download and re-install it?

That is a working branch which means its changing all the time - but the version number remains the same :)

**Comment by llamedia** [comment]
ahh, ok thanks for the clarification. will try now.

**Comment by llamedia** [comment]
no change on latest update.

**Comment by franticpsyx** [comment]
@llamedia -- can you try again? I just just pushed some commits to the `2.0` branch. These PB integration patches have been made locally since last week, but were not pushed to the repo.

Note that the PB integration is the only one that's finalized in `2.0`. Composite Products and Mix-and-Match Products integrations are in progress.

**Comment by llamedia** [comment]
giving it a try now.

**Comment by llamedia** [comment]
<img width="1226" alt="screen shot 2017-05-12 at 10 03 45 pm" src="https://cloud.githubusercontent.com/assets/28643585/26022004/e47de23c-375e-11e7-83a1-92430115e143.png">

<img width="645" alt="screen shot 2017-05-12 at 10 04 32 pm" src="https://cloud.githubusercontent.com/assets/28643585/26022006/fca78390-375e-11e7-90f7-ccfc94d67afb.png">
 
product page still displays "none"  so no change there. 
cart is now displaying just 2 options, but now the total of the instant purchase is blank. its working but not displaying. 

progress! can't thank you enough!!!

**Comment by franticpsyx** [comment]
> product page still displays "none" so no change there

This is the desired behavior. Was it different in v1? It's consistent with how SATT works with other product types, too.

**Comment by franticpsyx** [comment]
> cart is now displaying just 2 options, but now the total of the instant purchase is blank. its working but not displaying.

Hm, this works fine on my end. Can you please make sure you are running Product Bundles v5.2.4?

**Comment by llamedia** [comment]
it's literally "no subscription" option. ha. it used to just say 97$

We currently only have the 1 product on the site. Do you know if i can pass a filter to display $97 instead of none? 

I am running 5.2.4. It isn't a show stopper. to not have that total displaying, because the CART total is working.

**Comment by franticpsyx** [comment]
> We currently only have the 1 product on the site. Do you know if i can pass a filter to display $97 instead of none?

This is definitely possible but I'm afraid I can't be of much help as we can't provide any support for customizations. Closing as the original issue seems to be fixed!
