### ISSUE TITLE
Subscription option display Every `Array`

### ISSUE THREAD

**Issue by kristinaplauche** [Prospress/woocommerce-subscribe-all-the-things#124]
### What I expected.

To set up a Subscriptions rule for every day, week, month, or year and have that time period display on the front end.

### What actually happened.

The time period is listed as "Array".
![screenshot](http://cld.wthms.co/6NgMZ+)
Image link: http://cld.wthms.co/6NgMZ

### To Replicate:

**Have only these plugins active:**
WooCommerce 3.0.7
Subscriptions 2.2.6
Subscribe all the things 1.1.2

![screenshot](http://cld.wthms.co/cDAAK+)
Image link: http://cld.wthms.co/cDAAK

**Comment by thenbrent** [comment]
> Have only these plugins active:
> WooCommerce 3.0.7

@kristinaplauche I think this is just another of the many things we'll find/fix once we get to 3.0 compatibility work with #96 (once we feel like Subscriptions is working reliably, we'll hopefully be able to make time to update our free extensions too.)

If you came to this issue via someone submitting a ticket to woocommerce.com, it's probably worth reminding them of this: https://github.com/Prospress/woocommerce-subscribe-all-the-things#support

**Comment by kristinaplauche** [comment]
Tbh, I did not realize it wasn't 3.0 compatible yet and I've been recommending it to people who need the functionality. I know better now. 😬
Thanks Brent!
