### ISSUE TITLE
Quantity Input Missing

### ISSUE THREAD

**Issue by tlelkins** [Prospress/woocommerce-subscribe-all-the-things#126]
I noticed that on certain products, the quantity field doesn't appear.

For example, it doesn't show here: http://www.eighthandroast.com/shop/coffee/brazil-sweet-blue/

But it DOES show here: http://www.eighthandroast.com/shop/coffee/test-product/

Any idea why that is? It appears that if a product has already been created as a variable subscription product, then is changed to a simple product with your subscriptions added in, it breaks the quantity field.

**Comment by javorszky** [comment]
Is the brazil sweet blue restricted to be individually sold, by any chance?

**Comment by tlelkins** [comment]
Yep! I unchecked that box in the variable subscription menu and it totally worked. Thanks for that!
