### ISSUE TITLE
MnM - Subscription period is showing up as "array"

### ISSUE THREAD

**Issue by helgatheviking** [Prospress/woocommerce-subscribe-all-the-things#127]
The subscription plan is $85 / array instead of $85 / month. 

![image](https://cloud.githubusercontent.com/assets/507025/26523042/41918ea4-42d3-11e7-92bd-4482eef502a1.png)

This was a mix and match product with the following settings:

![image](https://cloud.githubusercontent.com/assets/507025/26523070/32000294-42d4-11e7-9ec3-169f67fc7abc.png)

SATT 2.0 -alpha
WC-3.1 -alpha
MNM- 1.2.3
Subs - 2.2.7

Granted, I'm using the bleeding edge versions of pretty much everything, but just a heads up in case this persists.

**Comment by franticpsyx** [comment]
WC 3.1? 👯 As if 3.0 was alright to start with.

It's a known issue @helgatheviking -- I haven't managed to look into CP/MnM compatibility just yet.

**Comment by helgatheviking** [comment]
I mean 3.1-alpha is what's in their main branch now. Whether they've fixed all the 3.0 issues or not... 🤷‍♀️ 

I should test this out with a regular product, but the MNM config shouldn't have any bearing on the billing period `/array` conversion, but I also am not that familiar with this one.

**Comment by franticpsyx** [comment]
@helgatheviking MnM seems to work fine for me with SATT v2.0-alpha, WCS 2.2 and WC 3.0.

Can you perhaps have another look when you find a few spare minutes?

**Comment by helgatheviking** [comment]
I'll try my best!

**Comment by franticpsyx** [comment]
I'll take the risk and close this, as it really looks like an issue with using SATT v1 in combination with later WCS / WC versions. Can't replicate and MnM integration is not particularly complex to test as it only supports static MnM prices.

**Comment by helgatheviking** [comment]
welp... I haven't gotten to test this, so I'll take your word for it!
