### ISSUE TITLE
WC 3.07

### ISSUE THREAD

**Issue by ImportantlyMe** [Prospress/woocommerce-subscribe-all-the-things#128]
Hi

Where can I get a verison to try with WC 3.07 please ?

Thanks

John

**Comment by franticpsyx** [comment]
Hey @ImportantlyMe -- feel free to try out the 2.0 branch: https://github.com/Prospress/woocommerce-subscribe-all-the-things/tree/2.0

Note that this is still alpha (work in progress), but we will be tagging a v2.0 beta very soon.
