### ISSUE TITLE
Version 2.0.0-alpha of WooCommerce Subscribe All the Things product Update issue from admin

### ISSUE THREAD

**Issue by umang-dev** [Prospress/woocommerce-subscribe-all-the-things#129]
I am using Version 2.0.0-alpha of WooCommerce Subscribe All the Things. i am facing issue with subscriptions option not updating from admin. i have checked up database and found in old version we are using  _subscription_schemes field and for new verison using _wcsatt_schemes field. should i remove  _subscription_schemes field in database to make all products work ?

**Comment by franticpsyx** [comment]
@umang-dev -- I see no `_subscription_schemes` meta in use in the v1.0 codebase. Both versions reference a `_wcsatt_schemes` meta.

Perhaps I haven't quite understood what you mean, but there is no need for a DB upgrade when moving from v1 to v2. 

If there was a need to update the DB, a v2 upgrade routine would be included.
