### ISSUE TITLE
Latest Version

### ISSUE THREAD

**Issue by jchrislemmer** [Prospress/woocommerce-subscribe-all-the-things#132]
Hi guys,

Any idea when this extension will support the latest version of WooCommerce and WooCommerce subscriptions?

Thanks!
Chris

**Comment by franticpsyx** [comment]
@jchrislemmer 

Feel free to have a look at v2.0-alpha: https://github.com/Prospress/woocommerce-subscribe-all-the-things/tree/2.0

Note that this is a work-in-progress branch, but it should be more stable than its `alpha` tag suggests. We are planning to review 2.0-alpha internally and hopefully tag a 2.0 beta in the next couple weeks!
