### ISSUE TITLE
Conditions

### ISSUE THREAD

**Issue by jchrislemmer** [Prospress/woocommerce-subscribe-all-the-things#138]
Hi there,

Is it possible to add conditions? So for instance if one of the components of a "Composite Product" is "X", then only subscription "X" is available. And if it's "Y" only subscription "Y" on that composite product is available.

Thanks
Chris

**Comment by franticpsyx** [comment]
Hey @jchrislemmer -- sounds like a very case-specific requirement.

We have no plans to do anything like this, please refer to the [Roadmap](https://github.com/Prospress/woocommerce-subscribe-all-the-things/wiki/Roadmap) to see some of the features we want to build into SATT.
