### ISSUE TITLE
Unable to apply useful labels for subscription options

### ISSUE THREAD

**Issue by shyrgelber** [Prospress/woocommerce-subscribe-all-the-things#139]
Hi there, I have downloaded this plugin though it seems that I can't edit the labels so that it makes sense on the front end for the customer. I played around in inspector - is it possible to edit the labels somewhere so it looks like my screenshot? Thank you! 
Here is my page where issue is: https://www.fortythieves.co.nz/product/cacao-hazelnut-with-toasted-coconut/

What it currently looks like: 
<img width="434" alt="screen shot 2017-06-21 at 10 37 36 am" src="https://user-images.githubusercontent.com/29587201/27362028-7dcc1ea6-567f-11e7-91ec-aa2d4c01d3c5.png">
What I'd like it to look like: 
<img width="465" alt="screen shot 2017-06-21 at 10 37 12 am" src="https://user-images.githubusercontent.com/29587201/27362031-7fd64708-567f-11e7-8f53-d71011997ca3.png">

**Comment by seb86** [comment]
@shyrgelber I suggest you install version 2.0 there is a new branch for it. The plugin is currently being reviewed before merging into the master branch ready for a new release.

**Comment by shyrgelber** [comment]
Oh great - have done that and the "array" labels are fixed. Any chance I can change the option "none" to "one time purchase"?

**Comment by shyrgelber** [comment]
I managed to fix that one too. Final question - how do I remove starting price and mention of subscription? I am happy to simply have the 'one time puchase' price. 
<img width="446" alt="screen shot 2017-06-21 at 3 49 41 pm" src="https://user-images.githubusercontent.com/29587201/27366309-63ab3150-5699-11e7-8f52-bd94625e2153.png">
<img width="295" alt="screen shot 2017-06-21 at 3 49 31 pm" src="https://user-images.githubusercontent.com/29587201/27366311-65060958-5699-11e7-8085-a4df32df51ae.png">

**Comment by franticpsyx** [comment]
@shyrgelber You'll need to write some custom code to do this.

In SATT v2, a price string like this will be generated when no subscription scheme is set on the object -- when `WCS_ATT_Product::get_subscription_scheme( $product )` returns `null`. 

What you need is to hook into `woocommerce_get_price_html` (possibly conditionally, in the single-product summary) and if the product displayed:

- `WCS_ATT_Product::has_subscriptions( $product ) === true`;
- `WCS_ATT_Product::get_subscription_scheme( $product ) === null`;
- `WCS_ATT_Product::has_forced_subscription( $product ) === false`;

then return the price that corresponds to the "one-time" state: `WCS_ATT_Product::get_price_html( $product, false )`.

Note that `false` here refers to the "one-time" state.

If you need help writing that code, you could check to see if @seb86 could put some time aside to help you out.

**Comment by shyrgelber** [comment]
Thanks very much @franticpsyx unfortunately I'm not a developer and have tried to follow your instructions but haven't quite figured out how to fix it. @seb86 if you do have a moment to help me, that would be really fantastic. Thank you!

**Comment by seb86** [comment]
@shyrgelber Can you kindly please contact me via email to continue as this is not an issue with the plugin but a customisation and only issues should be commented here. Thank you.
