### ISSUE TITLE
Price display issue

### ISSUE THREAD

**Issue by souellette** [Prospress/woocommerce-subscribe-all-the-things#140]
The price showing for example 79.95$ / Array instead of month

![screen shot 2017-06-23 at 11 57 45 am](https://user-images.githubusercontent.com/3178372/27490156-354d8196-580b-11e7-8a0b-5f97ba373bc4.png)

**Comment by thenbrent** [comment]
Hi @souellette this is a [known issue](https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20price%20array) related to WC 3.0 compatibility (#96).

We have a (very large) open pull request which included 3.0 compatibility, as well as this issue. Once it is merged, it will be fixed. See #136. Sorry for the trouble.

**Comment by souellette** [comment]
any ideas of when its going to be fixed ?

thanks for the help
