### ISSUE TITLE
Use string for text domain, not class constant

### ISSUE THREAD

**Issue by thenbrent** [Prospress/woocommerce-subscribe-all-the-things#141]
SATT currently uses `WCS_ATT::TEXT_DOMAIN` as the text domain. The text domain should be a plain string. Not a variable or constant.

See:

* https://markjaquith.wordpress.com/2011/10/06/translating-wordpress-plugins-and-themes-dont-get-clever/
* http://ottopress.com/2012/internationalization-youre-probably-doing-it-wrong/
* https://ulrich.pogson.ch/string-text-domain-must (which disagrees with the reasoning of the above, but still agrees a variable or constant shouldn't be used)

The `'woocommerce-subscribe-all-the-things'` string literal should be used instead of `WCS_ATT::TEXT_DOMAIN`.

**Comment by franticpsyx** [comment]
This is pretty much a leftover from when we were looking for a name. I've reminded myself to open an issue about this a few times in the past, so glad you noticed!

**Comment by franticpsyx** [comment]
Tempted to fix this in the v2 branch, but I will wait until after we merge. 😈
