### ISSUE TITLE
missing subscription option on frontend

### ISSUE THREAD

**Issue by dmorton2** [Prospress/woocommerce-subscribe-all-the-things#143]
Am using the Mix and Match and Subscription plugin with this ext.

in the product 'Subscription Options' iv add 2, monthly and weekly but on the front end i can not see any option to select a 'monthly' or 'weekly' subscription ?

**Comment by dmorton2** [comment]
After some searching i see its not compatible with the latest version am using! 
i've found and older version of Mix and Match v1.1.2 but again it still dose not show up :-(
This would have been perfect what i require... anyone got an idea how to fix this...HELP

**Comment by franticpsyx** [comment]
@dmorton2 SATT v1 is not compatible with WooCommerce 3.0.
v2, which supports WooCommerce 3.0 and the latest version of Mix & Match is currently being [reviewed](https://github.com/Prospress/woocommerce-subscribe-all-the-things/pull/136) and will be [released](https://github.com/Prospress/woocommerce-subscribe-all-the-things/releases) soon! :)

Note that Mix-and-Match bundles with **Per Item Pricing** enabled are not supported!

Hope this helps!

**Comment by dmorton2** [comment]
Thanks for the update, looking forward to the new release.
