### ISSUE TITLE
Set up Travis

### ISSUE THREAD

**Issue by franticpsyx** [Prospress/woocommerce-subscribe-all-the-things#144]
See https://github.com/Prospress/woocommerce-subscriptions-gifting

cc @jconroy -- in case if you have any quick tips/gotchas to share from experience.

**Comment by jconroy** [comment]
Off the top of my head the main gotcha will be if you need pull in a private repo (like subscriptions). 

There are a few options e.g. https://docs.travis-ci.com/user/private-dependencies/ - the most straight forward was using an API token https://docs.travis-ci.com/user/private-dependencies/#API-Token

On gifting we add it as an envcrypted env variable - the downside is that the variable isn't available to pull requests from forks - so those PRs will always fail.

To get around that I  _think_ we could actually use the `encrypt` command and add the token to the `.travis.yml` file. e.g. https://docs.travis-ci.com/user/encryption-keys/#Usage

Looks like the documentation around this stuff has improved a heap in the last 12-18months.

I can help out next week if you'd like.

**Comment by franticpsyx** [comment]
@jimjasson want to take a look and teach me something new? We could schedule this for next Friday, but if your plate is full next week feel free to postpone.

**Comment by franticpsyx** [comment]
@jconroy it's been a while but thanks for chiming in here :)

> if you need pull in a private repo (like subscriptions)

As expected, we got stuck trying to figure out how to get Travis to clone the private WCS repo. While we can register an environment variable and use it like you did in WCS Gifting, to my understanding this isn't going to work with PRs from forks.

After looking at the Travis docs we still couldn't figure out what needs to be done in order to make this work universally.

We've been able to set up Travis for our private repos -- here it looks like we could use some help.

**Comment by franticpsyx** [comment]
@jconroy -- see #265 

I think the only missing bit is cloning the WCS repo. 

FYI we get this when running unit tests locally with WC 3.3:

`PHP Fatal error:  require_once(): Failed opening required '/srv/www/sites/travis/woocommerce/tests/framework/factories/class-wc-unit-test-factory-for-webhook.php' (include_path='.:/usr/share/php') in /srv/www/sites/travis/woocommerce-subscriptions/tests/bootstrap.php on line 151`

**Comment by thenbrent** [comment]
@franticpsyx we've got an open issue to fix that issue with the WC 3.3 unit tests now: https://github.com/Prospress/woocommerce-subscriptions/issues/2547

**Comment by jconroy** [comment]
howdy gang, sorry for the delay, I'll try my hardest to get around to looking into the encryption keys within the next week

**Comment by franticpsyx** [comment]
Thanks @jconroy -- I hoped we'd solve this on our side, but the fact this is a public repo with a private repo as a dependency complicates things a bit. Travis docs contain lots of information but they are written in a rather confusing/convoluted way (no clear steps to follow, previous knowledge of cryptic stuff assumed, etc). At some point both @jimjasson and I felt like the best way forward would be to ask for help.

With SATT we thought it makes sense to make sure PRs submitted from forks would be handled with no issues but couldn't figure out how to do that.
