### ISSUE TITLE
$subscription_period displayed as text 'Array'

### ISSUE THREAD

**Issue by ishmaelangelo** [Prospress/woocommerce-subscribe-all-the-things#146]
WC_SATT saves the subscription parameters together as serialized data with meta key _wcsatt_schemes  in wp_postmeta.
(wp-content/plugins/woocommerce-subscribe-all-the-things/includes/admin/class-wcsatt-admin.php 221)

However $option[ 'description' ] is displayed as '$40.47 / Array' instead of something like '$40.47 / Month'
(wp-content/plugins/woocommerce-subscribe-all-the-things/templates/single-product/satt-product-options.php 35)

$options have descriptions made from $sub_price_html. $subscription_scheme goes in with correct data, but $sub_price_html comes out with incorrect output when passed to WC_Subscriptions_Product::get_price_string()
(wp-content/plugins/woocommerce-subscribe-all-the-things/includes/class-wcsatt-display.php 170)

WC_Subscriptions_Product::get_price_string() eventually looks for the meta_key _subscription_period that a WC_Subscriptions_Product has, but a Single Product (or any other non-WC_Subscriptions_Product) would not have this meta_key.

So it seems that we can't depend on WC_Subscriptions_Product::get_price_string() and we need to write our own function to return the price string constructed from $subscription_scheme.

**Comment by franticpsyx** [comment]
@ishmaelangelo Have a look at https://github.com/Prospress/woocommerce-subscribe-all-the-things/pull/136

Sounds like the Product API we are introducing in v2 might be useful to you.
 
Also note SATT v1 is not compatible with WC 3.0+.

**Comment by ishmaelangelo** [comment]
Great. I'm ready to do testing on v2 when it's ready. Let me know if there is anything else I can help with. Thanks
