### ISSUE TITLE
Product price not showing

### ISSUE THREAD

**Issue by umang-dev** [Prospress/woocommerce-subscribe-all-the-things#149]
Hello Guys,

  I am using woocommerce subscribe all the things 2.0 version. i am getting following error on admin.

Fatal error: Call to a member function has_price_filter() on string in /home/petwant1/public_html/wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/class-wcsatt-scheme-prices.php on line 149

due to this error price does not displaying. please help us to solve this issue

**Comment by umang-dev** [comment]
Also I am getting these errors after updating woocommerce version to 3.0.1.

**Comment by franticpsyx** [comment]
@umang-dev Can't replicate using the latest `2.0` dev version. Note this is an alpha version and a work-in-progress branch.

We will be tagging a beta version soon so I would suggest waiting for that one if you are not able to track down the cause of the issue and/or send a PR.
