### ISSUE TITLE
[2.0] Handling of renewals/resubscriptions when the active subscription scheme no longer exists

### ISSUE THREAD

**Issue by franticpsyx** [Prospress/woocommerce-subscribe-all-the-things#153]
See https://github.com/Prospress/woocommerce-subscribe-all-the-things/pull/136#discussion_r124692666

To be fixed:

- [x] General handling of cart items with an incorrectly applied scheme.
- [x] Handling of products with deleted scheme when re-subscribing.
- [x] Handling of products with deleted scheme when renewing.

**Comment by thenbrent** [comment]
I'm not if this will be comprehensive, but here's some tips.

### Prevent Resubscribe

The easiest way to prevent a subscriber [resubscribing](https://docs.woocommerce.com/document/subscriptions/customers-view/#section-16) after the scheme has been deleted is to use the `'wcs_can_user_resubscribe_to_subscription'` filter. Hopefully the params are all self explanatory. 

### Handle Renewal

This is how renewal on a deleted product is handled: when attempting to renew the product via cart, if it has been deleted, a notice will be added to explain the product can't be purchased but `WC()->cart->add_to_cart()` will still be called with the product, only it won't work.

This process can be seen here: https://github.com/Prospress/woocommerce-subscriptions/blob/2.2.8/includes/class-wcs-cart-renewal.php#L243:L269

That approach is probably also sufficient for products with deleted schemes.

The `'woocommerce_add_to_cart_validation'` can be used to implement it. That should also prevent other unforeseen occasions where a customer is attempting to purchase a product with an invalid scheme.

**Comment by franticpsyx** [comment]
@thenbrent thanks for the tips! I think I am quite familiar with the product/cart side of WCS. This time it looks like we will not be able to count on WCS to do the heavy lifting without some hacking.

> Use the 'wcs_can_user_resubscribe_to_subscription' filter. Hopefully the params are all self explanatory [..]

The problem is that all that code runs only if a cart item has been converted to a subscription by SATT _already_. If the originally purchased scheme doesn't exist, then SATT fails silently and the item in the cart is seen as a subscription-less product.

This most likely means we need to implement some sort of basic failure handling in SATT. There is an even simpler need for this. Consider the following scenario:

- Customer adds product in the cart.
- At the same time, shop owner changes the subscription schemes attached to the product.
- Customer attempts to check out. The originally selected scheme is not there anymore.
- To prevent the product from being purchased as a "vanilla" product, we need to add some logic to SATT.

Remember SATT does the conversion on session load. When the "scheme setting" fails, what happens is that the "scheme to apply" (stored in `$cart_item[ 'satt_data' ][ 'active_subscription_scheme' ]` and obtained via `WCS_Cart::get_subscription_scheme( $cart_item )`) will not be consistent with `WCS_ATT_Product::get_subscription_scheme( $cart_item[ 'data' ] )`.

And here you see the main difference between the two methods -- the former tells you which scheme "should" have been set on the object associated with that cart item, while the latter one which is actually set on it.

The easiest way to handle this is to do a check on `woocommerce_check_cart_items` and show a notice.

The "proper" way to handle this would be to show a helpful notice that informs the customer that the subscription plan he/she purchased no longer exists, and perhaps prompt them to choose a new one if multiple plans are available.

The latter approach has some complications, because we probably need to:

- detect the situation on session load, 
- "pre-activate" another subscription scheme, and
- rely on the inconsistency between "scheme to set" and "scheme actually set" to show a context-specific message/error in different situations (resubscribe, renew, or initial).

I have the impression that renewal should always fail with an error message, as it doesn't make sense to renew a subscription when the original scheme is no longer offered.

> This is how renewal on a deleted product is handled [..]

I was thinking that "ideally" it should be possible to keep renewing an existing subscription until it ends, even if the scheme(s) attached to the product have changed.

What if the shop owner wants to change the subscription details? What happens to existing subscribers (assuming renewals are paid manually?).

I was looking at WCS code trying to decipher all of this and make a decision that's consistent with the current behavior.

**Comment by franticpsyx** [comment]
PS: Note that some of these complications arise from the fact that SATT inherently includes "switching" features that make switching easy _in the cart_. 

So while digging into all of this, it became apparent to me that I needed to see how WCS handles switching, too. 🌵

**Comment by franticpsyx** [comment]
Updated list of to-dos.

**Comment by franticpsyx** [comment]
> General handling of cart items with an incorrectly applied scheme.

Again, the scenario we want to deal with as a start:

- Customer adds product in the cart.
- At the same time, shop owner changes the subscription schemes attached to the product.
- Customer attempts to check out. The originally selected scheme is not there anymore.

To tackle this, we need to add some new cart item validation logic in SATT which should be there regardless of how we will handle the other 2 to-do's. [Here's](https://github.com/Prospress/woocommerce-subscribe-all-the-things/commit/8e028846e9ae4b9802e587031cf2d61395e880f1) one approach.

The gist of it:

- The "subscription to set" is saved in `$cart_item[ 'wcsatt_data' ][ 'active_subscription_scheme' ]` and retrieved via `WCS_ATT_Cart::get_subscription_scheme`. An attempt is made to apply it on the product object associated with a cart item by calling `WCS_ATT_Cart::apply_subscription_scheme`. This happens on `woocommerce_cart_loaded_from_session`.
- If the attempt fails, the actual scheme on the object is reset to `null`.
- The result: `WCS_ATT_Product::get_subscription_scheme` will return `null` and `WCS_ATT_Cart::get_subscription_scheme` will return something else.
- The mismatch is picked up on `woocommerce_check_cart_items` and an error notice is added. If possible, the user is prompted to choose a new scheme option in order to continue, e.g. https://cl.ly/0h0f3n3c0m37 .
- In more extreme cases, the user is not given an opportunity to resolve the situation, e.g. https://cl.ly/050Z3m1J0g3X and https://cl.ly/3l0J0r352Q2E . In some situations, we could allow the user to resolve the error condition by adding an "OK, fix this for me" button next to the notice.

The next step -- see how the other items on the issue list are affected by this patch.

I suspect that we might be able to re-use some this logic to prevent re-subscriptions or renewals without hooking into WCS?

**Comment by thenbrent** [comment]
> I suspect that we might be able to re-use some this logic to prevent re-subscriptions or renewals without hooking into WCS?

Yes definitely. Ideally this is handled just once.

> The mismatch is picked up on woocommerce_check_cart_items and an error notice is added. If possible, the user is prompted to choose a new scheme option in order to continue

That sounds good, what about instead:

1. not adding the product to the cart
1. redirecting the customer to the product page
1. displaying the notice there

The product page is handy in case there are other things that need to be set/chosen in relation to choosing a new subscription scheme/product (e.g. if product add-ons, or something else is associated).

Also just to clarify, this would address:

1. resubscribes
1. initial purchase

It does not necessarily relate to _renewals_. For those, I agree with what you said:

> it should be possible to keep renewing an existing subscription until it ends, even if the scheme(s) attached to the product have changed

To do that there is a good approach we can use that we use for Subscriptions too: don't add a _subscription with scheme to the cart_, instead just add the product without a scheme and use renewal meta data to link it back to the subscription (hopefully all of that should be taken care of already by `WCS_Cart_Renewal` without any special effort on SATT's part).

> An attempt is made to apply it on the product object associated with a cart item by calling `WCS_ATT_Cart::apply_subscription_scheme. This happens on `woocommerce_cart_loaded_from_session`.

In case it's useful, we also use `'woocommerce_cart_loaded_from_session'` and `'woocommerce_get_cart_item_from_session'` in a few places already to handle similar situations. See:

* `WCS_Cart_Renewal::get_cart_item_from_session()`
* `WCS_Cart_Renewal::cart_items_loaded_from_session()`
* `WC_Subscriptions_Switcher::get_cart_item_from_session()`

**Comment by franticpsyx** [comment]
> To do that there is a good approach we can use that we use for Subscriptions too: don't add a subscription with scheme to the cart, instead just add the product without a scheme and use renewal meta data to link it back to the subscription (hopefully all of that should be taken care of already by `WCS_Cart_Renewal` without any special effort on SATT's part).

👍 Sounds like we might need to remove all scheme data from the object when renewing. Then our general sanity-checking [logic](https://github.com/Prospress/woocommerce-subscribe-all-the-things/commit/8e028846e9ae4b9802e587031cf2d61395e880f1) won't even kick in, and (hopefully) the problem will solve itself.

**Comment by franticpsyx** [comment]
https://github.com/Prospress/woocommerce-subscribe-all-the-things/commit/2ca4d1684d39ef71008be762289c71fc0b3f9a09 removes all scheme data from the object when renewing and prevents our cart validation logic kicking in.

Renewals go through fine even if the original scheme no longer exists.

Initial subscription payments are also handled well, I think. Here's what happens when attempting to pay for a failed initial subscription order and the original scheme no longer exists:

<img width="1140" alt="failedpay" src="https://user-images.githubusercontent.com/1783726/28191310-277b6e6a-6838-11e7-8db3-acf5b95190fc.png">

**Comment by franticpsyx** [comment]
> Here's what happens when attempting to pay for a failed initial subscription order and the original scheme no longer exists

> what about instead / not adding the product to the cart / redirecting the customer to the product page

Not sure about this. Would be nice if only attempting to resub / pay-the-initial-order for a single product, but a subscription may include multiple items _in general_.

**Comment by franticpsyx** [comment]
> Here's what happens when attempting to pay for a failed initial subscription order and the original scheme no longer exists

The existing logic appears to work when re-subscribing, as well. If the original scheme is unavailable, resubscribing shouldn't work as the "terms" have changed.
