### ISSUE TITLE
Fatal error on Cart page

### ISSUE THREAD

**Issue by steven-cotterill** [Prospress/woocommerce-subscribe-all-the-things#154]
Hi all, I am receiving a Fatal Error on the Cart page. I am currently running:

+ WordPress 4.8
+ Flatsome theme 3.3.7
+ WooCommerce 3.1.0
+ WooCommerce Subscriptions 2.2.8
+ WooCommerce SATT 1.1.2
+ A number of other plugins, all up to date.

This was working fine until I recently updated to the newest versions of everything. Any help here would be great.

Thanks, error below:

------------------------------------

`Fatal error: Uncaught Exception: Invalid product. in /var/www/public/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php:134 Stack trace: #0 /var/www/public/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(147): WC_Product_Data_Store_CPT->read(Object(WC_Product)) #1 /var/www/public/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php(126): WC_Data_Store->read(Object(WC_Product)) #2 /var/www/public/wp-content/plugins/woocommerce-subscribe-all-the-things/includes/class-wcsatt-display.php(392): WC_Product->__construct('1') #3 /var/www/public/wp-includes/class-wp-hook.php(298): WCS_ATT_Display::show_subscribe_to_cart_prompt('') #4 /var/www/public/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #5 /var/www/public/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #6 /var/www/public/wp-content/plugins/woocommerce/templates/cart/cart-totals.php(26): do_action('woocommerce_bef...') #7 /var/www/public/wp-content/plugins/woocommerce/in in /var/www/public/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php on line 134`

**Comment by franticpsyx** [comment]
@steven-cotterill SATT v1 is not compatible with WC 3.0+

We are currently [finalizing](https://github.com/Prospress/woocommerce-subscribe-all-the-things/pull/136) work on SATT v2 which will support WC 3.0+.

**Comment by steven-cotterill** [comment]
Hi, sorry to open this again. Is there any type of timescale for v2?

**Comment by franticpsyx** [comment]
@steven-cotterill We should have a beta version tagged around mid-July.

**Comment by steven-cotterill** [comment]
Cheers!
