### ISSUE TITLE
_subscription_schemes metakey issue with woocommerce 3.0.1

### ISSUE THREAD

**Issue by umang-dev** [Prospress/woocommerce-subscribe-all-the-things#158]
Hello Guys,

         I am using woocommerce version 3.0.1 with woocommerce-subscribe-all-the-things 2.0 tree from github. In previous woocommerce when i edit product from backend it doest not give me error and all products display well. but with woocommerce version 3.0.1 , i am getting following error:

PHP Fatal error:  Call to a member function has_price_filter() on string in /home/petwant1/public_html/wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/class-wcsatt-scheme-prices.php on line 149

Above error makes problem on displaying product on backend and front end. when i go to database i found metakey named "_subscription_schemes" on postmeta table. when i remove this metakey, error is solved. and this metakey added when i am editing previously create product and update. please help me to solve this problem. i am waiting for plugin update. i can not rollback to previous version.

Thanks,
Umang.

**Comment by franticpsyx** [comment]
@umang-dev Do you remember when you installed v2.0 for the first time? That key should not have been saved in your database if you installed SATT in the last month or so.

**Comment by umang-dev** [comment]
Hello,
  I have installed v2.0 in end of april or may. I have then updated code 2 or more time from github page 2.0 tree. Can this problem be solved? Can you help me?

**Comment by franticpsyx** [comment]
@umang-dev Sounds like you might need to delete all occurrences of the "runtime" `_subscription_schemes` meta from your database manually. We have added some code to ensure this won't happen with the stable version.

Beyond bug-fixing, there is little more we can do -- running alpha/beta software on a live website is (as always) not for the faint-hearted.
