### ISSUE TITLE
Array text and wrong price

### ISSUE THREAD

**Issue by jakeperrin** [Prospress/woocommerce-subscribe-all-the-things#159]
It displays array where it should show the frequency.  Also the subscription price doesn't carry over to the cart.  Here is how I have things:

Product price...
http://cloud.jakeperrin.com/3Y0g1C0F202n

Subscription...
http://cloud.jakeperrin.com/0d1G3K3H2H0t

Product page...
http://cloud.jakeperrin.com/0J2C3m0a103V

Cart...
http://cloud.jakeperrin.com/0F1M263w0c3g

**Comment by ozguruzden** [comment]
I have the exact same issue.

**Comment by ozguruzden** [comment]
You can see from these screenshots;
http://prntscr.com/fsxg61
http://prntscr.com/fsxgiz

I use woocommerce 3.0

**Comment by franticpsyx** [comment]
See https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/124
