### ISSUE TITLE
Shows double subscription period

### ISSUE THREAD

**Issue by zielo** [Prospress/woocommerce-subscribe-all-the-things#171]
Subscription details that shows period are doubled. 
![capture1](https://user-images.githubusercontent.com/6492978/28119872-fffa78f0-671e-11e7-9255-c60895e12dc9.PNG)

And here:
![capture](https://user-images.githubusercontent.com/6492978/28119931-30e49b12-671f-11e7-9805-8ee4285a0caa.PNG)

How to remove the extra <span subsription-details..?

**Comment by franticpsyx** [comment]
@zielo Can you please share WC / SATT / WCS version info? Thanks!

**Comment by zielo** [comment]
@franticpsyx thanks for prompt reply. Here it is WC: 3.1.1 / SATT: 1.1.2 / WCS  2.2.7 thanks

**Comment by franticpsyx** [comment]
SATT v1 is not compatible with WC 3.0+

We are currently [finalizing](https://github.com/Prospress/woocommerce-subscribe-all-the-things/pull/136) work on SATT v2 which will support WC 3.0+.
