### ISSUE TITLE
Different discount options not compatible in one single product page

### ISSUE THREAD

**Issue by ly148** [Prospress/woocommerce-subscribe-all-the-things#172]
It seems like the subscription option with extra discount doesn't work at all. 

![image](https://user-images.githubusercontent.com/10776604/28180070-fa4dd934-67d1-11e7-9d1e-3c244832e2a7.png)

I wanted to encourage customers to subscribe by adding a 40% discount plus 1st-month free trial, while the one-time purchase discount is 30%. Then I added the subscription option to cart and checked out, but it turned out the one-time purchase discount overwriting the subscription discount. 

![image](https://user-images.githubusercontent.com/10776604/28180441-1d95e214-67d3-11e7-9b44-4294fd876f06.png)

Anyone knows how to fix this? Thansk!!

**Comment by seb86** [comment]
Please provide your WooCommerce System Status report so we can take a look. Thank you.

**Comment by ly148** [comment]
Please see attached, thanks!
[Woocommerce System Report.txt](https://github.com/Prospress/woocommerce-subscribe-all-the-things/files/1153644/Woocommerce.System.Report.txt)

**Comment by franticpsyx** [comment]
@ly148 Can't replicate -- @seb86 thanks so much for helping out! Looks like a plugin conflict, or version-related issue.

**Comment by ly148** [comment]
@franticpsyx @seb86 Thanks for your reply! @franticpsyx Could you please give a hint of which specific plugin leads to the problem? Thanks!

**Comment by franticpsyx** [comment]
@ly148 could you please install [2.0.0 Beta 1](https://github.com/Prospress/woocommerce-subscribe-all-the-things/releases/tag/2.0.0-beta.1) and re-test **after de-activating all plugins except**:

- WC
- WCS
- SATT

Thanks!

**Comment by ly148** [comment]
@franticpsyx It works!! Thank you so much!

**Comment by franticpsyx** [comment]
@ly148 Thanks for the follow-up!

Note that if you are using any custom code on top of SATT (such as snippets, template overrides or plugins), you will need to update that to work with SATT v2.

It looks like you are using a plugin to enable Free Trials with SATT -- if so, then you will need to ensure that the version you are running is fully compatible with SATT v2!
