### ISSUE TITLE
Can't purchase SATT product - Internal Server Error at checkout

### ISSUE THREAD

**Issue by sambomcd** [Prospress/woocommerce-subscribe-all-the-things#175]
Not sure if anyone else is running into this.

Using SATT 2.0. I am getting the above when attempting to purchase a product that has had an SATT sub set for it. Works fine for 'One off' purchase, but if I select one of the Sub options the above error is received. WC shows status as Payment Pending.

It appears sometimes Stripe is registering payment, other times not?

Environment: WC 3.1.1, WCS 2.2.8, WC Stripe 3.2.2 (I first saw the issue at 3.2.1 then updated to see if it had any affect).

**Comment by sambomcd** [comment]
After further testing, this seems to be happening on a standard (non-SATT) subscription too. So I am going to guess this is either a problem my end, or a WCS issue or a Stripe issue. But looks like it isn't a SATT issue. Apologies.

**Comment by thenbrent** [comment]
Thanks for letting us know @sambomcd

**Comment by sambomcd** [comment]
Apologies - meant to closed this myself.
