### ISSUE TITLE
When will be the final release of SATT v2?

### ISSUE THREAD

**Issue by aljohnrey** [Prospress/woocommerce-subscribe-all-the-things#177]
Do you the have  SATT v2 of "Subscribe All the things" now?

**Comment by thenbrent** [comment]
Current progress is in https://github.com/Prospress/woocommerce-subscribe-all-the-things/pull/136

We're aiming to have a public release done within the next couple of weeks. Sorry for the delay.

**Comment by aljohnrey** [comment]
Ack

Thank you for the response!
