### ISSUE TITLE
[2.0] Drop WC 2.6 support

### ISSUE THREAD

**Issue by franticpsyx** [Prospress/woocommerce-subscribe-all-the-things#178]
WooCommerce 2.6 support needs to be dropped. We have decided to continue supporting WC 3.0 only due to the excessive number of breaking changes that 3.0 introduced.

Since the resources we have available for developing and maintaining SATT are limited, we have decided that it's better to focus on the future of the project rather than its past.

**Comment by franticpsyx** [comment]
@thenbrent This will be the last one before we tag 2.0.0 beta.

**Comment by seb86** [comment]
I was thinking the same thing today. Its important that we support the plugin properly and not hold ourselves back to deliver a great product. Otherwise its just more work for something that will eventually be done for nothing at the going rate that WooCommerce is improving.
