### ISSUE TITLE
Status change to on-hold on Renewal

### ISSUE THREAD

**Issue by ozguruzden** [Prospress/woocommerce-subscribe-all-the-things#179]
Hi there,
I created a subscription with SATT2 on WC3.
Subscription reneval period is daily. When subscription tried to renew, it becomes on-hold status and does not create new order.

I also created subscription product with subscription plugin to see if problem is related to my payment gateway or not, it works. 

I am not sure if it is related to my system or not but there can be a bug.

**Comment by seb86** [comment]
Can you provide us with your WooCommerce System Status report. Thank you.

**Comment by ozguruzden** [comment]
Of course, here it is,

`
### WordPress Environment ###

Home URL: http://52.29.1.8
Site URL: http://52.29.1.8
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: tr_TR

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.15-0ubuntu0.16.04.4
PHP Post Max Size: 512 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.18
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Sunucunuzda SoapClient sınıfı etkinleştirilmiş durumda değil; SOAP kullanan bazı ağ geçidi eklentileri
beklendiği şekilde çalışmayabilir.

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Mağazanız HTTPS kullanmıyor. HTTPS and SSL sertifikaları hakkında bilgi alın.
Hide errors from visitors: ✔

### Active Plugins (39) ###

WooCommerce Order Status & Actions Manager: (Actuality Extensions) – 2.1.2
BAW Login/Logout menu: (Juliobox) – 1.3.3
Contact Form 7: (Takayuki Miyoshi) – 4.8
Envato WordPress Toolkit: (Envato) – 1.7.3
EWWW Image Optimizer: (Shane Bishop) – 3.5.0
Flexible Checkout Fields: (WP Desk) – 1.5.1
Force Regenerate Thumbnails: (Pedro Elsner) – 2.0.6
HTML Javascript Adder: (Aakash Chakravarthy) – 3.9
WordPress.com’dan Jetpack: (Automattic) – 5.1
WPBakery Visual Composer: (Michael M - WPBakery.com) – 5.1.1
MailChimp for WooCommerce: (MailChimp) – 2.0.0
Mobile Assistant Connector: (eMagicOne) – 1.3.7
PayTR - WooCommerce eklentisi: (ali.yilmaz) – 1.1
Popup Builder: (Popup Builder) – 2.6.2
Privileged Menu: (Benjamin Guy) – 1.8.4
PushEngage: (Radha Krishna B) – 1.4.4
SUMO Reward Points: (Fantastic Plugins) – 17.6
Security Headers: (Simon Waters (Surevine Ltd)) – 0.9
WPML Multilingual CMS: (OnTheGoSystems) – 3.7.0
Tawk.to Live Chat: (Tawkto) – 0.3.1
UpdraftPlus - Backup/Restore: (UpdraftPlus.Com
DavidAnderson) – 1.13.4

Abandoned Cart Reports For WooCommerce: (Small Fish Analytics) – 2.2.0
WooCommerce Catalog Visibility Options: (Lucas Stark) – 2.8.3 – 3.0.1 mevcut
WooCommerce Colors: (WooThemes) – 1.0.6
WooCommerce Conditional Shipping and Payments: (WooThemes) – 1.2.1 – 1.2.7 mevcut
Woocommerce AC Iyzico Güvenli Ödeme: (Abdullah Ceylan) – 1.0.2
WooCommerce Login Popup and Shortcodes: (Phpbits Creative Studio) – 1.0.1
WooCommerce Product Badge: (Terry Tsang) – 1.0.4
WooCommerce Shipping Per Product v2: (WooThemes) – 2.2.8 – 2.2.10 mevcut
WooCommerce Subscribe All the Things: (Prospress Inc.) – 2.0.0-alpha
WooCommerce Subscriptions: (Prospress Inc.) – 2.2.8 – 2.2.9 mevcut
WooCommerce TL Birimi: (Halil Kaya ) – 2.2
WooCommerce: (Automattic) – 3.1.1
Yoast SEO: (Yoast ekibi) – 5.0.2
WordPress Social Login: (Miled) – 2.3.3
WP File Manager: (mndpsingh287) – 1.6
WP Smush: (WPMU DEV) – 2.7.1
WPML String Translation: (OnTheGoSystems) – 2.5.3
WPML Translation Management: (OnTheGoSystems) – 2.3.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: TRY (TL)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Mağaza giriş sayfası: #200 - /magaza/
Sepet: #201 - /sepet/
Ödeme: #202 - /odeme/
Hesabım sayfası: #203 - /hesabim/

### Theme ###

Name: Bridge Child
Version: 1.0.0
Author URL: http://www.qodethemes.com/
Child Theme: ✔
Parent Theme Name: Bridge
Parent Theme Version: 11.1
Parent Theme Author URL: http://www.qodethemes.com/
WooCommerce Support: ✔

### Templates ###

Archive Template: Temanızın bir woocommerce.php dosyası var; woocommerce.php dosyasının archive-product.php üzerinde önceliği olduğu için woocommerce/archive-product.php yolunu geçersiz kılamazsınız. Bunun amacı
görüntüleme sorularını önlemektir.

Overrides: bridge/woocommerce/cart/cart-empty.php
bridge/woocommerce/cart/cart-shipping.php
bridge-child/woocommerce/cart/cart-totals.php
bridge-child/woocommerce/cart/cart.php 2.3.8 sürümü güncel değil. Çekirdek sürüm: 3.1.0
bridge/woocommerce/cart/shipping-calculator.php
bridge/woocommerce/checkout/form-coupon.php
bridge-child/woocommerce/checkout/thankyou.php
bridge-child/woocommerce/content-product.php 2.6.1 sürümü güncel değil. Çekirdek sürüm: 3.0.0
bridge/woocommerce/content-single-product.php
bridge/woocommerce/global/form-login.php
bridge/woocommerce/global/quantity-input.php
bridge/woocommerce/loop/add-to-cart.php
bridge-child/woocommerce/loop/loop-start.php
bridge/woocommerce/loop/pagination.php
bridge/woocommerce/loop/rating.php
bridge/woocommerce/loop/result-count.php
bridge-child/woocommerce/loop/sale-flash.php
bridge-child/woocommerce/myaccount/form-login.php
bridge/woocommerce/myaccount/form-lost-password.php
bridge/woocommerce/myaccount/my-address.php
bridge/woocommerce/myaccount/my-orders.php
bridge/woocommerce/single-product/add-to-cart/external.php
bridge/woocommerce/single-product/add-to-cart/grouped.php
bridge/woocommerce/single-product/add-to-cart/simple.php
bridge/woocommerce/single-product/add-to-cart/variable.php
bridge/woocommerce/single-product/related.php
bridge/woocommerce/single-product/sale-flash.php
bridge/woocommerce/single-product/tabs/additional-information.php
bridge/woocommerce/single-product/tabs/description.php
bridge/woocommerce/single-product/tabs/tabs.php
bridge/woocommerce/single-product/up-sells.php

Outdated Templates: ❌Nasıl güncelleştirileceğini öğrenin

### subscriptions ###

WCS_DEBUG: ✔ Hayır
Subscriptions Mode: ✔ Live
`

**Comment by franticpsyx** [comment]
Hey @ozguruzden -- could you please install [2.0.0 Beta 1](https://github.com/Prospress/woocommerce-subscribe-all-the-things/releases/tag/2.0.0-beta.1) and re-test?

If the issue persists, could you provide some more details:

- Which gateway are you using?
- What type of product are you testing? 
- A screenshot of the "Subscriptions" tab of that product.
- A screenshot of your **WooCommerce > Settings > Subscriptions** page.

Thanks!

**Comment by franticpsyx** [comment]
Tested using https://github.com/somewherewarm/woocommerce-gateway-dummy to process auto renewals without issues.

Manual renewals also appear to work fine here.

**Comment by ozguruzden** [comment]
Very sorry, I could not checked with beta due to my travel.
I will update plugin and re-test.

**Comment by ozguruzden** [comment]
Hi again,
I created new subscription with beta version and the problem goes on.

**Which gateway are you using?** - Woocommerce AC Iyzico Güvenli Ödeme: (Abdullah Ceylan) – 1.0.2
**What type of product are you testing?** - Basic Procuct
**A screenshot of the "Subscriptions" tab of that product.** http://prntscr.com/fyy8wt
**A screenshot of your WooCommerce > Settings > Subscriptions page.** http://prntscr.com/fyy9cs  - http://prntscr.com/fyy9iy

**Comment by franticpsyx** [comment]
@ozguruzden I have looked into this again but couldn't replicate.

**On-hold** indicates that the renewal order was not processed correctly - not sure why that might be but it seems to be a gateway-related issue. It's very likely that your gateway might dislike something about SATT?

Unfortunately there is little more I can look at on the SATT side. Our [capacity to support SATT](https://github.com/Prospress/woocommerce-subscribe-all-the-things#support) is limited to fixing issues that we can replicate locally. This is something that we'd need to investigate on your website, and unfortunately we don't have the resources to offer that kind of service right now.

Perhaps you could consider working with a developer to track down the exact cause of the problem? I personally recommend @seb86 (not sure if he is available though).

If you manage to find the culprit and it happens to be in SATT, we'll be happy to help patch things up!

**Comment by seb86** [comment]
@ozguruzden There is one way to verify if it is the payment gateway at fault and that is to do a simple subscription, not a SATT subscription.

**Comment by franticpsyx** [comment]
@seb86 I think @ozguruzden actually tried that:

> I also created subscription product with subscription plugin to see if problem is related to my payment gateway or not, it works.

There might be something specific to SATT that a gateway might not like, who knows. Can't assume something else at this point.

**Comment by seb86** [comment]
@franticpsyx Oh, must of missed that comment. This is interesting. Do you have any logs created by the Payment Gateway? They can be found under WooCommerce > System Status > Logs.

**Comment by franticpsyx** [comment]
Closing -- feel free to update this if you bump onto something that could help us replicate the issue locally.

**Comment by ozguruzden** [comment]
Sorry, I could not have an attention about the issue for a while. @seb86 , I will share logs today, ı am waiting for the renewal for new subscription with SATT. As it tries to renew, I will share logs of payment gateway.

**Comment by ozguruzden** [comment]
@seb86 interesting, the payment is started but it is not ended like standart subscription. @franticpsyx My payment gateway does not like SATT =)

`07-08-2017 @ 10:12:11 - İşlem yanıtı: {"status":"success","locale":"tr","systemTime":1499501531568,"price":28.00000000,"paidPrice":28.00000000,"installment":1,"paymentId":"10354794","fraudStatus":1,"merchantCommissionRate":0E-8,"merchantCommissionRateAmount":0E-8,"iyziCommissionRateAmount":0.73500000,"iyziCommissionFee":0.25000000,"cardType":"CREDIT_CARD","cardAssociation":"MASTER_CARD","cardFamily":"Axess","cardToken":"ieeIwxrqxmDOoKLwG5foeLKKjw8=","cardUserKey":"Wgn5rWW9Rd9PqKWO1aKti/ZogOM=","binNumber":"552608","lastFourDigits":"0006","basketId":"1321","currency":"TRY","itemTransactions":[{"itemId":"1319","paymentTransactionId":"10619540","transactionStatus":2,"price":28.00000000,"paidPrice":28.00000000,"merchantCommissionRate":0E-8,"merchantCommissionRateAmount":0E-8,"iyziCommissionRateAmount":0.73500000,"iyziCommissionFee":0.25000000,"blockageRate":10.00000000,"blockageRateAmountMerchant":2.80000000,"blockageRateAmountSubMerchant":0E-8,"blockageResolvedDate":"2017-07-16 00:00:00","subMerchantPrice":0E-8,"subMerchantPayoutRate":0E-8,"subMerchantPayoutAmount":0E-8,"merchantPayoutAmount":24.21500000,"convertedPayout":{"paidPrice":28.00000000,"iyziCommissionRateAmount":0.73500000,"iyziCommissionFee":0.25000000,"blockageRateAmountMerchant":2.80000000,"blockageRateAmountSubMerchant":0E-8,"subMerchantPayoutAmount":0E-8,"merchantPayoutAmount":24.21500000,"iyziConversionRate":0E-8,"iyziConversionRateAmount":0E-8,"currency":"TRY"}}],"authCode":"mock00007iyziauthcd","phase":"AUTH","token":"dc14ad2d-621d-4679-9fbc-ca04da206b32","callbackUrl":"https://52.29.1.8/odeme/order-received/1321?key=wc_order_596093b3dd1d5&wc-api=WC_Gateway_AC_Iyzico","paymentStatus":"SUCCESS"}
07-08-2017 @ 14:08:45 - İşlem yanıtı: {"status":"success","locale":"tr","systemTime":1499515725411,"price":30.00000000,"paidPrice":30.00000000,"installment":1,"paymentId":"10354831","fraudStatus":1,"merchantCommissionRate":0E-8,"merchantCommissionRateAmount":0E-8,"iyziCommissionRateAmount":0.78750000,"iyziCommissionFee":0.25000000,"cardType":"CREDIT_CARD","cardAssociation":"MASTER_CARD","cardFamily":"Axess","cardToken":"ieeIwxrqxmDOoKLwG5foeLKKjw8=","cardUserKey":"Wgn5rWW9Rd9PqKWO1aKti/ZogOM=","binNumber":"552608","lastFourDigits":"0006","basketId":"1333","currency":"TRY","itemTransactions":[{"itemId":"1332","paymentTransactionId":"10619637","transactionStatus":2,"price":30.00000000,"paidPrice":30.00000000,"merchantCommissionRate":0E-8,"merchantCommissionRateAmount":0E-8,"iyziCommissionRateAmount":0.78750000,"iyziCommissionFee":0.25000000,"blockageRate":10.00000000,"blockageRateAmountMerchant":3.00000000,"blockageRateAmountSubMerchant":0E-8,"blockageResolvedDate":"2017-07-16 00:00:00","subMerchantPrice":0E-8,"subMerchantPayoutRate":0E-8,"subMerchantPayoutAmount":0E-8,"merchantPayoutAmount":25.96250000,"convertedPayout":{"paidPrice":30.00000000,"iyziCommissionRateAmount":0.78750000,"iyziCommissionFee":0.25000000,"blockageRateAmountMerchant":3.00000000,"blockageRateAmountSubMerchant":0E-8,"subMerchantPayoutAmount":0E-8,"merchantPayoutAmount":25.96250000,"iyziConversionRate":0E-8,"iyziConversionRateAmount":0E-8,"currency":"TRY"}}],"authCode":"mock00007iyziauthcd","phase":"AUTH","token":"f2875e39-12c7-4588-b203-de1f86dd93de","callbackUrl":"https://52.29.1.8/odeme/order-received/1333?key=wc_order_5960cb3406167&wc-api=WC_Gateway_AC_Iyzico","paymentStatus":"SUCCESS"}
07-16-2017 @ 11:15:02 - Bilgi: 28.00 tutarındaki 1337 siparişi için abonelik bedeli ödeme işlemi başladı.
07-16-2017 @ 11:15:07 - Success: iyzico ile abonelik yenileme işlemi tamamlandı (10404616).
07-16-2017 @ 11:30:04 - İşlem yanıtı: {"status":"success","locale":"tr","systemTime":1500197404002,"price":47.73000000,"paidPrice":47.73000000,"installment":1,"paymentId":"10404617","fraudStatus":1,"merchantCommissionRate":0E-8,"merchantCommissionRateAmount":0E-8,"iyziCommissionRateAmount":1.25291250,"iyziCommissionFee":0.25000000,"cardType":"CREDIT_CARD","cardAssociation":"MASTER_CARD","cardFamily":"Axess","cardToken":"ieeIwxrqxmDOoKLwG5foeLKKjw8=","cardUserKey":"Wgn5rWW9Rd9PqKWO1aKti/ZogOM=","binNumber":"552608","lastFourDigits":"0006","basketId":"1339","currency":"TRY","itemTransactions":[{"itemId":"822","paymentTransactionId":"10755377","transactionStatus":2,"price":47.73000000,"paidPrice":47.73000000,"merchantCommissionRate":0E-8,"merchantCommissionRateAmount":0E-8,"iyziCommissionRateAmount":1.25291250,"iyziCommissionFee":0.25000000,"blockageRate":10.00000000,"blockageRateAmountMerchant":4.77300000,"blockageRateAmountSubMerchant":0E-8,"blockageResolvedDate":"2017-07-24 00:00:00","subMerchantPrice":0E-8,"subMerchantPayoutRate":0E-8,"subMerchantPayoutAmount":0E-8,"merchantPayoutAmount":41.45408750,"convertedPayout":{"paidPrice":47.73000000,"iyziCommissionRateAmount":1.25291250,"iyziCommissionFee":0.25000000,"blockageRateAmountMerchant":4.77300000,"blockageRateAmountSubMerchant":0E-8,"subMerchantPayoutAmount":0E-8,"merchantPayoutAmount":41.45408750,"iyziConversionRate":0E-8,"iyziConversionRateAmount":0E-8,"currency":"TRY"}}],"authCode":"mock00007iyziauthcd","phase":"AUTH","token":"f3a98482-1f57-40f7-8d50-0ba90eac6b15","callbackUrl":"https://52.29.1.8/odeme/order-received/1339?key=wc_order_596b31fc39cc8&wc-api=WC_Gateway_AC_Iyzico","paymentStatus":"SUCCESS"}
07-16-2017 @ 13:41:31 - İşlem yanıtı: {"status":"success","locale":"tr","systemTime":1500205291119,"price":29.25000000,"paidPrice":29.25000000,"installment":1,"paymentId":"10404649","fraudStatus":1,"merchantCommissionRate":0E-8,"merchantCommissionRateAmount":0E-8,"iyziCommissionRateAmount":0.76781250,"iyziCommissionFee":0.25000000,"cardType":"CREDIT_CARD","cardAssociation":"MASTER_CARD","cardFamily":"Axess","cardToken":"ieeIwxrqxmDOoKLwG5foeLKKjw8=","cardUserKey":"Wgn5rWW9Rd9PqKWO1aKti/ZogOM=","binNumber":"552608","lastFourDigits":"0006","basketId":"1344","currency":"TRY","itemTransactions":[{"itemId":"822","paymentTransactionId":"10755424","transactionStatus":2,"price":29.25000000,"paidPrice":29.25000000,"merchantCommissionRate":0E-8,"merchantCommissionRateAmount":0E-8,"iyziCommissionRateAmount":0.76781250,"iyziCommissionFee":0.25000000,"blockageRate":10.00000000,"blockageRateAmountMerchant":2.92500000,"blockageRateAmountSubMerchant":0E-8,"blockageResolvedDate":"2017-07-24 00:00:00","subMerchantPrice":0E-8,"subMerchantPayoutRate":0E-8,"subMerchantPayoutAmount":0E-8,"merchantPayoutAmount":25.30718750,"convertedPayout":{"paidPrice":29.25000000,"iyziCommissionRateAmount":0.76781250,"iyziCommissionFee":0.25000000,"blockageRateAmountMerchant":2.92500000,"blockageRateAmountSubMerchant":0E-8,"subMerchantPayoutAmount":0E-8,"merchantPayoutAmount":25.30718750,"iyziConversionRate":0E-8,"iyziConversionRateAmount":0E-8,"currency":"TRY"}}],"authCode":"mock00007iyziauthcd","phase":"AUTH","token":"e755d6d7-2c82-421d-9925-d909364a7d77","callbackUrl":"https://52.29.1.8/odeme/order-received/1344?key=wc_order_596b50d141237&wc-api=WC_Gateway_AC_Iyzico","paymentStatus":"SUCCESS"}
07-17-2017 @ 14:49:20 - Bilgi: 29.25 tutarındaki 1347 siparişi için abonelik bedeli ödeme işlemi başladı.
07-17-2017 @ 17:52:54 - İşlem yanıtı: {"status":"success","locale":"tr","systemTime":1500306774557,"price":1.00000000,"paidPrice":1.00000000,"installment":1,"paymentId":"10408967","fraudStatus":1,"merchantCommissionRate":0E-8,"merchantCommissionRateAmount":0E-8,"iyziCommissionRateAmount":0.02625000,"iyziCommissionFee":0.25000000,"cardType":"CREDIT_CARD","cardAssociation":"MASTER_CARD","cardFamily":"Axess","cardToken":"ieeIwxrqxmDOoKLwG5foeLKKjw8=","cardUserKey":"Wgn5rWW9Rd9PqKWO1aKti/ZogOM=","binNumber":"552608","lastFourDigits":"0006","basketId":"1349","currency":"TRY","itemTransactions":[{"itemId":"1330","paymentTransactionId":"10766096","transactionStatus":2,"price":1.00000000,"paidPrice":1.00000000,"merchantCommissionRate":0E-8,"merchantCommissionRateAmount":0E-8,"iyziCommissionRateAmount":0.02625000,"iyziCommissionFee":0.25000000,"blockageRate":10.00000000,"blockageRateAmountMerchant":0.10000000,"blockageRateAmountSubMerchant":0E-8,"blockageResolvedDate":"2017-07-25 00:00:00","subMerchantPrice":0E-8,"subMerchantPayoutRate":0E-8,"subMerchantPayoutAmount":0E-8,"merchantPayoutAmount":0.62375000,"convertedPayout":{"paidPrice":1.00000000,"iyziCommissionRateAmount":0.02625000,"iyziCommissionFee":0.25000000,"blockageRateAmountMerchant":0.10000000,"blockageRateAmountSubMerchant":0E-8,"subMerchantPayoutAmount":0E-8,"merchantPayoutAmount":0.62375000,"iyziConversionRate":0E-8,"iyziConversionRateAmount":0E-8,"currency":"TRY"}}],"authCode":"mock00007iyziauthcd","phase":"AUTH","token":"50d6636b-ab1b-49be-bc7b-1c5012d3c3de","callbackUrl":"https://52.29.1.8/odeme/order-received/1349?key=wc_order_596cdd1b52fad&wc-api=WC_Gateway_AC_Iyzico","paymentStatus":"SUCCESS"}
07-18-2017 @ 15:21:35 - Bilgi: 29.25 tutarındaki 1352 siparişi için abonelik bedeli ödeme işlemi başladı.
07-18-2017 @ 17:56:15 - Bilgi: 1.00 tutarındaki 1353 siparişi için abonelik bedeli ödeme işlemi başladı.
07-18-2017 @ 17:56:17 - Success: iyzico ile abonelik yenileme işlemi tamamlandı (10438839).
07-19-2017 @ 18:11:12 - Bilgi: 1.00 tutarındaki 1355 siparişi için abonelik bedeli ödeme işlemi başladı.
07-19-2017 @ 18:11:14 - Success: iyzico ile abonelik yenileme işlemi tamamlandı (10440063).
07-20-2017 @ 19:15:05 - Bilgi: 1.00 tutarındaki 1357 siparişi için abonelik bedeli ödeme işlemi başladı.
07-20-2017 @ 19:15:08 - Success: iyzico ile abonelik yenileme işlemi tamamlandı (10441158).
07-21-2017 @ 15:52:30 - İşlem yanıtı: {"status":"success","locale":"tr","systemTime":1500645150846,"price":29.25000000,"paidPrice":29.25000000,"installment":1,"paymentId":"10441945","fraudStatus":1,"merchantCommissionRate":0E-8,"merchantCommissionRateAmount":0E-8,"iyziCommissionRateAmount":0.76781250,"iyziCommissionFee":0.25000000,"cardType":"CREDIT_CARD","cardAssociation":"MASTER_CARD","cardFamily":"Axess","cardToken":"ieeIwxrqxmDOoKLwG5foeLKKjw8=","cardUserKey":"Wgn5rWW9Rd9PqKWO1aKti/ZogOM=","binNumber":"552608","lastFourDigits":"0006","basketId":"1361","currency":"TRY","itemTransactions":[{"itemId":"822","paymentTransactionId":"10856806","transactionStatus":2,"price":29.25000000,"paidPrice":29.25000000,"merchantCommissionRate":0E-8,"merchantCommissionRateAmount":0E-8,"iyziCommissionRateAmount":0.76781250,"iyziCommissionFee":0.25000000,"blockageRate":10.00000000,"blockageRateAmountMerchant":2.92500000,"blockageRateAmountSubMerchant":0E-8,"blockageResolvedDate":"2017-07-29 00:00:00","subMerchantPrice":0E-8,"subMerchantPayoutRate":0E-8,"subMerchantPayoutAmount":0E-8,"merchantPayoutAmount":25.30718750,"convertedPayout":{"paidPrice":29.25000000,"iyziCommissionRateAmount":0.76781250,"iyziCommissionFee":0.25000000,"blockageRateAmountMerchant":2.92500000,"blockageRateAmountSubMerchant":0E-8,"subMerchantPayoutAmount":0E-8,"merchantPayoutAmount":25.30718750,"iyziConversionRate":0E-8,"iyziConversionRateAmount":0E-8,"currency":"TRY"}}],"authCode":"mock00007iyziauthcd","phase":"AUTH","token":"74a4fc0d-a4a0-4156-9210-2e30b80263e8","callbackUrl":"https://52.29.1.8/odeme/order-received/1361?key=wc_order_597207039c085&wc-api=WC_Gateway_AC_Iyzico","paymentStatus":"SUCCESS"}
07-21-2017 @ 19:34:52 - Bilgi: 1.00 tutarındaki 1364 siparişi için abonelik bedeli ödeme işlemi başladı.
07-21-2017 @ 19:34:55 - Success: iyzico ile abonelik yenileme işlemi tamamlandı (10442262).
07-22-2017 @ 17:34:38 - Bilgi: 29.25 tutarındaki 1366 siparişi için abonelik bedeli ödeme işlemi başladı.
07-22-2017 @ 18:05:39 - Bilgi: 29.25 tutarındaki 1367 siparişi için abonelik bedeli ödeme işlemi başladı.
07-22-2017 @ 19:36:03 - Bilgi: 1.00 tutarındaki 1368 siparişi için abonelik bedeli ödeme işlemi başladı.
07-22-2017 @ 19:36:06 - Success: iyzico ile abonelik yenileme işlemi tamamlandı (10442726).
07-23-2017 @ 19:50:21 - Bilgi: 1.00 tutarındaki 1370 siparişi için abonelik bedeli ödeme işlemi başladı.
07-23-2017 @ 19:50:24 - Success: iyzico ile abonelik yenileme işlemi tamamlandı (10443128).
07-24-2017 @ 20:23:21 - Bilgi: 1.00 tutarındaki 1372 siparişi için abonelik bedeli ödeme işlemi başladı.
07-24-2017 @ 20:23:24 - Success: iyzico ile abonelik yenileme işlemi tamamlandı (10444358).
07-25-2017 @ 21:55:57 - Bilgi: 1.00 tutarındaki 1374 siparişi için abonelik bedeli ödeme işlemi başladı.
07-25-2017 @ 21:55:59 - Success: iyzico ile abonelik yenileme işlemi tamamlandı (10445613).
07-26-2017 @ 22:31:08 - Bilgi: 1.00 tutarındaki 1376 siparişi için abonelik bedeli ödeme işlemi başladı.
07-26-2017 @ 22:31:10 - Success: iyzico ile abonelik yenileme işlemi tamamlandı (10446727).
07-27-2017 @ 22:49:29 - Bilgi: 1.00 tutarındaki 1378 siparişi için abonelik bedeli ödeme işlemi başladı.
07-27-2017 @ 22:49:32 - Success: iyzico ile abonelik yenileme işlemi tamamlandı (10447976).
07-28-2017 @ 23:00:36 - Bilgi: 1.00 tutarındaki 1380 siparişi için abonelik bedeli ödeme işlemi başladı.
07-28-2017 @ 23:00:38 - Success: iyzico ile abonelik yenileme işlemi tamamlandı (10449158).
07-29-2017 @ 23:17:47 - Bilgi: 1.00 tutarındaki 1382 siparişi için abonelik bedeli ödeme işlemi başladı.
07-29-2017 @ 23:17:50 - Success: iyzico ile abonelik yenileme işlemi tamamlandı (10449442).
07-31-2017 @ 00:07:15 - Bilgi: 1.00 tutarındaki 1384 siparişi için abonelik bedeli ödeme işlemi başladı.
07-31-2017 @ 00:07:18 - Success: iyzico ile abonelik yenileme işlemi tamamlandı (10477203).
08-01-2017 @ 00:20:54 - Bilgi: 1.00 tutarındaki 1386 siparişi için abonelik bedeli ödeme işlemi başladı.
08-01-2017 @ 00:20:56 - Success: iyzico ile abonelik yenileme işlemi tamamlandı (10493283).
08-02-2017 @ 01:18:50 - Bilgi: 1.00 tutarındaki 1388 siparişi için abonelik bedeli ödeme işlemi başladı.
08-02-2017 @ 01:18:52 - Success: iyzico ile abonelik yenileme işlemi tamamlandı (10494553).
08-02-2017 @ 19:00:36 - Bilgi: 29.25 tutarındaki 1392 siparişi için abonelik bedeli ödeme işlemi başladı.
`

**Comment by seb86** [comment]
@ozguruzden Is this the [payment gateway](https://codeaffairs.com/product/paytr-payment-gateway/)?

**Comment by ozguruzden** [comment]
@seb86 yes sen,this iş the payment gateway. 
It started payment for Satt subscription but according to log it did not completed.

**Comment by seb86** [comment]
@ozguruzden Have you contacted the developers of the payment gateway to see what they say? If the payment gateway acknowledges that the order is a subscription then something must not be registering on their end when you return to the site.

**Comment by franticpsyx** [comment]
Closing as we can't solve this on our end anyway.
