### ISSUE TITLE
Just updated - subscription time periods not displaying correctly on product page

### ISSUE THREAD

**Issue by pat1121** [Prospress/woocommerce-subscribe-all-the-things#181]
First of all, thank you. This plugin does exactly what I want and it's been awesome for the last few months!!

Just downloaded the latest version, and updated the version from January by deactivating the old plugin and activating the new one.

Now instead of $XX.xx / Month, my product pages show $XX.xx / array. Any idea's where I can find and fix this? I have tried deleting the old subscription data from the edit product page and adding in new data without any luck.

The offending page:
http://thelongevityedge.com/product/ultra-potent-fish-oil/

**Comment by pat1121** [comment]
I just reverted back to the old version until I can figure out the issue, the demo page above will appear correctly for now.

**Comment by franticpsyx** [comment]
@pat1121 

Please make sure you are testing with [this](https://github.com/Prospress/woocommerce-subscribe-all-the-things/releases/tag/2.0.0-beta.1) version.

If you have any custom code or plugins that run on top of SATT you may need to get them updated to work with v2.0.
