### ISSUE TITLE
woocommerce-subscribe-all-the-things theme issue

### ISSUE THREAD

**Issue by aljohnrey** [Prospress/woocommerce-subscribe-all-the-things#185]
Hi Guys

I am having an issue with the said plugin.

`
### WordPress Environment ###

Home URL: http://staging.salusco.com
Site URL: http://staging.salusco.com
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.18
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.51 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (51) ###

Advanced Custom Fields: by Elliot Condon – 4.4.11
AffiliateWP: by AffiliateWP
LLC – 2.1.2

AffiliateWP - Affiliate Dashboard Sharing: by Pippin Williamson and Andrew Munro – 1.1.3
Akismet Anti-Spam: by Automattic – 3.3.3
Alipay For WooCommerce: by CodingPet – 1.3.4
Approved Comment Notifier: by Remi Corson – 1.0
Auto Login New User After Registration: by Jeff Sherk – 1.5.2
BackWPup: by Inpsyde GmbH – 3.4.1
Contact Form 7: by Takayuki Miyoshi – 4.8.1
Duplicator: by Snap Creek – 1.2.14
Embed Google AdWords Codes on WooCommerce: by StoreYa – 1.2
Export User Data: by Q Studio – 1.3.1
Facebook Conversion Pixel: by Kellen Mace – 1.3.5
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.2.0
Instagram Feed: by Smash Balloon – 1.4.9
Loco Translate: by Tim Whitlock – 2.0.14
MailChimp for WordPress Pro: by ibericode – 2.7.26
Monarch Plugin: by Elegant Themes – 1.2.1
Multiple Post Thumbnails: by Chris Scott – 1.6.6
WooCommerce Product Bundles - Hide Bundled Item Prices: by SomewhereWarm – 1.0
Product Sales Report for WooCommerce: by Potent Plugins – 1.4.8
Really Simple CAPTCHA: by Takayuki Miyoshi – 2.0
ReferralCandy for WooCommerce: by ReferralCandy – 1.3.1
WooCommerce Shippit: by Shippit Pty Ltd – 1.3.6
Store Locator for Resparkle: by FLINT Creative – 2.1
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.13.4

Users Insights: by Pexeto – 3.1.1
Aelia Foundation Classes for WooCommerce: by Aelia – 1.8.9.170629
WooCommerce Subscription & Bundle Reporting: by HostGeek – 1.0.0
WooCommerce Subscription Reminder Email: by HostGeek – 1.0.0
WooCommerce Weight Based Shipping: by weightbasedshipping.com – 5.1.0
Abandoned Cart Lite for WooCommerce: by Tyche Softwares – 4.1
WooCommerce Advanced Free Shipping: by Jeroen Sormani – 1.1.2
WooCommerce Advanced Review Reminder: by kodemann.com – 1.6.4
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.2.7
WooCommerce Conversion Tracking: by Tareq Hasan – 1.2.2
WooCommerce Pin Payments Gateway: by Tyson Armstrong – 1.7.4
WooCommerce One Page Checkout: by Prospress Inc. – 1.5.1 – 1.5.2 is available
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.0.3
WooCommerce Product Bundles: by SomewhereWarm – 5.3.1 – 5.4.0 is available
WooCommerce Subscribe All the Things: by Prospress Inc. – 2.0.0-beta.1
WooCommerce Subscriptions: by Prospress Inc. – 2.2.8 – 2.2.10 is available
WooCommerce Table Rate Shipping: by Bolder Elements – 3.6.2
WooCommerce: by Automattic – 3.1.1
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO: by Team Yoast – 5.0.2
WordPress Database Backup: by Austin Matzko – 2.3.1
WP Maintenance Mode: by Designmodo – 2.0.9
WP-PostViews: by Lester 'GaMerZ' Chan – 1.75
WP Rollback: by WordImpress – 1.5
Refer a Friend for WooCommerce PREMIUM: by WPGens – 1.2.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Resparkle
Version: 1.2.0
Author URL: http://www.flcs.co
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: resparkle/woocommerce/archive-product.php
resparkle/woocommerce/cart/cart-empty.php
resparkle/woocommerce/cart/cart-item-data.php
resparkle/woocommerce/cart/cart-shipping.php
resparkle/woocommerce/cart/cart-totals.php
resparkle/woocommerce/cart/cart.php
resparkle/woocommerce/cart/cross-sells.php
resparkle/woocommerce/cart/mini-cart.php
resparkle/woocommerce/cart/proceed-to-checkout-button.php
resparkle/woocommerce/cart/shipping-calculator.php
resparkle/woocommerce/checkout/cart-errors.php
resparkle/woocommerce/checkout/form-billing.php
resparkle/woocommerce/checkout/form-checkout.php
resparkle/woocommerce/checkout/form-coupon.php
resparkle/woocommerce/checkout/form-login.php
resparkle/woocommerce/checkout/form-pay.php
resparkle/woocommerce/checkout/form-shipping.php
resparkle/woocommerce/checkout/payment-method.php
resparkle/woocommerce/checkout/payment.php
resparkle/woocommerce/checkout/review-order.php
resparkle/woocommerce/checkout/thankyou.php
resparkle/woocommerce/content-product.php
resparkle/woocommerce/content-product_cat.php
resparkle/woocommerce/content-single-product.php
resparkle/woocommerce/emails/admin-cancelled-order.php
resparkle/woocommerce/emails/admin-new-order.php
resparkle/woocommerce/emails/customer-completed-order.php
resparkle/woocommerce/emails/customer-invoice.php
resparkle/woocommerce/emails/customer-note.php
resparkle/woocommerce/emails/customer-processing-order.php
resparkle/woocommerce/emails/customer-reset-password.php
resparkle/woocommerce/emails/email-addresses.php
resparkle/woocommerce/emails/email-footer.php
resparkle/woocommerce/emails/email-header.php
resparkle/woocommerce/emails/email-order-items.php
resparkle/woocommerce/emails/email-styles.php
resparkle/woocommerce/emails/plain/admin-cancelled-order.php
resparkle/woocommerce/emails/plain/admin-new-order.php
resparkle/woocommerce/emails/plain/customer-completed-order.php
resparkle/woocommerce/emails/plain/customer-invoice.php
resparkle/woocommerce/emails/plain/customer-new-account.php
resparkle/woocommerce/emails/plain/customer-note.php
resparkle/woocommerce/emails/plain/customer-processing-order.php
resparkle/woocommerce/emails/plain/customer-reset-password.php
resparkle/woocommerce/emails/plain/email-addresses.php
resparkle/woocommerce/emails/plain/email-order-items.php
resparkle/woocommerce/loop/add-to-cart.php
resparkle/woocommerce/loop/loop-end.php
resparkle/woocommerce/loop/loop-start.php
resparkle/woocommerce/loop/no-products-found.php
resparkle/woocommerce/loop/orderby.php
resparkle/woocommerce/loop/pagination.php
resparkle/woocommerce/loop/price.php
resparkle/woocommerce/loop/rating.php
resparkle/woocommerce/loop/result-count.php
resparkle/woocommerce/loop/sale-flash.php
resparkle/woocommerce/myaccount/my-account.php
resparkle/woocommerce/myaccount/my-orders.php
resparkle/woocommerce/single-product/add-to-cart/external.php
resparkle/woocommerce/single-product/add-to-cart/grouped.php
resparkle/woocommerce/single-product/add-to-cart/simple.php
resparkle/woocommerce/single-product/add-to-cart/variable.php
resparkle/woocommerce/single-product/meta.php
resparkle/woocommerce/single-product/price.php
resparkle/woocommerce/single-product/product-attributes.php
resparkle/woocommerce/single-product/product-image.php
resparkle/woocommerce/single-product/product-thumbnails.php
resparkle/woocommerce/single-product/rating.php
resparkle/woocommerce/single-product/related.php
resparkle/woocommerce/single-product/review.php
resparkle/woocommerce/single-product/sale-flash.php
resparkle/woocommerce/single-product/share.php
resparkle/woocommerce/single-product/short-description.php
resparkle/woocommerce/single-product/tabs/description.php
resparkle/woocommerce/single-product/title.php
resparkle/woocommerce/single-product/up-sells.php
resparkle/woocommerce/single-product-reviews.php
resparkle/woocommerce/single-product.php

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
`

I hope you can help me fix this issue

Please see attached screenshot:

![test](https://user-images.githubusercontent.com/28753362/28599715-55688028-71df-11e7-852e-a61565912df3.png)

**Comment by aljohnrey** [comment]
@seb86 Per your advise, I have created a new ticket for this issue. To be more specific on this issue, I would like to know if the price amount section has a new design in the new version of subscribe all the things plugin, as shown in the screenshot above? In the older version, it says "Select a delivery plan" while in the new version, it says "Choose a subscription plan". Below is the design of the old version which is the one installed in the live site. Our customer is very meticulous so we want to make sure that we will be able to explain this to her when she'll notice the difference.

![screenshot_4](https://user-images.githubusercontent.com/28753362/28608866-d6143304-7214-11e7-8c10-fa80a19ed6d6.png)

**Comment by franticpsyx** [comment]
@aljohnrey SATT templates file styles have not changed. The change you are showing us probably has its origin somewhere else.

**Comment by aljohnrey** [comment]
@franticpsyx Can you take a look on it for me please? 
It would be a big help for us if we fix this one

**Comment by franticpsyx** [comment]
@aljohnrey -- please have a look at https://github.com/Prospress/woocommerce-subscribe-all-the-things#support

If you need help with customizations or issues with third-party plugins, you best bet would be to hire a developer to assist as we can't provide that kind of service for free. @seb86 might be available -- I would recommend sending him a DM to check.

**Comment by seb86** [comment]
@aljohnrey I have responded to your email.
