### ISSUE TITLE
Subscription renewal for individual products instead for Mix n` Match product

### ISSUE THREAD

**Issue by zielo** [Prospress/woocommerce-subscribe-all-the-things#187]
Hi I`m using WC 3+ and SATT v.2 beta.

There`s some problem when trying to renew Mix n Match container (product) so it picks individual products instead.

When a first time customer checks out with a Mix n` Match subscription product it gets charged by what I have set the price to be for MnM product. So it works as it should.

Strangely, when customer tries to renew it`s subscription the checkout page will no longer charge per subscription but instead shows the total price of the individual items that were previously ordered (items that were bought in the same MnM container).

Off course checkout is not possible and customer gets an error message asking to chose more items because it have selected too few.

**Comment by franticpsyx** [comment]
Hey @zielo -- can you share a couple screenshots, perhaps? Thanks!

**Comment by zielo** [comment]
Hi, the following screenshot is when trying to checkout with the renewal:
![capture2](https://user-images.githubusercontent.com/6492978/28874417-7127245c-779a-11e7-80b4-903a034bf7f8.PNG)

You can see that "Cezario Salotos" is added 4 times (it shows 0 sum because I`ve specified 0 value in this product page).

However, when buying same product as subscription it shows both the MnM product - Skubantiems and the individual products:
![capture3](https://user-images.githubusercontent.com/6492978/28874504-cc58e658-779a-11e7-96e5-3c01db19963c.PNG)

I think there could be a workaround if I set the prices for individual products and chose "Per item Pricing" in the Mix n Match product settings.
![capture4](https://user-images.githubusercontent.com/6492978/28874616-4c5786e8-779b-11e7-8835-7a8bf3318a46.PNG)

Maybe not the best option though...

**Comment by franticpsyx** [comment]
Hey @zielo -- thanks for the details!

We have been able to replicate this issue -- however this needs to be patched on the Mix-and-Match side.

The good news is we have already submitted a SATT compatibility patch to the MnM repository, so the fix should be included with the next version of MnM.

**Comment by franticpsyx** [comment]
ref: https://github.com/woocommerce/woocommerce-mix-and-match-products/issues/174
