### ISSUE TITLE
How to show subscription options on product archive page?

### ISSUE THREAD

**Issue by pawandeepsidhu** [Prospress/woocommerce-subscribe-all-the-things#189]
Hi there,

First of all, i will thank you for creating such a useful and user-friendly plugin for subscription options free of cost. I am trying to show subscription options on product archive page.

Can you please suggest me how i can do that.

Thanks

**Comment by franticpsyx** [comment]
@pawandeepsidhu see https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/191

For now it might be best to avoid displaying subscription options on catalog pages and change the `Add to cart` text to something more suitable when a product offers subscription options.
