### ISSUE TITLE
Subscription prompt not displaying / saving

### ISSUE THREAD

**Issue by willgorham** [Prospress/woocommerce-subscribe-all-the-things#193]
WP 4.8.1
WC 3.1.2
WCS 2.2.11
WC SATT RC-2.0
Storefront 2.2.5
No other plugins active

When I add text to the 'Subscription Prompt' field in the product editor and update the product, on refresh the field is again blank and the text doesn't display on the front end (I'm not 100% sure where it's supposed to display, but my assumption is right above the options on the single product page).

Before saving: https://cl.ly/2h1s3R3s051C
After saving: https://cl.ly/0b2o081i0g3a
Front end display: https://cl.ly/3J0m3K2E3k1H

I haven't taken the time to isolate the issue in the code, but I'll take a look and submit a PR if I can. Just wanted to get this down here first.

Thanks!

**Comment by franticpsyx** [comment]
Thanks @willgorham -- keep it coming 🗡
