### ISSUE TITLE
Non-subscription bundle with subscribe-able item shows irrelevant subscription options in cart

### ISSUE THREAD

**Issue by willgorham** [Prospress/woocommerce-subscribe-all-the-things#195]
WP 4.8.1
WC 3.1.2
WCS 2.2.11
WC PB 5.4.2
WC SATT RC-2.0
Storefront 2.2.5
No other plugins active

Screenshot: https://cl.ly/3O0L1V1N1z0b

To reproduce:
1. Create a simple product with at least one subscription option
2. Create a bundle that contains that product (no subscription options on the bundle)
3. Add the bundle to the cart

If you're buying a bundle without subscription options, It doesn't make sense to see subscription options on a bundled item.

**Comment by franticpsyx** [comment]
@willgorham This use case is not supported at the moment -- subscription-enabled products (via SATT) can't be added to bundles.

This needs to be supported on the Product Bundles side to work, and eventually it will.

For now, complex product types such as Bundles and Composites are only able to handle subscription options at container-level (and the selected subscription propagates down to their contents).

Hope this makes sense!

**Comment by willgorham** [comment]
@franticpsyx Yep that makes sense, I figured maybe the scheme options on the bundled item would be hidden in the cart because it's unsupported. 

Say I want to have a subscription option on a singular item. That item is also contained in a bundle, but I don't need to have subscriptions on bundled components. Leaving things as-is (and maybe hiding the cart options) seems to be fine. Do you see any issues with this? (Sometimes these subscription/bundle sentences feel like a maze 🤔 )

From testing, things seem to work ok - the bundled item gets _wcsatt_scheme set to 0 and everything goes through. I know you can't support customizations, but this seems more like trying to avoid customizations 😄. If you feel like it's out of your scope I totally understand.

Thanks!
