### ISSUE TITLE
Bad Wiki links

### ISSUE THREAD

**Issue by keeneyemedia** [Prospress/woocommerce-subscribe-all-the-things#197]
Hi Guys... really excited to start trying this out on a site.

I started into the Wiki, but the links on the Developer Guide are all bad. https://github.com/Prospress/woocommerce-subscribe-all-the-things/wiki/Brief-Developer-Guide-to-Subscribe-all-the-Things

Just letting you know. 
Thanks!

**Comment by franticpsyx** [comment]
@keeneyemedia -- updated, thanks for letting us know!
