### ISSUE TITLE
Variable products support

### ISSUE THREAD

**Issue by franticpsyx** [Prospress/woocommerce-subscribe-all-the-things#2]
Currently we do not allow subscription schemes to be defined for variable products -- when we do it, we could make this work at variation level, or we could simply ignore variations and use the existing "Subscriptions" tab to define subscription schemes at parent level.

**Comment by louis2b** [comment]
I was thinking at this as I'd find it very useful to be able to subscribe to different skus. 
It may be obvious but I was thinking, how it could look in terms of ux, for variable products. 

I see 2 options to be able to define subs schemes at variation level
1. Having subscription fields appear in the different variations settings (in the variations tab)
2. keeping a subs tab, and for each subs scheme be able to give the variations to which it should be applied 

Option 2 seems much more interesting as there could be tons of variations and setting subs schemes 1by1 could be frustrating. 

Plus I agree with @franticpsyx in #1 : variations is sthg that defines the products, and subscriptions schemes is more how you sell it. So they should be kept separated.

**Comment by franticpsyx** [comment]
Added to the 1.1 milestone - cc @thenbrent

**Comment by Ahrengot** [comment]
Is there a rough time frame for when 1.1 will be ready?

**Comment by franticpsyx** [comment]
>Is there a rough time frame for when 1.1 will be ready?

Hard to say - however, I can definitely say that we will be able to allocate more resources to SATT in Q2.

**Comment by Ahrengot** [comment]
Alright I'm still a little unclear on the time frame. I'm trying to figure out if we're talking about weeks or months, but it sounds like months — Correct?

**Comment by franticpsyx** [comment]
@thenbrent Can we perhaps brainstorm a few ideas about this to see what we want/need to implement?

@Ahrengot The main issue here is that we haven't specced this feature at all, so it's still unclear what the workload is going to be. We don't have a roadmap in place for SATT development, but we do have a pretty good idea of the features we want to prioritize - this is one of them. It's still hard to give an ETA, though - sorry I can't be more specific but the open source nature of the project makes it difficult to make any commitments.

**Comment by seb86** [comment]
@franticpsyx and @Ahrengot I think option one would be better for adding subscriptions to variation products.

I think it would be confusing to some users to go between tabs in order to apply subscription options per variation.

Plus there is the issue of the data being saved. If you placed the subscription options under it's own section, would it not require more work to identify each subscription option per variable option.

**Comment by thenbrent** [comment]
> Can we perhaps brainstorm a few ideas about this to see what we want/need to implement?

My 2c for now: I think using the Subscriptions tab to define schemes at the _variable level_ will be sufficient, at least for the first version. I'd like to see compelling use cases where each individual variation needs a unique subscription scheme before we build support for that.

**Comment by franticpsyx** [comment]
>I'd like to see compelling use cases where each individual variation needs a unique subscription scheme before we build support for that.

I think the reason we left that out in the first place was that, well, there's already the concept of Variable Subscriptions for this. The problem with Variable Susbcriptions, though, is that if you have X different subscription options and N variations to describe product properties, you need X*N variations to include the different subscription options - the sub options are not separated from the product attributes that make up the variations.

>using the Subscriptions tab to define schemes at the variable level will be sufficient

Even like this, it's still not exactly a walk in the park :) had a look earlier - some thought is needed to decide how to code price overrides + discounts into it:

- Price overrides apparently can't be defined at parent level, while discounts can (applied to all variations).
- In addition to that, we'll need to write some JS to update the prices displayed next to the sub options, depending on which variation is chosen, and how much the discount is. Not pretty - will require passing some data into JS.

**Comment by franticpsyx** [comment]
>some thought is needed to decide how to code price overrides + discounts into it

Considering all this, it might as well be simpler to just go straight to variation level, since we'll probably need to work at variation level anyway.

**Comment by franticpsyx** [comment]
>I think it would be confusing to some users to go between tabs in order to apply subscription options per variation.

:+1:. If we go straight to variation level, it's probably wiser to just duplicate the entire content displayed under the "Subscriptions" tab at variation level.

**Comment by seb86** [comment]
Two questions.

Q1. Does a single variation only have a single subscription option?
Q2. Do we hide all the subscription fields by default unless the user has ticked a checkbox for that variable?

**Comment by franticpsyx** [comment]
>Two questions.

If we go to variation level, you'll be able to do the same thing that you can do now from the Subscriptions tab, only for every single variation. The Subscriptions tab won't exist - the options will be displayed inside the variation metaboxes.

So choosing a variation will completely refresh (or hide) the "Choose a subscription" container.

You'll be able to have variations with sub options and variations without - basically every variation will have its own set of unique config options, including the options to i) prevent one-off purchases and ii) set a default sub option.

Does this make sense?

**Comment by seb86** [comment]
Yes, that makes sense. I was just confirming that a variation product would have the ability to have more than one subscription option as we do now for a simple product.

**Comment by thenbrent** [comment]
> going straight to variation level might make sense

Something not yet considered is how much harder for store owners this would be to work with it if they have more than a trivial number of variations. Can you imagine having to define the same 5 subscription schemes for 100 variations (which isn't actually that many)? The store owners would have to do approximately 1,500 mouse clicks, instead of 15 if we offer variable level .

There are bulk editing capabilities on Variable Subscriptions for handling this, which could of course be added if offering variation level subscription schemes here, but that is just part of the orders of magnitude more complexity I think we'll encounter when writing and maintain this to make variation level schemes usable.

I think it will be a mistake not to start with variable level schemes. It's much easier to _add_ variation level schemes later than it is to remove it if we find no one needs them. The need for a feature as complicated as this should be proven before it's developed.

> how to code price overrides + discounts

Do we really need to support specific price overrides for variable product subscription schemes?

IMO a % discount will be sufficient, which is a relative amount for the variations price so can be used at the variable level.

**Comment by franticpsyx** [comment]
>Something not yet considered is how much harder for store owners this would be to work with it if they have more than a trivial number of variations. Can you imagine having to define the same 5 subscription schemes for 100 variations (which isn't actually that many)? The store owners would have to do approximately 1,500 mouse clicks, instead of 15 if we offer variable level .

>There are bulk editing capabilities on Variable Subscriptions for handling this, which could of course be added if offering variation level subscription schemes here, but that is just part of the orders of magnitude more complexity I think we'll encounter when writing and maintain this to make variation level schemes usable.

Good points.

>Do we really need to support specific price overrides for variable product subscription schemes? IMO a % discount will be sufficient, which is a relative amount for the variations price so can be used at the variable level.

>The need for a feature as complicated as this should be proven before it's developed.

At odd as it might be, discounts + price overrides were the most requested features, which kind of makes sense considering the use cases for SATT vs vanilla Subs. There is no reason to assume that users will not need this variation level - we already have 2 requests for exactly this via e-mail, and roughly 2 more here.

I am a bit worried that doing this at product level will leave a lot to be desired in terms of functionality, while if we decide to go to variation-level we will only have to sacrifice some back-end usability - for instance by dropping bulk editing from the initial spec.

My other main point here (https://github.com/Prospress/woocommerce-subscribe-to-all-the-things/issues/2#issuecomment-203463148) was that even just with discounts, we will need to do some server-side work at variation-level *and* do some scripting work to in order to replace the text that is displayed in the subscription options list every time a new variation is selected. So most (if not all) of the structure required for variation-level handling will already be there.

**Comment by franticpsyx** [comment]
Closing - scale tipped to adding support at product level, for now. For details, refer to #32 and #35 .
