### ISSUE TITLE
Subscription price is not adding in cart in case of Bundled Product

### ISSUE THREAD

**Issue by pawandeepsidhu** [Prospress/woocommerce-subscribe-all-the-things#200]
I have a bundle of two products. Each product has its subscription. For example: Product, A is a simple product and has subscription price $74.95 and Product B is a variable Product and has subscription price $64.95. I created a bundle product C with Product A and Product B and set its subscription price $129.90. Now when i am adding product in cart its adding subscription price of Product A and Product B with $129.90. And the total becomes $74.95 + $64.95 + 129.90 = $269.80. But its should be $129.90 not $269.80

Can you please help me to fix it or the Subscribe All The Things plugin work like this.

Waiting for your response.
Thanks

**Comment by pawandeepsidhu** [comment]
Is there anyone to help me ??

**Comment by franticpsyx** [comment]
@pawandeepsidhu -- I believe this could answer your question: https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/195

> Subscription-enabled products (via SATT) can't be added to bundles. This needs to be supported on the Product Bundles side to work, and eventually it will. For now, complex product types such as Bundles and Composites are only able to handle subscription options at container-level (and the selected subscription propagates down to their contents).
