### ISSUE TITLE
Exclude products from cart subscription

### ISSUE THREAD

**Issue by hamblyfreeman** [Prospress/woocommerce-subscribe-all-the-things#204]
This is probably more of a feature request than an issue, but we have encountered a situation where we need some products added to the subscription, but others not. This is using the cart subscription method specifically as the site needs the checkout option to subscribe or to checkout as a one off.

Before I go and try and work out my own way of doing something, is there anything for the situation where not every product should be in the subscription? I was thinking of creating two categories (subscription products and non-subscription products) and working out a way to omit the non-subscription products from the recurring totals on cart/checkout and the products entirely from the subscription record.

Thanks in advance for any advice!

**Comment by thenbrent** [comment]
Hi @hamblyfreeman,

> is there anything for the situation where not every product should be in the subscription? 

No not yet.

> I was thinking of creating two categories (subscription products and non-subscription products) and working out a way to omit the non-subscription products from the recurring totals on cart/checkout and the products entirely from the subscription record.

That sounds like a pretty sane way to do it. If you're willing to submit it as a Pull Request to SATT, we can help spec out the best way to achieve that and point you in the right direction on where to do things as well as provide code review on the patch.

**Comment by hamblyfreeman** [comment]
Thanks for the reply, Brent. I'd love to... but we also found the issue with cart subscriptions and switching/editing subscriptions on the My Account page, so we're having to have a bit of a rethink on how we handle the subscription approach now.

I'll definitely keep an eye on the plugin development over the next few months though, it does 80% of what we need brilliantly!

**Comment by thenbrent** [comment]
Thanks for letting us know @hamblyfreeman, I'll close this one now.
