### ISSUE TITLE
Admin creating/editing Order - can't add SATT scheme

### ISSUE THREAD

**Issue by sambomcd** [Prospress/woocommerce-subscribe-all-the-things#205]
This may be a limitation of SATT at the moment, or just me being stupid, but:

If an Admin has to make changes to a customer's Subscription, or even create one on their behalf in the Admin console, how can they set a SATT scheme? 

My client has made changes to a few subscriptions on behalf of customers, and now the Renewal Order fails to trigger at the scheduled time each week. So they have to process a manual Renewal. I noticed on these edited Subs that the line items in the Sub are missing the **_wc_scheme: 1_week** type meta data, and assume there is something going on there. Is there any way for an Admin to add this? Or is this part of the 'switching subscriptions' functionality on the roadmap? In which case is there a workaround, other than asking the customer to recreate the Sub from scratch?

Any thoughts/suggestions greatly welcomed!

Sam

**Comment by thenbrent** [comment]
Hey Sam,

> how can they set a SATT scheme?

Subscription's are separate from a subscription product (whether it's a SATT product or built in product type in Subscriptions). That means a subscription doesn't ever have a SATT scheme. Instead, the billing schedule/interval [set on the **Edit Subscription** screen](https://docs.woocommerce.com/document/subscriptions/add-or-modify-a-subscription/#section-3) is used.

If the separation between produts with a scheme and a subscription still isn't clear, this guide provides more detail to help clarify it: https://docs.woocommerce.com/document/subscriptions/subscription-product-vs-subscription/

> now the Renewal Order fails to trigger at the scheduled time each week

This is unlikely to be related to manually editing the subscription, as long as the subscription's billing schedule it setup correctly.

Normally renewals not processing is a result of WP-Cron not running. You can install WP-Crontrol to ensure that is running, or use the Action Scheduler's admin screen.

**Comment by sambomcd** [comment]
Hi @thenbrent,

Thanks for the response - I think I have ruined this with my poor choice of terminology!

I am clear on Subscription Product vs a Product with a SATT scheme. It is the latter I am referring to above. So - for a Product that a customer has chosen to subscribe to using SATT. When a customer orders a product and chooses a SATT scheme, it creates a Subscription for them, correct? But how does an Admin either:

- Edit a Subscription created by the Customer ordering a Product with a SATT scheme, but retain that SATT scheme (i.e. customer ordered ProductA but meant to order ProductB, so contact the shop to get it changed)
- Create a new Order for a Product or Products with a SATT scheme?

Does this help explain? Or am I really missing something obvious here?

Sam

**Comment by thenbrent** [comment]
> Edit a Subscription created by the Customer ordering a Product with a SATT scheme, but retain that SATT scheme

What do you mean by "retain that SATT scheme"?

Do you mean you want the billing schedule on the subscription to be the same as the SATT scheme? If so my previous comment addresses that. That's really all a scheme is - the rules for creating the subscription's billing schedule when that product is purchased.

Do you want the meta data set on the line item added to the subscription to include the scheme meta data? If so, which scheme? Because we don't know that unless the customer chooses it. The admin can add specific meta manually themselves if needed.

> Create a new Order for a Product or Products with a SATT scheme?

There is no way to manually create an order for a subscription product (whether that's a SATT Product or Simple Subscription product) and have it automatically create a subscription. Instead, you create the subscription then create an order, see https://docs.woocommerce.com/document/subscriptions/add-or-modify-a-subscription/#section-14

**Comment by sambomcd** [comment]
Hi Brent,

Perhaps I am on the wrong track with what I am asking, or I am just asking it wrong. Let me outline exactly what the problem is I am seeing:

Customer purchases a Product, selects a subscription option for the Product as provided by SATT plugin
Customer realises they made a mistake, or need to change their order. Shop Owner (my client) goes in and makes a change. I cannot be sure what the Shop Owner has done, I am sorry. I am assuming they have manually edited the Subscription, removing and adding a Product to fix the client’s mistake.
Every week around the same time, all Subscriptions process their Renewals (we synchronise them manually to do this). 40-odd renewal orders process without fail (so it is not a WP-Cron issue). About 6 do nothing. The time passed and their ’Next payment’ starts pointing to the time in the past when the Renewal was supposed to run.
In the log I see this:

[05-Sep-2017 14:19:53 UTC] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to ActionScheduler_Action::__construct() must be of the type array, null given, called in /home/xxxxx/public_html/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php on line 123 and defined in /home/xxxxx/public_html/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/ActionScheduler_Action.php:13
Stack trace:
#0 /home/xxxxx/public_html/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php(123): ActionScheduler_Action->__construct('woocommerce_sch...', NULL, Object(ActionScheduler_SimpleSchedule), '')
#1 /home/xxxxx/public_html/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php(99): ActionSch in /home/xxxxx/public_html/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/ActionScheduler_Action.php on line 13
  
When I check a ‘good’ Subscription vs one of these that are failing, I notice that the SATT scheme meta data is missing:

Good


Failing every week


Therefore I wondered if there was something that had happened when the Shop Owner made some changes to the Subscription. Hence my original question about an Admin making changes to a Subscription.

I apologise if I was not clear from the start. I am not 100% sure this is related to SATT and didn’t want to waste anyone’s time, but I guess I did that inadvertently by asking the question in such a roundabout manner.

If you had any thoughts on this it would be much appreciated.

Sam

**Comment by willgorham** [comment]
@sambomcd Images attached via email don't show up in the GitHub issue

**Comment by sambomcd** [comment]
Thanks @willgorham - have edited my response. (Plus will never respond from email again!)

**Comment by sambomcd** [comment]
Hi Brent,

Perhaps I am on the wrong track with what I am asking, or I am just asking it wrong. Let me outline exactly what the problem is I am seeing:

- Customer purchases a Product, selects a subscription option for the Product as provided by SATT plugin
- Customer realises they made a mistake, or need to change their order. Shop Owner (my client) goes in and makes a change. I cannot be sure what the Shop Owner has done, I am sorry. I am assuming they have manually edited the Subscription, removing and adding a Product to fix the client’s mistake.
- Every week around the same time, all Subscriptions process their Renewals (we synchronise them manually to do this). 40-odd renewal orders process without fail (so it is not a WP-Cron issue). About 6 do nothing. The time passed and their ’Next payment’ starts pointing to the time in the past when the Renewal was supposed to run.
- In the log I see this:

```
[05-Sep-2017 14:19:53 UTC] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to ActionScheduler_Action::__construct() must be of the type array, null given, called in /home/xxxxx/public_html/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php on line 123 and defined in /home/xxxxx/public_html/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/ActionScheduler_Action.php:13
Stack trace:
#0 /home/xxxxx/public_html/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php(123): ActionScheduler_Action->__construct('woocommerce_sch...', NULL, Object(ActionScheduler_SimpleSchedule), '')
#1 /home/xxxxx/public_html/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php(99): ActionSch in /home/xxxxx/public_html/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/ActionScheduler_Action.php on line 13
```

When I check a ‘good’ Subscription vs one of these that are failing, I notice that the SATT scheme meta data is missing:

**Good**
<img width="264" alt="screen shot 2017-09-11 at 3 48 40 pm" src="https://user-images.githubusercontent.com/1875763/30282954-af1ec088-970e-11e7-8aba-c4c0dbeefe4f.png">

**Failing every week**
<img width="236" alt="screen shot 2017-09-11 at 3 49 01 pm" src="https://user-images.githubusercontent.com/1875763/30282963-b510b758-970e-11e7-809e-59c05d0ec32a.png">

Therefore I wondered if there was something that had happened when the Shop Owner made some changes to the Subscription. Hence my original question about an Admin making changes to a Subscription.

I apologise if I was not clear from the start. I am not 100% sure this is related to SATT and didn’t want to waste anyone’s time, but I guess I did that inadvertently by asking the question in such a roundabout manner.

If you had any thoughts on this it would be much appreciated.

Sam

**Comment by thenbrent** [comment]
@sambomcd this has nothing to do with the SATT data. I also don't think it's actually a Subscriptions issue.

Based on the error in the log, this is being caused by something incorrectly changing a scheduled actions data. Subscriptions doesn't do this (if it did, we'd have 1,000 of stores seeing the error). SATT doesn't do this. No other plugin I know of does this (but it's possible there is a plugin I don't know of), which means it's most likely a bug in custom code.

You should audit all code you have on your site that interacts with Action Scheduler, either via API functions or database queries. If you can't find anything relevant, [open a ticket a WooCommerce.com](http://woocommerce.com/my-account/create-a-ticket/) and we'll do what we can to help, but neither SATT nor debugging custom code is covered under support, so our involvement will be limited to helping point you in the right direction and perhaps doing a quick scan of your site's plugins/code for potential causes.

**Comment by sambomcd** [comment]
OK thanks Brent. I will follow your suggestions. I have not put in place any custom code that interacts with Action Scheduler, so it must be a plugin then. I apologise I was on the wrong track referring it here.

Sam
