### ISSUE TITLE
Radio Buttons NOT Clickable...

### ISSUE THREAD

**Issue by stephendanielkarpik** [Prospress/woocommerce-subscribe-all-the-things#207]
https://www.useloom.com/share/6a9ffe266f5a489c8ecd8446914f896c

Version 2.0.1-dev installed with WC 3.1.2

`
### WordPress Environment ###

WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31-4+wpengine10
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 3000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.37
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (35) ###

ActiveCampaign: by ActiveCampaign – 6.2.12
AffiliateWP - PayPal Payouts: by Pippin Williamson and Andrew Munro – 1.1.7
AffiliateWP: by AffiliateWP
LLC – 2.1.4.1

AffiliateWP - Custom Affiliate Slugs: by Pippin Williamson and Andrew Munro – 1.0.1
AutomateWoo: by AutomateWoo – 3.2.5
Autoptimize: by Frank Goossens (futtta) – 2.2.2
Contact Form DB: by Michael Simpson – 2.8.8
Contact Form 7: by Takayuki Miyoshi – 4.9
WooCommerce Single Product Page Builder: by SiteSao Team – 3.0.6
Envato WordPress Toolkit: by Envato – 1.7.3
Google Analytics Dashboard for WP (GADWP): by Alin Marcu – 5.1.1.1
JP Sharing: by JP – 3.9.6
Local Geo Search: by Elite Impressions
LLC – 1.2.1

NS Redirection and GA Campaign Link Builder: by Never Settle – 1.0.0.2
Pixel Caffeine: by AdEspresso – 1.2.3
Plugin Notes: by Mohammad Jangda – 1.6
Redirection: by John Godley – 2.7.3
Replace Image: by Potent Plugins – 1.1.6
Slider Revolution: by ThemePunch – 5.4.5.1
Simple Sitemap: by David Gwyer – 2.1
Uncode Core: by Undsgn – 1.4.1
Uncode Visual Composer: by Michael M - WPBakery.com – 5.2
Visual Composer Clipboard: by bitorbit – 3.24
WooCommerce Dynamic Pricing & Discounts: by RightPress – 1.1
Advanced Order Export For WooCommerce: by AlgolPlus – 1.4.5
WooCommerce Amazon Fulfillment: by Never Settle – 3.0.7
WooCommerce Stripe Gateway: by WooCommerce – 3.2.3
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3
Booster for WooCommerce: by Algoritmika Ltd – 3.0.1
WooCommerce ShippingEasy Integration: by  – 3.3.0 – 4.0.0 is available
WooCommerce Subscribe All the Things: by Prospress Inc. – 2.0.1-dev
WooCommerce Subscriptions: by Prospress Inc. – 2.2.11
WooCommerce Table Rate Shipping: by Erica Dion – 3.3.8
WooCommerce: by Automattic – 3.1.2
Yoast SEO: by Team Yoast – 5.4

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page not set
Cart: #607 - /cart/
Checkout: #608 - /checkout/
My account: #609 - /my-account/

### Theme ###

Name: Uncode Child
Version: 1.0.0
Author URL: http://www.undsgn.com
Child Theme: ✔
Parent Theme Name: Uncode
Parent Theme Version: 1.6.1
Parent Theme Author URL: http://www.undsgn.com
WooCommerce Support: ✔

### Templates ###

Overrides: uncode/woocommerce/archive-product.php
uncode/woocommerce/cart/mini-cart.php
uncode/woocommerce/content-product.php
uncode/woocommerce/content-product_cat.php
uncode/woocommerce/content-single-product.php
uncode/woocommerce/loop/loop-end.php
uncode/woocommerce/loop/loop-start.php
uncode/woocommerce/loop/pagination.php
uncode/woocommerce/myaccount/my-account.php
uncode/woocommerce/myaccount/navigation.php
uncode/woocommerce/notices/error.php
uncode/woocommerce/notices/notice.php
uncode/woocommerce/notices/success.php
uncode/woocommerce/order/order-details-customer.php
uncode/woocommerce/order/order-details.php
uncode/woocommerce/product-searchform.php
uncode/woocommerce/single-product/add-to-cart/external.php
uncode/woocommerce/single-product/add-to-cart/grouped.php
uncode/woocommerce/single-product/add-to-cart/simple.php
uncode/woocommerce/single-product/add-to-cart/variable.php
uncode/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
uncode/woocommerce/single-product/meta.php
uncode/woocommerce/single-product/price.php
uncode/woocommerce/single-product/product-image.php
uncode/woocommerce/single-product/product-thumbnails.php
uncode/woocommerce/single-product/related.php
uncode/woocommerce/single-product/review.php
uncode/woocommerce/single-product/share.php
uncode/woocommerce/single-product/tabs/additional-information.php
uncode/woocommerce/single-product/tabs/description.php
uncode/woocommerce/single-product/tabs/tabs.php
uncode/woocommerce/single-product/title.php
uncode/woocommerce/single-product/up-sells.php
uncode/woocommerce/single-product-reviews.php
uncode/woocommerce/single-product.php
uncode/woocommerce/taxonomy-product_cat.php

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ❌ Staging
`

**Comment by seb86** [comment]
@stephendanielkarpik This looks more of a theme issue. If this is a stage/development site, can you change the theme to Twenty Sixteen or Twenty Seventeen and take a look at the checkout page again and then let us know if you are still unable to select the radio buttons. Thank you.

**Comment by franticpsyx** [comment]
Definitely a theme issue. Closing but feel free to provide more details, @stephendanielkarpik :)
