### ISSUE TITLE
Compatibility with WPML

### ISSUE THREAD

**Issue by marieptremblay** [Prospress/woocommerce-subscribe-all-the-things#208]
Hi,

I would like to suggest a feature, which is to add WPML compatibility. The website I work on has products generated with WPML and the translated products don't have the metadata created by this extension in the original language product. 
Basically, this plugin only works in the native language of the website but doesn't work once you switch languages.
For the website I work on, I made a compatibility fix which is the following : 
If the metadatas are missing from the product, I will go fetch the original product id from the translated product. I will then instance a WC_Product of the original product and collect the metadata from this product. 

For instance, I will use this fix to collect the subscription schemes of my translated products, both on the product page and in the cart.

If you are interested, I can post the code I used for my fix. Though, I only use variable products so I've only make the fix for this part of the extension.

**Comment by franticpsyx** [comment]
@marieptremblay WPML compatibility for WooCommerce extensions/plugins is maintained by the WPML team in [WooCommerce Multilingual](https://wordpress.org/plugins/woocommerce-multilingual/).

We are happy to provide technical assistance to them if they want to support SATT, but beyond that there's not much we can do on our side.
