### ISSUE TITLE
All subscriptions going through as manual renewal and not automatic ?!?

### ISSUE THREAD

**Issue by chsajid09** [Prospress/woocommerce-subscribe-all-the-things#209]
I have this plugin installed, all the subscriptions are going on manual renewal not automatic.

can you please advise asap. 

thanks.

**Comment by willgorham** [comment]
I don't think SATT has anything to do with whether the subscription is manual/automatic. Sounds like a gateway configuration problem most likely. A system status report would probably be helpful here.

https://docs.woocommerce.com/document/subscriptions/renewal-process/

**Comment by chsajid09** [comment]
Where can i find the system report?

**Comment by willgorham** [comment]
WooCommerce > Status > Get System Report

**Comment by chsajid09** [comment]
`
### WordPress Environment ###

Home URL: 
Site URL: 
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.23
PHP Post Max Size: 8 MB
PHP Time Limit: 90
PHP Max Input Vars: 5000
cURL Version: 7.55.1
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.37
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (19) ###

Gravity Perks: by Gravity Wiz – 1.2.18.6
Gravity Forms: by rocketgenius – 2.1.3.4
Custom Reporting Pro: by Stuart Elliot – 0.1
ClickToAddress Auto-Complete Integration: by Crafty Clicks – 1.1.1
Gift Aid for WooCommerce: by Dave Green  – 1.3.3
GP eCommerce Fields: by Gravity Wiz – 1.0.beta1.7
Gravity Forms Reset Button Add-On: by Able Engine & William Wilkerson – 1.0
GP Reload Form: by David Smith – 1.1.12
Advanced Order Export For WooCommerce: by AlgolPlus – 1.4.2
Woo Orders Date Range Filter: by Thewpexperts – 1.0.0
Bolder Fees for WooCommerce: by Bolder Elements – 1.4.15
WooCommerce Cart Tab: by jameskoster – 1.1.1
WooCommerce Checkout Field Editor: by WooThemes – 1.4.10 – 1.5.6 is available
WooCommerce Stripe Gateway: by WooCommerce – 3.2.1
WooCommerce WorldPay Gateway: by Add On Enterprises (Andrew Benbow) – 3.6.0 – 3.6.1 is available
WooCommerce - Gravity Forms Product Add-Ons: by Lucas Stark – 3.1.10 – 3.1.11 is available
WooCommerce Subscribe All the Things: by Prospress Inc. – 1.1.2
WooCommerce Subscriptions: by Prospress Inc. – 2.2.4
WooCommerce: by WooThemes – 2.6.14

### Settings ###

Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: ❌ Page ID is set
but the page does not exist

Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)


### Theme ###

Name: Storefront
Version: 2.2.3 – 2.2.5 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ❌ Staging
`

**Comment by willgorham** [comment]
Subscriptions is in staging mode: https://docs.woocommerce.com/document/subscriptions-handles-staging-sites/

**Comment by thenbrent** [comment]
Closing this one now. @willgorham did a great job diagnosing it. Please have a read over the document he sent through for ways to switch to live mode if required. 🙂

**Comment by chsajid09** [comment]
Thanks guys thats sorted it! :)

**Comment by ccolonello** [comment]
Hi guys, I have the same problem if I chek I have Subscriptions Mode: ❌ Staging . How can I change in live mode? Thanks

**Comment by thenbrent** [comment]
Hi @ccolonello please follow the guide here: https://docs.woocommerce.com/document/subscriptions-handles-staging-sites/#section-4
