### ISSUE TITLE
WC 3.1.2 and SATT 2.0 choked

### ISSUE THREAD

**Issue by jessejones2** [Prospress/woocommerce-subscribe-all-the-things#210]
I was leaving my site on WC 2.6.13 because SATT 1.1.2 did not work with WC 3.
I just "accidentally" upgraded to WC 3.1.2 and thought I would try the new SATT 2.0 before I went back to WC 2.6.13 and SATT 1.1.2.
However, going to WC 3.1.2 with SATT 2.00 did not work. The whole thing choked and there was not even the "subscription" option in my product pages.
Got any ideas?

**Comment by franticpsyx** [comment]
@jessejones2 

There are no general issues/incompatibilities with SATT 2.0 and WC 3.0+. Did you upgrade WCS to 2.1+?

It sounds like you might be up against:

* an issue with custom code; or
* a conflict with another plugin.

I would suggest disabling all custom code/snippets + other plugins except for WooCommerce, WCS and SATT and checking again. If this fixes the issue, then slowly re-enable plugins until you find the one causing the problem.
