### ISSUE TITLE
Woocommerce Renewal Synchronization not supported

### ISSUE THREAD

**Issue by tntc1978** [Prospress/woocommerce-subscribe-all-the-things#211]
So I'm working on a site.
I'm using _subscriptions_ and _Mix and Match Products_ and also using _WooCommerce Subscribe All the Things_, these three extensions are used to show the opportunity to select from different products.

Now to the issue. When enabling the Renewal Synchronization
https://docs.woocommerce.com/document/subscriptions/renewal-synchronisation/ then I don't get the opportunity to select that the subscription needs to start the 1st of the month. I gather that that should be possible for the mix and match product type.

I asked the Woocommerce support, and they asked me to post the issue here.

**Comment by thenbrent** [comment]
>  I don't get the opportunity to select that the subscription needs to start the 1st of the month

Hi @tntc1978, that functionality is not supported yet. Along with a few other features. You can learn more about what's still to do on the Roadmap here: https://github.com/Prospress/woocommerce-subscribe-all-the-things/wiki/Roadmap#short-term

I can't provide an ETA on when that functionality will be available unfortunately.
