### ISSUE TITLE
Subscription Switching Not Allowed

### ISSUE THREAD

**Issue by umang-metatagg** [Prospress/woocommerce-subscribe-all-the-things#212]
Hello Team,

It is possible switch subscription with this plugin? Currently woocommerce subscription support switching of subscription. I would like following things customer can make editable:
1. add and delete items (products)
2. change frequency
3. change quantity

**Comment by thenbrent** [comment]
Hi @umang-metatagg switching is not supported yet. It is on the [Roadmap for WCS Features Parity Milestone 3 and 4](https://github.com/Prospress/woocommerce-subscribe-all-the-things/wiki/Roadmap#medium-term) so it is still quite a long way off being developed too.

**Comment by umang-metatagg** [comment]
How much time it take to develop? Our Team is interested for this feature with custom work. Thanks!

**Comment by seb86** [comment]
@umang-metatagg Get in touch with me directly and we can talk.
