### ISSUE TITLE
Price override per variation?

### ISSUE THREAD

**Issue by ash-f** [Prospress/woocommerce-subscribe-all-the-things#214]
Is this planned in near future release?

**Comment by franticpsyx** [comment]
@ash-f 

As part of our medium/long term plan to reach features parity between SATT and WCS, we'd like to make it possible to define/pick/exclude specific schemes at variation level, but at this point we haven't done any work on this so I can't provide any more details.

Initially I hoped that scheme data should only exist at parent level, but in the end we will probably need to allow individual variations to have their own new schemes, overriding the schemes of their parent.

Closing for now as this is part of the [Roadmap](https://github.com/Prospress/woocommerce-subscribe-all-the-things/wiki/Roadmap).

**Comment by ash-f** [comment]
Understand. Thank you!

**Comment by seb86** [comment]
@ash-f I actually did this feature for the first version of SATT for a client. It will require updating to work with SATT 2.0

If you are interested in hiring me to have this done for you please [get in touch](https://sebastiendumont.com/contact/).
