### ISSUE TITLE
Subscription option does not appear on "variable" products

### ISSUE THREAD

**Issue by dberz** [Prospress/woocommerce-subscribe-all-the-things#216]
Here's a Woocommerce "variable product" where the the subscription controls are missing, even though they are configured to display: https://staging-www.parsleyhealth.com/store/rebuild-protein-shake/

WooCommerce admin configurations pasted below.

![screen shot 2017-10-16 at 12 18 56 pm](https://user-images.githubusercontent.com/5471790/31623228-cb71c766-b26c-11e7-8302-c78fd7e0d868.png)

![screen shot 2017-10-16 at 12 19 23 pm](https://user-images.githubusercontent.com/5471790/31623231-cd3651f2-b26c-11e7-9f70-1f88210aa169.png)

//

Here's an example of a "simple product", where the subscription controls do correctly show: https://staging-www.parsleyhealth.com/store/rebuild-protein-shake-copy/

// 

Any suggestions would be welcome!

**Comment by seb86** [comment]
@dberz It's not supported at this time. [See roadmap](https://github.com/Prospress/woocommerce-subscribe-all-the-things/wiki/Roadmap) for more information.

However, if you would like to hire me to support variable products please let me know.

**Comment by willgorham** [comment]
My impression was that variable products were supported. Just not differing subscription settings at the variation level. Am I wrong? They are working on my store, at least it sure seems like they are...

**Comment by willgorham** [comment]
@dberz 

I have them working fine.
Front end: https://cl.ly/0x2N0N2P2u0Y
Admin: https://cl.ly/2U2s0O0Q4715
https://cl.ly/0P2W1T1N1D3E

Any PHP notices? JS errors? Customizations that you're trying to implement?

**Comment by seb86** [comment]
@willgorham He is wanting subscription schemes on the variation level if I understood correctly. @dberz please confirm.

**Comment by dberz** [comment]
Thanks @willgorham and @seb86 -
