### ISSUE TITLE
Subscription prompt has mixed signals

### ISSUE THREAD

**Issue by seb86** [Prospress/woocommerce-subscribe-all-the-things#217]
First, if the subscription prompt is used to change the text it is placed in a paragraph `<p>` instead of still using header 3 `<h3>`.

Second, the subscription prompt only appears to be working on simple products, not variable products. I dont know if other product types are also experiencing this problem.

I think the default prompt in [the template](https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/templates/single-product/product-subscription-options.php#L25) should be in a paragraph to match but so far I have used it for clients who prefer it with header 3 `<h3>` and want to simply change the text and not use it for anything else.

I am using the master branch. Any thoughts @franticpsyx, @thenbrent?

**Comment by franticpsyx** [comment]
@seb86 -- There was a glitch reported in https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/198 which should be patched in master.

Happy to look into again -- at the moment I'm still airplane-hopping but will be returning to SATT in the next few days.

Regarding the template / markup, I think the intention was that store owners should be able to use the markup they want, including `h3` tags. When nothing is defined there, the default message gets wrapped in `h3`.

**Comment by seb86** [comment]
@franticpsyx I was using the latest master of SATT so the bug may have come back. Maybe a change in the core of WooCommerce for variables might be the cause. I cant say for sure. If you find it is working with everything up to date then I will check if there is something else causing it.

**Comment by franticpsyx** [comment]
Can't find any issue here: https://cl.ly/3u2v0W1d0j27

> Regarding the template / markup, I think the intention was that store owners should be able to use the markup they want, including `h3` tags. 

When the Prompt content is empty, the default message gets wrapped in `h3`. Placing that logic in the template (instead of placing an `h3` tag in the text string) is arguably the cleanest way to do it.
