### ISSUE TITLE
Issue with Sync'ed Subscriptions

### ISSUE THREAD

**Issue by stickypages** [Prospress/woocommerce-subscribe-all-the-things#219]
Hello!

Just curious here, I believe I have found a bug. When you have a subscription with a 'synced date'. I have a subscription with a Sync date of the 20th. So no one should be charged upon completion of checkout. and then charged when the sync date arrives. 

Here is a screenshot of the checkout: 
![2017-10-20 15_24_36-checkout](https://user-images.githubusercontent.com/658488/31844008-092c053a-b5ab-11e7-9196-0bcb1441dd0f.png)

This is my Woo Settings:
![2017-10-20 15_26_32-woocommerce settings township 7 wine wordpress](https://user-images.githubusercontent.com/658488/31844021-1b43eddc-b5ab-11e7-85d6-d556f48fecef.png)

**I have attempted,** 
- removing all plugins except for WooCommerce + Subscriptions. Same response. 
- removed all code in the functions file, same response
- created a new simple subscription product, same response

Can anyone duplicate this issue?

**Comment by willgorham** [comment]
Hey @stickypages, WCSATT isn't compatible with synchronized subscriptions yet. You can check out the roadmap for more info: https://github.com/Prospress/woocommerce-subscribe-all-the-things/wiki/Roadmap

**Comment by stickypages** [comment]
Ohh ok, think I was confused between this and just regular Woo Subscriptions.
