### ISSUE TITLE
Change Discount Based on Quantity?

### ISSUE THREAD

**Issue by Deftwun** [Prospress/woocommerce-subscribe-all-the-things#220]
How difficult would it be to change the discount based on the number of items added to cart? 

So if I choose to subscribe & receive one item per month I get a 5% discount. 
If I choose to subscribe to 2 items per month I get a 10% discount.
If I choose to subscribe to 3 items per month I get a 15% discount. 
etc..

**Comment by franticpsyx** [comment]
> How difficult would it be to change [...]

For someone familiar with SATT it might not be very tough, but in any case you are looking at customization territory :) Unfortunately we cannot provide assistance with customizations: Please remember this is a bug tracker. 

For details, see https://github.com/Prospress/woocommerce-subscribe-all-the-things#support
