### ISSUE TITLE
Customizing the radio button text

### ISSUE THREAD

**Issue by dimijazz** [Prospress/woocommerce-subscribe-all-the-things#226]
How can I add the regular price next to the one time button text? 
Also I would need to customize  the class="price subscription-price". Now it is displaying  ($27.00 $24.30 / month) need to make it ( Subscribe and save 10% $ 24.30). 
What I try to do is make it look exactly like this website: https://www.rxbar.com/shop/blueberry-box-of-12-bars.html
Any help would be really appreciated.
Thank you

**Comment by franticpsyx** [comment]
Hey @dimijazz -- unfortunately we can't provide much help with customizations as this issue tracker is only for reporting bugs: https://github.com/Prospress/woocommerce-subscribe-all-the-things#support

Thanks for understanding!
