### ISSUE TITLE
Idea: Options in the product loop

### ISSUE THREAD

**Issue by seb86** [Prospress/woocommerce-subscribe-all-the-things#229]
Just an idea but what do you think of adding the scheme options in the product loop?

This shop called [RXBAR](https://www.rxbar.com/shop.html) have done it. 

What do you think @thenbrent and @franticpsyx?

![Product Loop Example](https://cldup.com/JDr79vr02C.png)

**Comment by thenbrent** [comment]
@seb86 my concern with doing that are how it appears when you have more than one option. e.g. if you have 5 or 10, or some products with 1, some with 3, some with 10, everything is going to fall out-of-alignment if the site is using a grid layout for products (which many do).

The way RXBAR has done it is quite cool. Only show it on hover. But that IMO is beyond the scope of SATT and falls into theme territory.

**Comment by willgorham** [comment]
I do like that the schemes are all inside a select input, displayed after clicking on the radio button. It seems like nicer UX, and keeps things cleaner than having a huge list if you have lots of available schemes. This applies currently to the product/cart pages (maybe that's worth a different issue), but is relevant too if you wanted to implement something like this on archives / in the loop.

**Comment by franticpsyx** [comment]
Generally speaking radios are good for up to 3-4 options, then anything more is probably going to work better in a select. I remember chatting about this with @thenbrent before releasing v1 -- then, we decided to go with radio-buttons and let everything else be handled via the templates. Still feel the same about this.

@seb86 that looks great. We _know_ this is useful and it has been requested again in the past. However I see this as the equivalent of requesting to have variable-product attribute drop-downs in shop archives -- which I think falls into theming territory. In some cases, it will look and function great. In most it will not.

I'd rather just follow the paradigm set by WooCommerce core here which dictates that shop archives and product loops contain nothing but a button -- and leave this to theme developers.

Eventually, we can circle back to this and re-evalute if we get more requests in the future.
