### ISSUE TITLE
One time shipping fee option is not working

### ISSUE THREAD

**Issue by Key7i** [Prospress/woocommerce-subscribe-all-the-things#231]
Hello,

I setup subscription for a variable product and choose one time shipping fee but its not working. On checkout page, its showing same flat rate for Recurring total. And recurring amount is same as initial payment including shipping fee.

There is no free trial. Also Synchronize renewals option is disabled in subscription settings. http://prntscr.com/hdxhkp/direct

Help please.

Thanks

**Comment by franticpsyx** [comment]
Hey @Key7i 

Thanks for reaching out :)

I'm afraid I can't replicate this one, though. Here's what I see when "One time shipping" is enabled:

Initial order -- https://cl.ly/3y272Y2O2A0g
Renewal order -- https://cl.ly/193P1A201I3Y

...and when "One time shipping" is disabled:

Renewal order -- https://cl.ly/3Z3D1w3C1u3p

This looks fine to me. Have you perhaps installed any third-party Subscriptions / Subscribe All The Things plugins?

**Comment by franticpsyx** [comment]
Maybe related: https://github.com/Prospress/woocommerce-subscriptions/issues/2434

Closing here.
