### ISSUE TITLE
Customization options?

### ISSUE THREAD

**Issue by RedtailScream** [Prospress/woocommerce-subscribe-all-the-things#242]
Is there a way to remove the wording: "Subscription plans available starting at...." from the Price line of the WooCommerce product? Thanks!!

**Comment by franticpsyx** [comment]
Hey @RedtailScream -- unfortunately we can't provide much help with customizations as this issue tracker is only for reporting bugs: https://github.com/Prospress/woocommerce-subscribe-all-the-things#support

Thanks for understanding!
