### ISSUE TITLE
Emails being sent out multiple times

### ISSUE THREAD

**Issue by ImportantlyMe** [Prospress/woocommerce-subscribe-all-the-things#244]
Hi there

We've a situation where multiple emails are being sent out when an Order is produced from a subscription - sometimes in 000's (highest was 2,500+)

See https://cl.ly/odDk

We're using

WooCommerce Subscriptions Version 2.2.16
WooCommerce Subscribe All the Things Version 2.0.0-alpha 

All other plugins and WP are up-to-date
Server is running on PHP7

We've switched to wpMandrill today instead of the standard WP php.mailer and I've added a daily subscription to see if it happens tomorrow...

If you've any ideas / knowledge, please let me know. Appreciate your help (I'm not a developer)

Thanks :-)

John

**Comment by ImportantlyMe** [comment]
Hi 

An update

On first renewal, two emails were created

On second day - today 6th, there were 000's again

https://cl.ly/ogEK

Cheers

John

**Comment by thenbrent** [comment]
Hi John, I'd try disabling all other plugins (especially those relating to orders, emails) and custom code. This looks a lot like an infinite loop. There's no known issues like that in Subscriptions or Subscribe all the Things, meaning it's most likely coming from a plugin conflict or elsewhere.

**Comment by ImportantlyMe** [comment]
Thanks Brent :-)

It looks like a plugin called Smart Manager....

Anyway, FYI, we are using this in a live environment, and customers (and my client) love it!

We've got a lot of additional plugins too, so if you want to have a look at how it's working with the Flatsome Theme, here it is https://www.aqua-amore.com 

Cheers

John

**Comment by franticpsyx** [comment]
> Anyway, FYI, we are using this in a live environment, and customers (and my client) love it!

Thanks John! Nothing wrong with that if you have a developer on call :) The only reason we can't recommend installing SATT on a live site is that there's no dedicated/premium support channel for it. Otherwise the codebase should be as bug free as any solid piece of WP software out there.
