### ISSUE TITLE
Cart Subscription Discounts | Not working

### ISSUE THREAD

**Issue by alexghattas** [Prospress/woocommerce-subscribe-all-the-things#245]
First off, thank you very much for this free plugin, has saved me a ton of time!

I am running into one issue, and wondering if your team currently has a fix for it, or if you are aware of it. On an individual mix-and-match product, I am trying to apply a discount when the user selects a subscription, but the discount is not being applied.

Any feedback would be greatly appreciated, or even a starting point where I could start debugging this issue :)

Thanks again!!

![image](https://user-images.githubusercontent.com/13427918/34655288-170c26cc-f3d5-11e7-8289-b9b7668b96e7.png)

**Comment by franticpsyx** [comment]
@jimjasson want to take a look? Can you replicate? Ping me if you need MnM repo access.

**Comment by jimjasson** [comment]
@alexghattas When the 'Per-Item Pricing' option is disabled, the discount seems to be applied correctly: https://cl.ly/3V3s023A3s0q . However, when it is enabled, it looks like the subscription option for the Mix & Match product is not offered at all. 

As mentioned in this issue (https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/202), this is intended behavior since per-item priced MnM products are unsupported due to some missing infrastructure in MnM.

@franticpsyx Can you confirm this?

**Comment by franticpsyx** [comment]
@jimjasson Yup, when *Per-Item Pricing* is enabled you shouldn't be seeing any subscription schemes.

@alexghattas how's that mix-and-match product configured?

**Comment by alexghattas** [comment]
@jimjasson and @franticpsyx really appreciate the time you are taking to look into this.

See image below for mix-and-match configuration. Let me know anything else I can provide.

![image](https://user-images.githubusercontent.com/13427918/34731294-f0c30916-f52f-11e7-8abd-9db84fcd81a5.png)

**Comment by seb86** [comment]
I think additional JavaScript will be needed to apply the discount after calculating the added items to the container when the subscription scheme is selected using this trigger `wc-mnm-price-updated`.

May also need to add Javascript to detect if the customer has changed subscription scheme on the single product page or switched back to one-time order.

Just my thoughts on this conversation. Hope it helps.

**Comment by franticpsyx** [comment]
@alexghattas You shouldn't be seeing any subscription options when **Per-Item Pricing** is enabled.

Assuming you are using the latest versions of WC, MnM, SATT and WCS, of course.

From #202 -- 

> Per-item priced MnM products are unsupported due to some missing infrastructure in MnM. As a workaround, you could use Product Bundles in combination with the [Min/Max Items](https://docs.woocommerce.com/document/bundles/bundles-mini-extensions/#section-2) mini-extension (free), which does pretty much the same thing as MnM.
 
@seb adding that infrastructure to MnM would require a significant investment of time. There are many pieces in the puzzle that are currently missing. In any case, this is not something we can fix in SATT.
