### ISSUE TITLE
I try to exclude subscription products to a coupon

### ISSUE THREAD

**Issue by bstrokevin** [Prospress/woocommerce-subscribe-all-the-things#248]
But the Coupon still applys and the discount calculation seems odd. How do I disable any coupon for subscriptions

**Comment by franticpsyx** [comment]
@bstrokevin thanks for getting in touch!

This sounds like a general issue/question and not something limited to Subscribe All the Things, so I would encourage you to ask for assistance by opening a new ticket via your WooCommerce.com account dashboard at http://woocommerce.com/my-account/marketplace-ticket-form/

Thanks!

**Comment by bstrokevin** [comment]
Hi. Thanks just saw this reply. I’ll try ask in the forum now. Thanks.
