### ISSUE TITLE
Add subscription to cart via ?add-to-cart in the URL

### ISSUE THREAD

**Issue by jakeperrin** [Prospress/woocommerce-subscribe-all-the-things#254]
Just wondered if this was possible since its a single product and not a subscription or variable subscription product?

**Comment by franticpsyx** [comment]
Hey @jakeperrin 

That _should_ have been possible -- by passing the subscription scheme key along with the `convert_to_sub_{product_id}` parameter.

Example: `?add-to-cart=52&convert_to_sub_52=1_month_5`. 

However this doesn't work at the moment -- SATT handles data in `POST` requests only. Definitely something we can fix. Adding to the 2.1 release milestone.

**Comment by franticpsyx** [comment]
Closed via https://github.com/Prospress/woocommerce-subscribe-all-the-things/commit/e042b6fa381c223c74434c321aeb2821a2dd5cbf
