### ISSUE TITLE
I can't seems to find a want to exclude subscription to coupons

### ISSUE THREAD

**Issue by bstrokevin** [Prospress/woocommerce-subscribe-all-the-things#255]
I want to make sure coupons can't be applied to subscriptions. Is there a way to do that?

**Comment by franticpsyx** [comment]
As mentioned in #248 we can't help with general WooCommerce or WooCommerce Subscriptions questions. **This repository is only for reporting SATT bugs only**. 

For assistance with WooCommerce or WooCommerce Subscriptions, please open a ticket via your WooCommerce.com account dashboard at http://woocommerce.com/my-account/marketplace-ticket-form/ . Thanks!
