### ISSUE TITLE
Not working with simple/variable products.

### ISSUE THREAD

**Issue by WebDesigner1234** [Prospress/woocommerce-subscribe-all-the-things#256]
![bug](https://user-images.githubusercontent.com/35849109/35457285-9bf4b178-0295-11e8-9e4b-e31bf080b70f.jpg)
![simple](https://user-images.githubusercontent.com/35849109/35458167-8f6f7426-0298-11e8-993b-dfb113ddd2e9.jpg)

Didn't know if this was a known issue. 

1. There is no checkbox or bullet option to subscribe on a variable product page or simple product page. Currently set to every month.
2. It does not calculate/display the correct discount ie 10% on the product page. It displays original price with a slash. Does not calculate/display discount properly when set to override all variations.
3. When in shopping cart it displays discount in the price column but does not calculate discount on the total price next to checkout button.
4. Does not calculate or display discount on checkout page. 

Wordpress 4.9.2 latest Woocommerce. Subscriptions 2.2.8

**Comment by franticpsyx** [comment]
Hey @WebDesigner1234

Looks like a theme/plugin conflict. Closing as I can't replicate. Please:

* Temporarily switch back to a default WordPress theme (or Storefront). If this resolves the issue, then please bring this to the attention of your theme author.
* If the issue persists, then disable all other plugins except for WooCommerce, WooCommerce Subscriptions and Subscribe All the Things. If this fixes the issue, then slowly re-enable plugins until you find the one triggering it.

Thanks!
