### ISSUE TITLE
Addons doesn't apply to subscriptions

### ISSUE THREAD

**Issue by jraviz** [Prospress/woocommerce-subscribe-all-the-things#27]
@franticpsyx Hello Sir! I would like to ask if there's any way that the add-ons will be applied if I choose the subscription? Because for now it applies to One-time Purchases only. My idea is that the optional addons will be applied on the initial payment only.

**Comment by franticpsyx** [comment]
@jraviz We need to stick with the default WooCommerce Subscriptions way here (can't change it from the SATT side), which (I think) is to include Add-ons in the recurring price. @thenbrent is that accurate?

**Comment by thenbrent** [comment]
> (I think) is to include Add-ons costs in the recurring price. @thenbrent is this accurate?

Assuming you mean this [Product Add-ons](https://www.woothemes.com/products/product-add-ons/) extension, yep, that's right, based on my vague memory of last time I looked at it and this line of [the docs](https://docs.woothemes.com/document/product-add-ons/):

> This extension also works with the WooCommerce Subscriptions plugin to add additional pricing with your options to the recurring subscription.

😄
