### ISSUE TITLE
Changing the text within the labels

### ISSUE THREAD

**Issue by jksh23686** [Prospress/woocommerce-subscribe-all-the-things#273]
First off love the plug-in it saved my butt with a client and not having to reorganize their store and SKUs!  This isn't so much of a bug as help with understanding where to change a few things being that its an add on to a plug-in.

Basically I need to change the output for the variations on subscriptions:
1. Need to change to the text from NONE to One Time Purchase then the price. 
2. For each subscription I need to change the text to say: Subscribe & save [X%]; {Sub_price}

Any help in this would be awesome. I found some functions for the price_string but it seemed to do nothing.

```
function wc_subscriptions_custom_price_string( $pricestring ) {
    $newprice = str_replace( 'every 3 months', 'per season', $pricestring );
    return $newprice;
}
add_filter( 'woocommerce_subscriptions_product_price_string', 'wc_subscriptions_custom_price_string' );
add_filter( 'woocommerce_subscription_price_string', 'wc_subscriptions_custom_price_string' );
```

Any help would be appreciated.

**Comment by franticpsyx** [comment]
Hey @jksh23686 thanks for the kind words!

I believe [this](https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/display/class-wcs-att-display-product.php#L92) and [this](https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/display/class-wcs-att-display-product.php#L111) are the filters you need to look at!

It looks like you'll be able to handle the rest 🥇

**Comment by jksh23686** [comment]
Yep thats what I needed! Thank you very much.

**Comment by premiumlion** [comment]
How would one accomplish this? (along with the Tooltip)

Any help would be greatly appreciated

![image](https://user-images.githubusercontent.com/45533027/50345136-8ff0d580-04f3-11e9-8a9c-74a33a4d61d5.png)
