### ISSUE TITLE
PHP issue

### ISSUE THREAD

**Issue by spouellet** [Prospress/woocommerce-subscribe-all-the-things#282]
What can be this error?

[15-Mar-2018 14:08:36 UTC] PHP Fatal error: Call to a member function get_meta() on boolean in /home/olabam5/public_html/wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/class-wcs-att-product.php on line 156

I see that some orders are paid in paypal and Stripe... but are ON HOLD in Subscriptions and the order are awaiting payment. But the payment has been done. Looks like an IPN issue.

Can it be related to Subscribe all the things plugin?
Thanks

**Comment by cesar-prospress** [comment]
@spouellet Do you have the complete backtrace by any chance? It seems a product is not being loaded correctly (and `false` is returned instead).

**Comment by spouellet** [comment]
Where can I find the complete backtrace?

**Comment by franticpsyx** [comment]
@spouellet It should be logged along with this error. Here's an example: https://cl.ly/2d2o2O2d2O0A

**Comment by franticpsyx** [comment]
Closing as the thread has been inactive for over a month :)

**Comment by AndreasVikke** [comment]
Hey @franticpsyx  and @cesar-prospress , i see this thread is closed, but i just ran into the same problem as @spouellet .... 

I get this in the subscription view, and only on this single one:
https://i.imgur.com/N29NBqV.png 

Hope there's help to be found here :)

**Comment by franticpsyx** [comment]
@AndreasVikke thanks for sharing that stack trace!

I have pushed a fix that should resolve this -- could you please download the latest version from `master` and give it a spin?

**Comment by AndreasVikke** [comment]
@franticpsyx  Many thanks! It works great now!
