### ISSUE TITLE
Modify shipping cost of Cart Subscriptions ?

### ISSUE THREAD

**Issue by neoseeyou** [Prospress/woocommerce-subscribe-all-the-things#283]
Hello 

First of all thank you for creating this plugin, it's unique and very usefull.

I have a question regarding the shipping cost

In my scenario, customer can start a subscription by buying a specific product (user role switch to another one call premium) and grant him free shipping for all his next orders (like amazon premium) . If customer stop his subscription, his user role come back to "simple customer" and shipping cost must be paid again for all his next orders.

What if the premium customer start a cart subscription and then choose to stop his premium subscription? Is the shipping cost will still remain free for his next recurring orders? or does the shipping cost will change according to his user role?

Sorry for poor my english as it's not my native language 

Thanks

**Comment by franticpsyx** [comment]
@neoseeyou shipping costs are calculated when the initial subscription order is placed. They are not re-calculated with every renewal+fulfillment, which means that you will need to modify them manually, or figure out a way to automate this process (most likely by working with a developer).

Closing as this is a general Subscriptions question and not an issue or feature request that's related with SATT.

**Comment by neoseeyou** [comment]
Sorry to open a thread as an issue but it's not you're right

Thank you for your confirmation about this case. I will have to hire a freelance.

Cheers
