### ISSUE TITLE
Conflict with WooCommerce Extra Product Options Pro

### ISSUE THREAD

**Issue by bethannon** [Prospress/woocommerce-subscribe-all-the-things#284]
Looks like there is a conflict with WooCommerce Extra Product Options Pro so that on the product page, it only shows each subscription option as "subscription plans available": https://prnt.sc/isamtm

This does NOT happen on the cart page, which correctly shows the options: https://prnt.sc/isangf.

Happy to help with testing or further troubleshooting.

**Comment by bethannon** [comment]
Should have also said that I am happy to provide WooCommerce Extra Product Options Pro for testing purposes.

And, here is a link to a product having this issue: https://ezfitmeals.com/product/grilled-fish-tilapia/

I'm no coder, but to help with troubleshooting, here is a browser inspector comparison of the code of a product affected by this issue, with one that is not affected.

![affected-product](https://user-images.githubusercontent.com/11577857/37557449-181f96a2-29c2-11e8-8d62-afb37d26afb1.jpg)
![unaffected-product](https://user-images.githubusercontent.com/11577857/37557448-1805f044-29c2-11e8-802a-5bef586e1445.jpg)

The affected product shows:
`<small class="wcsatt-sub-options">– subscription plans available</small>` right after the price.

The unaffected product shows:
`<span class="subscription-details"> / week</span>`

I'm wondering if somehow, WooCommerce Extra Product Options Pro is triggering some kind of a loop, and in class-wcs-att-product-prices.php, around line 225, SATT outputs "wcsatt-sub-options" to get out of the loop?

Maybe it is related to this loop? -->  the price of the product changes depending on the options chosen in the product options dropdowns.

**Comment by franticpsyx** [comment]
@bethannon thanks for the issue report!

I'm afraid that at the moment we do not plan to support any third-party products -- SATT is already sitting between WooCommerce, WooCommerce Subscriptions and at least 3 official WooCommerce extensions, which means that maintenance requirements are already too high.

Happy to review and merge any code/PR that deals with this issue in a clean way.

**Comment by bethannon** [comment]
I completely understand. Unless client wants to just leave these products out off the subscription offerings, I'll probably outsource solution to Codeable. If it seems like it would be helpful, will def be back with the code to contribute!
