### ISSUE TITLE
Clarification: Add to an existing subscription?

### ISSUE THREAD

**Issue by seb86** [Prospress/woocommerce-subscribe-all-the-things#288]
@franticpsyx I am testing the latest 2.1.0 beta 2 release and when setting up a bookable product although it is not supported for subscriptions, the option to add the product to an existing subscription is still showing after the Book Now button. I wanted to know if this was intended or a bug.

Please, can you clarify? Thank you.

![Bookable Product](https://cldup.com/bHtBe9ubt1.png)

**Comment by franticpsyx** [comment]
@seb86 thanks for reporting this!

Looks like a bug, will be looking at this in the next few hours -- hopefully it's the last thing to fix before tagging `rc.1`.

**Comment by franticpsyx** [comment]
Closed via https://github.com/Prospress/woocommerce-subscribe-all-the-things/commit/84b08ff4f03229e6e16f1ffddde89d08fccbe999

**Comment by franticpsyx** [comment]
@seb86 should be good now, thanks again!
