### ISSUE TITLE
You can only switch to a subscription product

### ISSUE THREAD

**Issue by HowdyMcGee** [Prospress/woocommerce-subscribe-all-the-things#289]
Whenever attempting to modify your subscription ( My Account -> Subscriptions -> Modify ) I am receiving the following error:

> You can only switch to a subscription product

As far as I can tell Subscribe All The Things does not work with Variable Subscriptions. This was working at one point but some latest updates in either WooSubscriptions or this plugin has interfered. 

-----

### WordPress Environment ###

WC Version: 3.3.4
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.28
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.28.4

SUHOSIN Installed: –
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.4
WC Database Prefix: wp_ssc_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 6.68MB
Database Data Size: 5.17MB
Database Index Size: 1.51MB
wp_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_aiowps_events: Data: 0.02MB + Index: 0.00MB
wp_aiowps_failed_logins: Data: 0.02MB + Index: 0.00MB
wp_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB
wp_aiowps_login_activity: Data: 0.02MB + Index: 0.00MB
wp_aiowps_login_lockdown: Data: 0.02MB + Index: 0.00MB
wp_aiowps_permanent_block: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.08MB + Index: 0.05MB
wp_postmeta: Data: 2.19MB + Index: 0.66MB
wp_posts: Data: 0.19MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.05MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 83
customize_changeset: 3
fl-builder-template: 3
flamingo_contact: 8
flamingo_inbound: 1
nav_menu_item: 40
page: 10
product: 13
product_variation: 153
revision: 25
scheduled-action: 19
shop_order: 2
shop_subscription: 2
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

All In One WP Security: by Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.3.2

ARI Fancy Lightbox: by ARI Soft – 1.3.3
Beaver Builder Plugin (Standard Version): by The Beaver Builder Team – 2.0.6.3
Contact Form 7: by Takayuki Miyoshi – 5.0.1
Flamingo: by Takayuki Miyoshi – 1.8
Really Simple CAPTCHA: by Takayuki Miyoshi – 2.0.1
TinyMCE Advanced: by Andrew Ozz – 4.6.7
WooCommerce Stripe Gateway: by WooCommerce – 4.0.7
WooCommerce Menu Extension: by August Infotech – 1.6 – Not tested with the active version of WooCommerce
WooCommerce Subscribe All the Things: by Prospress Inc. – 2.1.0-beta.2
WooCommerce Subscriptions: by Prospress Inc. – 2.2.18
WooCommerce: by Automattic – 3.3.4

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #24 - /products/
Cart: #26 - /cart/
Checkout: #27 - /checkout/
My account: #28 - /my-account/
Terms and conditions: #37 - /terms-conditions/

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: –

### subscriptions ###

WCS_DEBUG: ✔
						No
Subscriptions Mode: ✔
						Live
Subscriptions Template Theme Overrides: –
Report Cache Enabled: ✔
						Yes
Cache Update Failures: ✔
						0 failure

**Comment by franticpsyx** [comment]
@HowdyMcGee could you please provide some clear steps to replicate this? Thanks!

**Comment by HowdyMcGee** [comment]
I apologize, I no longer have access to the project or resources to test this. We can close this issue.
