### ISSUE TITLE
Subscription products not available in composite product

### ISSUE THREAD

**Issue by michaelpalmer7** [Prospress/woocommerce-subscribe-all-the-things#291]
Hi,

I have successfully installed this add-in however when trying to add some subscription products to a component in WooCommerce Composite Products Subscription products are not being offered.

I don't know if its a bug or if I have missed a setting somewhere.

Thanks.

**Comment by franticpsyx** [comment]
@michaelpalmer7 Products with subscription schemes will not work as expected **in** Composite Products, but you can attach subscription schemes **to** Composite Products and the billing schedule will propagate to all Components.

What are you trying to achieve? Are you perhaps trying to offer an optional subscription/service with a Composite Product?

**Comment by michaelpalmer7** [comment]
Hi. 

I worked out the problem. It was me. 

Didn’t realise I had to set it as a simple product and use the ‘subscription’ tab. 

Works fine now. Great plugin. Thank you! 

Regards,

Michael

**Comment by franticpsyx** [comment]
Awesome -- thanks for the update, Michael. If you have a public URL that you can share, we'd love to see what you're up to!
