### ISSUE TITLE
Free Shipping IF customer subscribes to cart

### ISSUE THREAD

**Issue by giulianorapoz** [Prospress/woocommerce-subscribe-all-the-things#292]
Hello,

Is it possible to add a custom function to remove the flat rate shipping cost if a customer clicks the "Subscribe to cart" button?

Essentially what is the method which is called at this point to where an (IF Subscribed == Free shipping) could be added?

Thanks!

**Comment by franticpsyx** [comment]
Hey @giulianorapoz -- I'm pretty sure this is possible with some custom code but unfortunately this repository [is only used for issue/bug reporting and handling](https://github.com/Prospress/woocommerce-subscribe-all-the-things#support). Thanks for understanding!

**Comment by giulianorapoz** [comment]
Thanks @franticpsyx  - I'm aware that I probably need to do this with some custom code in a function...but I was wondering if you could point me to the name of the method which is called to detect if user has checked the "subscribe to cart" box?

**Comment by franticpsyx** [comment]
Hey @giulianorapoz check out `WCS_ATT_Cart::get_cart_subscription_scheme()`.
