### ISSUE TITLE
Cart Items Showing Subscribe Values Twice...

### ISSUE THREAD

**Issue by britandrews** [Prospress/woocommerce-subscribe-all-the-things#293]
Everything seems to work great with this extension. However, I notice that whenever I add a "Subscribed item to the cart, it will display the subscription options twice on the item. Any idea why this happens or how to fix it? (I've attached a screen capture below. We also run the Flatsome theme)

![capture](https://user-images.githubusercontent.com/38393368/38780250-5fdeb176-4088-11e8-9df1-ac7a0cf685b8.JPG)

**Comment by britandrews** [comment]
It would also be great if there was a built in option that allowed the administrator to change the basic text, such Subscription to Auto-Delivery. Also, the ability to turn off the text that appears in the main store on subscription products next to the price that says Subscription Available.

**Comment by franticpsyx** [comment]
@britandrews thanks for the issue report! 

This looks like a theme-related issue. Did you try to see if you can replicate this using a default WordPress theme, or Storefront?
