### ISSUE TITLE
Change wording

### ISSUE THREAD

**Issue by schmoot** [Prospress/woocommerce-subscribe-all-the-things#300]
Hello, I'd like to be able to change the wording, especially 'subscription plan available', can I do this via my functions file at all?

If not can you possibly add this as a new feature to the admin?

**Comment by franticpsyx** [comment]
Hey @schmoot -- unfortunately we can't provide much help with customizations like this, as this issue tracker is only for reporting bugs: https://github.com/Prospress/woocommerce-subscribe-all-the-things#support

You can use an plugin such as <a href="https://wordpress.org/plugins/loco-translate/">Loco Translate</a> to edit text strings. Although it may sound strange to "translate" in your own language, this is the best way to customize WooCommerce text strings, as the edits will not be overwritten when plugins are updated.

For details about localizing/translating WooCommerce and WooCommerce Extensions in general, please refer to https://docs.woocommerce.com/document/translate-woocommerce-extensions/#section-2​
