### ISSUE TITLE
Add subscription to cart by URL parameter

### ISSUE THREAD

**Issue by brycehamrick** [Prospress/woocommerce-subscribe-all-the-things#303]
Products can be added to the cart using the `add-to-cart` URL parameter, and variations of variable products can be specified with the `variation_id` parameter. Similarly, I would like to add a product subscription to cart with a URL parameter as well.

Is this already supported?

**Comment by franticpsyx** [comment]
Hey @brycehamrick -- see https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/product/class-wcs-att-product-schemes.php#L307
