### ISSUE TITLE
Limit number of items in subscriptions

### ISSUE THREAD

**Issue by gigamedia** [Prospress/woocommerce-subscribe-all-the-things#304]
Is it possible to limit the number of items for a subscription order?
I would like to offer a one-off purchase of a bag of coffee + 3 subscription options that only 3 bags of coffee can be added max for each subscription option.

**Comment by franticpsyx** [comment]
Hey @gigamedia -- unfortunately we can't provide any help with customizations like this. 

This issue tracker is only for reporting bugs: https://github.com/Prospress/woocommerce-subscribe-all-the-things#support

Thanks for understanding!
