### ISSUE TITLE
Cart Subscription Options

### ISSUE THREAD

**Issue by taylorsyn** [Prospress/woocommerce-subscribe-all-the-things#307]
How can I hide subscription options from the cart? It provides the options for one time and the monthly options I have set up. But I only want it to show what the customer already added to the cart

**Comment by franticpsyx** [comment]
Hey @taylorsyn -- do you see any scheme options under **WooCommerce > Settings > Subscriptions** ?

**Comment by franticpsyx** [comment]
Internal: Global scheme options are defaulting to a non-empty set: https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/admin/class-wcs-att-admin.php#L84

Doesn't seem necessary (bad NUX?), and might actually lead to issues like this.
