### ISSUE TITLE
Multiple combination products are not showing payment option

### ISSUE THREAD

**Issue by suresh17061988** [Prospress/woocommerce-subscribe-all-the-things#308]
If I choose the same subscription option on both products then the payment gateway does show up.

It's just as soon as I choose a mixed on that it no longer works. Such as one product per week and the other per week for 8 weeks.

It doesn't look like this combination is supported by the Subscribe All the Things plugin.

**Comment by franticpsyx** [comment]
Could you provide some more details about this issue? A screenshot or two would help. Thanks!

**Comment by suresh17061988** [comment]
Hello,
No worries, Below I am attaching two products. If you add them individually, They will work fine, But If you add them together in the basket and try to checkout payment option would not show up.
Both are composite product with subscription enabled

==> http://testaura.gourmetfuel.com/shop/meals/multi-packs/5-breakfast-multi-pack/
==> http://testaura.gourmetfuel.com/shop/meals/multi-packs/5-lunches-5-dinners-5-free-snacks

Once you add both and try to chekout. You will see below message

Screenshot URL:- https://prnt.sc/jnj79u

**Comment by franticpsyx** [comment]
@suresh17061988 doesn't seem to be an issue with SATT -- from the looks of it your payment gateway doesn't support multiple subscriptions.
