### ISSUE TITLE
UX: Variation prices are always overwritten by the single-product subscription options template markup

### ISSUE THREAD

**Issue by james-allan** [Prospress/woocommerce-subscribe-all-the-things#309]
HelpScout ticket: https://secure.helpscout.net/conversation/590443122/9914?folderId=1524484

The customer is reporting that there is no price displayed on the single product page when you have a variable product with a range of prices and subscription options, where the subscription pricing is forced.

To replicate: 

1. Create a variable product
2. Add multiple variation attributes
3. Add a variation for each attribute
4. Edit each variation and enter a different price for each one. We want the variable product's price to be displayed as a range (_From: $10.00 – $30.00 / month_)
5. Add some subscription options and force subscription pricing  (https://cloudup.com/cPdY-9gKUfI)

When you view this product's single product page and select a variation you should see something like this: 

![screen shot 2018-05-30 at 1 38 18 pm](https://user-images.githubusercontent.com/8490476/40697696-d6386ffc-640e-11e8-99b2-b91c22b809c5.png)

There's no indication to the customer how much the red variation is per month.

**Comment by franticpsyx** [comment]
Looks like we might need a bit more than a tiny patch here. Some thinking is necessary to determine when and how variation prices should be displayed in general -- not only when forcing subscriptions.

- [ ] Remove price from "None" option (doesn't seem right to only show it there).
- [ ] **Append** the subscription options markup to the variation price html and only hide the variation price if: 1) we are dealing with a single-scheme forced subscription case; or 2) no scheme exists that overrides the variation price AND all variation prices are equal.

Currently the generated subscription options markup  always overwrites the variation price html, which is wrong.
