### ISSUE TITLE
Disable Subscription options for items in Cart

### ISSUE THREAD

**Issue by taylorsyn** [Prospress/woocommerce-subscribe-all-the-things#315]
Is it possible to disable the Subscription options for each product in the cart? I want it to only show the selected option chosen when added to cart and hide the options not selected.

In the attached screenshot the item highlighted is what I only want to show as it was originally chosen.

<img width="861" alt="screen shot 2018-06-06 at 8 47 30 pm" src="https://user-images.githubusercontent.com/1904820/41077373-21ae9774-69cb-11e8-939d-bb9f91821fb2.png">

**Comment by GirvinIT** [comment]
I was able to create a quick fix for this by commenting out the filter which adds the radio buttons in class-wcs-display-cart.php. (line 39)

**Comment by taylorsyn** [comment]
I think you are on an older version, I am on the latest and line 39 for me is totally different. Also you mean class-wcs-att-display-cart.php?

<img width="1107" alt="screen shot 2018-06-11 at 1 41 17 pm" src="https://user-images.githubusercontent.com/1904820/41255995-26c106a6-6d7d-11e8-88ee-c2cbdd026794.png">

This is what I have, which one am I to comment out?

**Comment by GirvinIT** [comment]
I grabbed the code at the beginning of June and I checked the code in the repository and found the line I commented out.  I am curious as to there the add_filter call is in your version.

Your solution does the pretty much the same thing as mine, I just stopped the entire function from being used.

**Comment by taylorsyn** [comment]
@GirvinIT Thank you, much appreciated for pointing me in the right direction! :)

**Comment by franticpsyx** [comment]
Hey all,

See https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/class-wcs-att-product.php#L116 or https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/class-wcs-att-product.php#L159

**Comment by taylorsyn** [comment]
@franticpsyx Should I be doing something with those two references you provided? As it's not clear.

Currently, I have removed line 53 thru 58 in class-wcs-att-display-cart.php.

Thanks

**Comment by franticpsyx** [comment]
@taylorsyn -- these are filter hooks you can use to prevent cart-item subscription options from displaying. There's no need to modify plugin files directly.

**Comment by areejk** [comment]
@franticpsyx Can you please provide the code I need to add to remove the other options and only show the selected option in the cart. I am assuming this will go in the functions.php file?
