### ISSUE TITLE
No option to apply specific prices on variations based on subscription duration

### ISSUE THREAD

**Issue by 3kynox** [Prospress/woocommerce-subscribe-all-the-things#316]
Hello there,

I just ordered recently Woocommerce Composite Products in addition to my Woocommerce Subscriptions package and I saw adding subscription components is not possible on a composite products but I have the option to use subscribe-all-the-things plugin here for this purpose.

When I added options (1 month / 3 months / 6 months / 1 year) to my simple variable product, the only two options available about prices are:
- inherit from chosen variation
- override price

If I select inherit option, it inherit the variation price, but price remain the same for every duration option.
If I use override option, it override simply variation price and problem still the same. Does not matter which duration option is selected, price remain the same.

I feel weird with this approach. What's the goal having ability to put subscription on product variations if price remain the same for all subscription periods options ?

Or I missed something ? :)

Two screenshots attached:
https://i.imgur.com/nSUSZZo.png
https://i.imgur.com/lu5lEa0.png

Thanks anyway

**Comment by franticpsyx** [comment]
Hey @3kynox 

-- currently it's not possible to assign a different set of subscription schemes (or a different subscription scheme) to different variations of the same variable product.

This feature is part of our Roadmap. See "WCS Feature Parity Milestone 4: Subscription Schemes at Variation Level" at https://github.com/Prospress/woocommerce-subscribe-all-the-things/wiki/Roadmap#medium-term

If you need this feature urgently, it might be possible to do it by writing some custom code. However, this isn't something we can help with, unfortunately!

**Comment by franticpsyx** [comment]
PS: I hope I haven't misunderstood your question. If so, please provide a clearer, step-by-step issue description along with screenshots to help us understand exactly what you are having trouble with. Thanks!
