### ISSUE TITLE
Change "None" option text

### ISSUE THREAD

**Issue by taylorsyn** [Prospress/woocommerce-subscribe-all-the-things#318]
Need to Change "None" to "One Time Purchase & No Subscription"
<img width="1146" alt="screen shot 2018-06-15 at 1 11 13 pm" src="https://user-images.githubusercontent.com/1904820/41487464-a2fa612c-709d-11e8-8592-ba69f9fadc68.png">

**Comment by franticpsyx** [comment]
Hey @taylorsyn 

This issue tracker is [only for reporting bugs](https://github.com/Prospress/woocommerce-subscribe-all-the-things#support) so we can't help you with this customization.

If you wish to pursue this further, it might be a good idea to hire a WordPress/WooCommerce developer to help. I can recommend:

<ul>
<li><a href="http://codeable.io/">Codeable</a>.</li>
<li>A <a href="http://woocommerce.com/experts/">WooExpert</a>.</li>
</ul>

Thanks for understanding!

**Comment by Goldendust20** [comment]
If you use jQuery you can add this:

$( ".one-time-option-details" ).each(function() {
		//get the text for just the element being iterated over
		var text = $(this).text();
		var comparingText = 'none';

		if(text == comparingText){
			$(this).replaceWith("One Time Purchase");
		}
	});
