### ISSUE TITLE
Breaks Affiliate/External product data links!

### ISSUE THREAD

**Issue by taylorsyn** [Prospress/woocommerce-subscribe-all-the-things#319]
When I deactivate subscribe all the things the links work fine however when its activated the external link will not load for a product that is data type: External/Affiliate!

This is with the latest version of woo commerce

**Comment by franticpsyx** [comment]
@jimjasson could you please take a look at this? Thanks!

**Comment by jimjasson** [comment]
@franticpsyx Confirmed! 

These are the plugins I kept active: https://cl.ly/0q2j1g273a0C

I then created an Affiliate Product with an external URL to a Simple Product: https://cl.ly/3w3j1R2y0e2D

When SATT is active, the 'Buy Product' button redirects to the same page. When SATT is deactivated, the 'Buy Product' button redirects to the Simple Product's page: https://cl.ly/003x413v0E0j

**Comment by taylorsyn** [comment]
Yes its true =\ Thus making this plugin unusable at the moment because we have many affiliate links. Is there an ETA to fixing this? Thanks

**Comment by franticpsyx** [comment]
### Cause ###

See 4f794399a0aa1673204688537a1d03ec97d5ceca

When using `indexOf` we need to check for `-1`, not boolean.

**Comment by franticpsyx** [comment]
@taylorsyn this is now fixed in master. We'll wait a bit before rolling out a fix release as I don't consider this as something that requires a hotfix right away, but if a couple weeks pass without another commit we'll definitely tag 2.1.2 and release it.
