### ISSUE TITLE
Request: Usability bug "None" subscription option, change text.

### ISSUE THREAD

**Issue by taylorsyn** [Prospress/woocommerce-subscribe-all-the-things#323]
Hi,

I audited the source and found no way to change the text "None" under Product page subscription options for no subscription. But maybe I missed something

We had someone who is an expert in usability for online e-commerce tell us that None is misleading for customers, especially with the elderly. Even despite this "None" is not proper syntax for no Subscription plan. It should be "No Subscription" or "One time purchase".

I know it makes sense to us, or better yet we don't even think about it but for the layperson who thinks ordering online is a challenge this can be a deal breaker for some people.

**Comment by willgorham** [comment]
Can't you use the `wcsatt_single_product_one_time_option_description` filter? https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/6f7bbc63b2b484d55f8adb30c76207dc74deaed2/includes/display/class-wcs-att-display-product.php#L93

**Comment by taylorsyn** [comment]
@willgorham Why thank you, got it line 89. I feel as though this would be helpful to add to the notes. As its a big part of the UI especially for older non tech savy users.
