### ISSUE TITLE
ShipStation Plugin

### ISSUE THREAD

**Issue by spouellet** [Prospress/woocommerce-subscribe-all-the-things#324]
I have an issue with ShipStation Integration plugin. I can't import orders from Woocommerce. 500 Internal Error.

I have done some research and disabled all plugin to test it, and it appears that the issue is solve when I disabled Subscribe all the things plugin. I have both plugin since 9 months and never had issues. Don't know why now...

**Comment by willgorham** [comment]
I have a site running SATT and ShipStation Integration and everything seems to be working fine. 500 errors are usually PHP errors so you should check your error logs (if you haven't already).

**Comment by franticpsyx** [comment]
Closing -- if you are running out of memory then disabling any sufficiently large plugin would probably have the same effect.

SATT does not interfere with shipping, it's all handled by WCS/WC.
