### ISSUE TITLE
Integration with Gift subscription

### ISSUE THREAD

**Issue by HypeDigital** [Prospress/woocommerce-subscribe-all-the-things#326]
Could you please make this work with Gift Subscription? Right now the box doesnt show up on the product page and the checkout page the checkbox and fill out form doesnt show up.

**Comment by franticpsyx** [comment]
Hey @HypeDigital 

This is something we'd love to do but not before we clear a bunch of higher priority items off our queue.

Please remember that it's rarely possible to make two plugins "play nice" with each other by writing code on one side -- so a decision to introduce compatibility between two plugins is not a decision to be taken lightly and needs to be prioritized on a cost/benefit basis.

Currently there is no plan to support for Gifting in the near future, but we'll keep gathering feedback and continue to evaluate things here.

cc @james-allan in case you want to log this on the Gifting side as well.

Thanks!
