### ISSUE TITLE
subscribe option for each variation

### ISSUE THREAD

**Issue by jubinrnds** [Prospress/woocommerce-subscribe-all-the-things#327]
Hi, first of all, appreciate your effort, nice extension . I have some suggetion about product subscription, the current subscription button for 'simple product' is just adding rules for whole variation of that product, 
my idea is , If I have 4 variation of product size (ex: 2,5,10,15) , and if variation '10' is the only one that need subscription, I can not implement that by common rule , ( force subscription hide single purchase of all product ), I thought separate subscription option field for each variation may be a solution for that. so the final result will be like
product variations : 

2 - single purchase only , no subsciption
5 - single purchase only , no subsciption
10 - subscitpion option with 3month/6month , no single purchase
15 -  single purchase only , no subsciption

Thank you

**Comment by franticpsyx** [comment]
Hey @jubinrnds 

Thanks for the feedback! This is already logged in the SATT [Roadmap](https://github.com/Prospress/woocommerce-subscribe-all-the-things/wiki/Roadmap).

At the moment I'm afraid I have no ETA to share -- what I can say confidently is there is no plan to make this feature available within the next 3-4 months.
