### ISSUE TITLE
How to bulk-add "Subscription Options" to all products?

### ISSUE THREAD

**Issue by vvdan** [Prospress/woocommerce-subscribe-all-the-things#328]
Hi<

First of all congrats on the work done with this extension.

At the moment, if I'm not missing something, the process of enabling Subscribe all the things to  Simple product types is:
Go to product data > click subscriptions > click Add Option > Menu with variables then shows on the screen > Edit > Save.

Is there any chance we can do a bulk update by CSV or by any means in order to have all products enabled for Subscribe all the things?

I've got 800 prouducts and clicking 1 by 1 would be really time consuming.

From what I can figure out in the code the action / button is ajax based:

```
		<div class="subscription_schemes wc-metaboxes ui-sortable" data-count=""><?php
						$i = 0;
						foreach ( $subscription_schemes as $subscription_scheme ) {
							do_action( 'wcsatt_subscription_scheme', $i, $subscription_scheme, '' );
							$i++;
						}
					?></div>
					<p class="toolbar">
						<button type="button" class="button add_subscription_scheme"><?php _e( 'Add Option', 'woocommerce-subscribe-all-the-things' ); ?></button>
```

My apologies if I'm missing something or I've said something stupid, I'm still relatively new with php and coding.

Any suggestion would be greatly appreciated.
Dan

PS: Is there any chance we can customize "every week" or "per month" label?
I think the previous version of this extension allowed that.
![need bulk](https://user-images.githubusercontent.com/41474135/42999513-fabcda82-8c15-11e8-85fe-d496782e9d8a.png)

**Comment by franticpsyx** [comment]
Hey @vvdan 

Thanks for the kind words!

Unfortunately there is no "manual" way to do this at the moment. You could possible add a meta field with this data to all these products using the Importer, but you'd need to do some work to generate the required scheme data the first time.

I think this would be a straightforward task for a WooCommerce/WordPress developer. While we can't help with customizations/features like this ourselves, you could perhaps join the WooCommerce community on Slack via https://woocommerceslack.herokuapp.com and seek for help there, or perhaps try a service such as [Codeable](codeable.io)?
