### ISSUE TITLE
Always "Failed to load matching subscriptions."

### ISSUE THREAD

**Issue by christianphilie** [Prospress/woocommerce-subscribe-all-the-things#331]
I'm trying to get adding all cart items to existing subscriptions to work. Everytime I click the checkbox "Add this cart to an existing subscription" I get the error: "Failed to load matching subscriptions. If this issue persists, please re-load the page and try again." But of course there are many subscriptions available for the logged-in customer. 

I checked the response of the AJAX request in assets/js/wcs-att-cart.js on line 102 and the result is always "false". 

Any ideas what to do about that? 
Thanks in advance for any recommendations!

WordPress Version 4.9.8
WooCommerce Version 3.3.3
WooCommerce Subscriptions Version 2.2.12

Also I have these other WooCommerce plugins activated, which might be of interest:
WooCommerce Germanized Version 1.9.9
WooCommerce Stripe-Gateway Version 4.1.3 
WooCommerce PDF Invoices & Packing Slips Version 2.1.10

**Comment by franticpsyx** [comment]
@christianphilie are you 100% certain that the chosen cart subscription scheme "matches" some existing subscriptions? 

You can check the logic behind "matching" at https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/class-wcs-att-scheme.php#L356

If your cart subscription schemes have a length, for example, then (by default) only active subscriptions with a matching number of remaining renewals will be matched.
