### ISSUE TITLE
Re-subscribe validation when a product was manually-added to a subscription

### ISSUE THREAD

**Issue by franticpsyx** [Prospress/woocommerce-subscribe-all-the-things#333]
### Description ###

See analysis in https://github.com/Prospress/woocommerce-subscribe-all-the-things/pull/329

1. Create a regular simple product [with no subscription options](https://cloudup.com/cTrfyGyaInP)
2. From the **WooCommerce > Subscription** table click "Add New"
3. Create a new subscription adding the simple product as a line item and selecting your user as the customer.
4. Create a parent order or process a renewal. This order needs to have a completed/processing status - we need at least 1 completed payment. 
5. Now cancel the subscription. 
6. From your **My Account > View subscription** page click resubscribe.
7. You should get an error which looks like this: https://cloudup.com/cY2EoHGMiPp

### Desired Behavior ###

* If a product has a set of schemes associated with it, check whether the scheme that's set on it when re-subscribing is a valid one. Include a filter to allow validation to pass when this condition isn't met.
* If a product doesn't have any schemes associated with it, then we don't need to do anything. SATT validation will never kick in.

Also see 
https://github.com/Prospress/woocommerce-subscribe-all-the-things/pull/329#issuecomment-411636810

**Comment by NickGreen** [comment]
https://secure.helpscout.net/conversation/626484821/15046/?folderId=1524435

@franticpsyx Merchant is reporting that this isn't fixed in 2.1.4

**Comment by zhollenbeak** [comment]
@franticpsyx Here are additional details that the customer is reporting with this latest SATT release
Clicking Resubscribe returns this message: 
"There are some issues with the items in your cart. Please go back to the cart page and resolve these issues before checking out"
And trying to change anything deletes the products and reads the cart is empty.

**Comment by franticpsyx** [comment]
@NickGreen @zhollenbeak thanks, can't replicate this locally though.

Wondering if this has anything to do with the billing details of the subscription (period, length, interval, synced, etc)?

Can you share more info here or via Slack?
