### ISSUE TITLE
Down- or Upgrade product in existing subscription

### ISSUE THREAD

**Issue by mazgor** [Prospress/woocommerce-subscribe-all-the-things#335]
(1) If I klick 'my subscription' and than choose an item on the subscription to up-or downgrade I get to the product view, if I change the number of that item, it works, I can switch, but it's not very elegant, as I get to the product view, where I can see all the available subscription options for this product and can choose any. Of course the switch only works, if I choose the same interval as the existing subscription already has... so it would be better, if only that subscription option would be displayed that matches the existing subscription as I come from up- and downgrade and don't wanna change the interval and customers could get confused by thinking, oh great, I can also 'switch' the interval... of course they can, but than a new subscription is created and the old one remains unchanged, so the customer would have that product twice, once with the old interval and now with the newly chosen interval, that's not so good.
(2) The message 'choose new subscription' remains even after I clicked the sign up and the new subscription was added to the cart, here it would be good to display something like 'Proceed to checkout to finish your up- and downgrad' or even better, why not - after having clicked the sign up - being forwarded directly to the check out page and displaying a message like e.g. please press 'sign up' in order to finish your up- or downgrade?

--> It would be great, if the up- and downgrade would be as easy as the add to existing subscription, which means, with a button eg 'change' (as the add+-button) and no need of going through the check out again...

**Comment by franticpsyx** [comment]
Hi @mazgor 

Switching functionality is mostly handled by WCS, not by SATT.

While I agree that the current flow could be optimized in some use cases, it's the safest and most reliable/compatible one to take.

> of course they can, but than a new subscription is created and the old one remains unchanged, so the customer would have that product twice, once with the old interval and now with the newly chosen interval

The intended behavior is that the original subscription should no longer contain the "switched" product. If you are seeing something different, than I would strongly advice contacting the WooCommerce Subscriptions support team via 
http://woocommerce.com/my-account/marketplace-ticket-form/.
