### ISSUE TITLE
Need support

### ISSUE THREAD

**Issue by intmanu** [Prospress/woocommerce-subscribe-all-the-things#336]
Hi,

I have set up "woocommerce-subscribe-all-the-things" and using one of the functionality that is "Cart Subscription".

I have set up 3 Schemes on that, 6 Months/12Months/18Months.

I just want to check if there is a possibility  to get the cart amount to recalculate with split up when i choose the scheme. Right now it shows total amount as monthly subscription rather than recalculating the amount by splitting the amount according to scheme duration.

Below is one example for more clarity.

- The cart total is $35000 before applying cart scheme
- Once cart scheme of 6 months is selected the cart total should be $5833 per month
- Right now it shows $35000 Per month when we select schemes of 6/12/18 months.

Kindly let me know if there is a way to achieve this.

Regards,
Manjunath Chandran

**Comment by willgorham** [comment]
Sounds to me like you're setting the interval to 6/12/18 months, but you want that to be the total duration and the interval to be monthly. Is that correct?

In that case, you want to set the interval to 1 month and the length to 6, 12, or 18 months.

**Comment by intmanu** [comment]
Thanks for the response will. I have already done what is specified by you. The total price does not change when we select either of 6/12/18 months options. I have attached the screen shot of the cart settings and also the screenshots when i make the selections of 6 and 12 months which shows the total price to remain same but with just a change of the months.
![screen shot 2018-08-21 at 11 31 26 pm](https://user-images.githubusercontent.com/6958306/44420496-ba5d7100-a59b-11e8-9fcd-e4a026ec4838.png)
![screen shot 2018-08-21 at 11 31 23 pm](https://user-images.githubusercontent.com/6958306/44420497-ba5d7100-a59b-11e8-84b6-a9c2f3b33c1c.png)
![screen shot 2018-08-21 at 11 31 01 pm](https://user-images.githubusercontent.com/6958306/44420499-ba5d7100-a59b-11e8-9e83-b1278f42a862.png)
![screen shot 2018-08-21 at 11 42 30 pm](https://user-images.githubusercontent.com/6958306/44420561-e7aa1f00-a59b-11e8-9502-d3074abecfb6.png)

**Comment by intmanu** [comment]
Hi Will,

Any updates on this..

**Comment by willgorham** [comment]
Ah, sorry, I see what you're saying. I don't think this plugin is designed to handle paying in installments, which is what you're looking to achieve.

The way your settings are configured, the behavior is correct. Basically what it says is: 'I want to purchase the entire cart every month for 6 (e.g.) months and then stop.' There's not way (as far as I know) to say 'I want to purchase the entire cart and pay for it over 6 months in monthly installments.

You could do this at an individual product level I think, but not for the whole cart (there are no options to override cart price). Maybe a feature request? Someone with more knowledge about cart subscriptions might be able to tell you more, it's not something I'm too familiar with :)

**Comment by franticpsyx** [comment]
@intmanu this is an interesting use case, however, as @willgorham said, SATT is not really designed for this.

Maybe you can get this to work at product-level, by overriding prices for each scheme in a way that the accumulated amount adds up to the desired total -- however to get this to work reliably you would need to ensure that customers will not be able to cancel their subscription before the full amount has been paid for.

@thenbrent could WCS be used like this? Do you see any value in researching SATT's ability to be used as a solution for offering "installments" at product or cart level? Do you see any constraints here on the WCS side?

If the technical overhead for implementing this is small, we could keep this in mind for the future. At product level this seems possible already -- at cart level I guess it would take more than a "Discount" option to support installments properly.
