### ISSUE TITLE
Default to 'Subscription' on product level

### ISSUE THREAD

**Issue by mazgor** [Prospress/woocommerce-subscribe-all-the-things#337]
If there is a subscription option on product level and default is set to subscription, this works not for variabel products, there the default in the shop is 'None', only single products have the subscription option as default.

**Comment by franticpsyx** [comment]
Hey @mazgor -- thanks for the issue report! Could you perhaps send us a couple screenshots (**Product Data > Subscriptions** tab, single-product page) to make this clearer? Thanks!

**Comment by mazgor** [comment]
Sure. Pls see attached screenshots for two products, one single, one variabel.

Both are set default to subscription, but only the single one works, and I saw that all my var products don’t work and all single products do work….

Fronend Single:
https://demosite.biomilchmann.ch/product/demeter-vollmilch-past-1-liter-tetra/ <https://demosite.biomilchmann.ch/product/demeter-vollmilch-past-1-liter-tetra/>

Frontend Var:
https://demosite.biomilchmann.ch/product/demeter-hybrid-eier/ <https://demosite.biomilchmann.ch/product/demeter-hybrid-eier/>


Best regards, Lukas

**Comment by mazgor** [comment]
Just saw, that the attachments via email-reply didn't go through, sorry.  So here the backend-view of the two products, one VAR and SINGLE, both default set to subscription.

![varprod_backend_notworking](https://user-images.githubusercontent.com/35103175/44331053-d44a6700-a468-11e8-8be2-0fd9cbc90a3e.png)
![singprod_backend_working](https://user-images.githubusercontent.com/35103175/44331054-d44a6700-a468-11e8-9cfd-113358cca3ec.png)

**Comment by franticpsyx** [comment]
### Cause ###

`WC_ATT_Product_Subscription_Schemes::get_default_subscription_scheme` does not include a fallback-to-parent mechanism when a variation is passed as an argument.

Additionally, for performance reasons `WCS_ATT_Display_Product::get_subscription_options_content` should operate directly with parent products when fetching properties that we are unlikely to allow overriding at variation level later.

**Comment by franticpsyx** [comment]
@mazgor this should be fixed on `master` now -- thanks again for the issue report!

**Comment by mazgor** [comment]
Dear Manos! Wow, thank you very much. That was quick :)
