### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by derekakelly** [Prospress/woocommerce-subscribe-all-the-things#341]
Hello,

First off a big thank you to everyone working on this project, it's become an invaluable part of my website. Everything is functioning as expected, but i routinely use Query Monitor to check my website for issues and it came up with a PHP warning today on my homepage. I then went to the listing here and noticed I had an outdated copy running, so I immediately updated it. The warnings still remained, so I wanted to report it.

Here's a screen shot
https://imgur.com/a/4Ovebgd

Also, while I was refreshing myself by reading your guide, I noticed in the Installation Section, in the 3rd step, you mention "select the .zip you downloaded in Step 1", well there's no mention of this in Step 1. Obviously I know how to download it, but some others may not be as familiar with github.

Any chance you'll set this up as a wordpress.org plugin for easier updates?

Thanks for your time,
Derek

**Comment by franticpsyx** [comment]
Hey @derekakelly 👍 

Could you please paste the entire logged message down to the last step/number? Thanks!

**Comment by derekakelly** [comment]
Hello @franticpsyx,

Thanks for the prompt response!

Here you go, it's the same as the screen shot. 
`
do_action('homepage')
wp-content/themes/storefront-child/template-homepage.php:32
storefront_recent_products()
wp-includes/class-wp-hook.php:286
storefront_do_shortcode()
wp-content/themes/storefront/inc/storefront-template-functions.php:624
WC_Shortcodes::products()
wp-content/themes/storefront/inc/storefront-functions.php:51
WC_Shortcode_Products->get_content()
wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php:264
WC_Shortcode_Products->product_loop()
wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-products.php:100
wc_get_template_part()
wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-products.php:617
load_template('wp-content/plugins/woocommerce/templates/content-product.php')
wp-content/plugins/woocommerce/includes/wc-core-functions.php:179
wc_product_class()
wp-content/plugins/woocommerce/templates/content-product.php:27
wc_get_product_class()
wp-content/plugins/woocommerce/includes/wc-template-functions.php:651
apply_filters('post_class')
wp-content/plugins/woocommerce/includes/wc-template-functions.php:640
wc_product_post_class()
wp-includes/class-wp-hook.php:286
WC_Product->is_on_sale()
wp-content/plugins/woocommerce/includes/wc-template-functions.php:470
WC_Product->get_sale_price()
wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php:1468
WC_Data->get_prop()
wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php:293
apply_filters('woocommerce_product_get_sale_price')
wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php:703
WCS_ATT_Product_Price_Filters::filter_sale_price()
wp-includes/class-wp-hook.php:286
WCS_ATT_Product::is_subscription()
wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/product/class-wcs-att-product-price-filters.php:290
WCS_ATT_Product_Schemes::has_active_subscription_scheme()
wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/class-wcs-att-product.php:73
WCS_ATT_Product_Schemes::get_subscription_scheme()
wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/product/class-wcs-att-product-schemes.php:70
WCS_ATT_Product_Schemes::get_subscription_schemes()
wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/product/class-wcs-att-product-schemes.php:158
wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/product/class-wcs-att-product-schemes.php:107`

from debug.log.

`[24-Aug-2018 18:52:21 UTC] PHP Warning:  Invalid argument supplied for foreach() in ..../wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/product/class-wcs-att-product-schemes.php on line 107`

The homepage has 8 identical warnings, whereas the catalog and product pages generally are only getting a single warning, but not always... Sometimes there aren't any warnings coming up, sometimes there's 6. They're inconsistent, but it's always coming up on the homepage. 

I got it to come up 6 times on this page
https://www.carewayclub.com/product-category/personal-care/

`wc_get_template()
wp-content/plugins/woocommerce/templates/taxonomy-product_cat.php:22
wc_get_template_part()
wp-content/plugins/woocommerce/templates/archive-product.php:72
load_template('wp-content/plugins/woocommerce/templates/content-product.php')
wp-content/plugins/woocommerce/includes/wc-core-functions.php:179
wc_product_class()
wp-content/plugins/woocommerce/templates/content-product.php:27
wc_get_product_class()
wp-content/plugins/woocommerce/includes/wc-template-functions.php:651
apply_filters('post_class')
wp-content/plugins/woocommerce/includes/wc-template-functions.php:640
wc_product_post_class()
wp-includes/class-wp-hook.php:286
WC_Product->is_on_sale()
wp-content/plugins/woocommerce/includes/wc-template-functions.php:470
WC_Product->get_sale_price()
wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php:1468
WC_Data->get_prop()
wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php:293
apply_filters('woocommerce_product_get_sale_price')
wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php:703
WCS_ATT_Product_Price_Filters::filter_sale_price()
wp-includes/class-wp-hook.php:286
WCS_ATT_Product::is_subscription()
wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/product/class-wcs-att-product-price-filters.php:290
WCS_ATT_Product_Schemes::has_active_subscription_scheme()
wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/class-wcs-att-product.php:73
WCS_ATT_Product_Schemes::get_subscription_scheme()
wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/product/class-wcs-att-product-schemes.php:70
WCS_ATT_Product_Schemes::get_subscription_schemes()
wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/product/class-wcs-att-product-schemes.php:158
wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/product/class-wcs-att-product-schemes.php:107`

Thanks for your time,
-Derek

**Comment by derekakelly** [comment]
Just noticed it's also coming up on the product list in the backend. I have it set to display 40 products at a time in my list and it came up with 40 warnings.
`WP_List_Table->display()
wp-admin/edit.php:362
WP_List_Table->display_rows_or_placeholder()
wp-admin/includes/class-wp-list-table.php:1097
WP_Posts_List_Table->display_rows()
wp-admin/includes/class-wp-list-table.php:1165
WP_Posts_List_Table->_display_rows()
wp-admin/includes/class-wp-posts-list-table.php:641
WP_Posts_List_Table->single_row()
wp-admin/includes/class-wp-posts-list-table.php:659
WP_List_Table->single_row_columns()
wp-admin/includes/class-wp-posts-list-table.php:1195
WP_Posts_List_Table->column_default()
wp-admin/includes/class-wp-list-table.php:1254
do_action('manage_product_posts_custom_column')
wp-admin/includes/class-wp-posts-list-table.php:1162
WC_Admin_List_Table->render_columns()
wp-includes/class-wp-hook.php:286
WC_Admin_List_Table_Products->render_name_column()
wp-content/plugins/woocommerce/includes/admin/list-tables/abstract-class-wc-admin-list-table.php:261
WC_Product->get_regular_price()
wp-content/plugins/woocommerce/includes/admin/list-tables/class-wc-admin-list-table-products.php:173
WC_Data->get_prop()
wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php:283
apply_filters('woocommerce_product_get_regular_price')
wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php:703
WCS_ATT_Product_Price_Filters::filter_regular_price()
wp-includes/class-wp-hook.php:286
WCS_ATT_Product::is_subscription()
wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/product/class-wcs-att-product-price-filters.php:274
WCS_ATT_Product_Schemes::has_active_subscription_scheme()
wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/class-wcs-att-product.php:73
WCS_ATT_Product_Schemes::get_subscription_scheme()
wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/product/class-wcs-att-product-schemes.php:70
WCS_ATT_Product_Schemes::get_subscription_schemes()
wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/product/class-wcs-att-product-schemes.php:158
wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/product/class-wcs-att-product-schemes.php:107`

**Comment by derekakelly** [comment]
I know what happened... Recently I've been importing CSV products sheets onto my website. because some of the products were to be used with your plugin, there's a few columns set for your meta attributes. It looks like there was a data entry error that wasn't caught prior to being imported.
https://imgur.com/a/dNyEht7
