### ISSUE TITLE
Subscription Switching

### ISSUE THREAD

**Issue by michaelpalmer7** [Prospress/woocommerce-subscribe-all-the-things#342]
Hi,

Great plugin by the way it's really helped me as I use WC Composite Products to configure Subscription products.

Are there any plans to support subscription switching?

Right now I can't do that as WC Subscriptions will only support Subscription Products.

Thanks,

Michael

**Comment by franticpsyx** [comment]
It's planned feature :) 

See https://github.com/Prospress/woocommerce-subscribe-all-the-things/wiki/Roadmap#medium-term (Medium Term).

We have no ETA to share at the moment!
