### ISSUE TITLE
Bundled variations subscription, would like to change the variations for next order

### ISSUE THREAD

**Issue by the-de-coder** [Prospress/woocommerce-subscribe-all-the-things#344]
After the bundled variations are set as a subscription, we'd like to allow the customer to change one or more of the variations for the next order.  Can you help with this?

**Comment by SundayDriver** [comment]
We also have this issue and would like that functionality.

**Comment by franticpsyx** [comment]
Already logged -- see https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/241

Unfortunately we have no ETA to share at the moment.
