### ISSUE TITLE
Add sign up fee with variable product

### ISSUE THREAD

**Issue by areejk** [Prospress/woocommerce-subscribe-all-the-things#345]
Hi,

When using variable products, is it possible to include a sign up fee, just like the variable subscription option. If so I would appreciate it if someone could point me in the right direction. If not is this something which will be available in the future?

**Comment by franticpsyx** [comment]
See https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/224

This is already logged in the SATT roadmap but unfortunately we have no ETA to share at the moment.
