### ISSUE TITLE
Change Text

### ISSUE THREAD

**Issue by POMgithub** [Prospress/woocommerce-subscribe-all-the-things#352]
Sorry to bother you with this, can you please tell me the filter used to change the word "none" to single purchase. I have the text above the subscription options saying "Choose Purchase Option" and I would like it to say Single Purchase. Thank you for your help.

**Comment by willgorham** [comment]
Hey @POMgithub, the filter is found here: https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/b03ccc2097d4071a2af5603de202cacbb59fe06a/includes/display/class-wcs-att-display-product.php#L96

**Comment by thenbrent** [comment]
Thanks @willgorham. 🙇
