### ISSUE TITLE
Variations lost when adding to subscription

### ISSUE THREAD

**Issue by thenbrent** [Prospress/woocommerce-subscribe-all-the-things#355]
As reported in https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/349#issuecomment-426445804

> When adding to an existing subscription, the variations are lost so we do not know what customers have ordered.

See video here: https://cl.ly/233b80e2f883

**Comment by thenbrent** [comment]
@SundayDriver I wasn't able to reproduce this. When I add the variation, all attributes are added correctly. See this video: http://pic.pros.pr/ebe0cf176edb

That's with settings to allow _all_ products to be added to subscriptions (screenshot of settings: http://pic.pros.pr/b362ab5a487e).

I noticed in your video that the checkbox only showed up _after_ clicking the radio button to choose a subscription, so it's possibly related to the setting. Or it could be related to the Toolbox plugin.

**Comment by SundayDriver** [comment]
Thanks for the video Brent, it helped me diagnose this further and I think I have figured it out. 

I have kept disabled toolbox just to rule things out. I did not see any change. 

In the screenshot below you will see 4 different variations. 
1- 15ml, 3mg - This variation shows up correctly when adding to a subscription. It will show the Size AND the Nicotine Level. 
2- Any Size, Any Nicotine Level - This variation will not show any attributes when added to a subscription. 
3- 15ml, Any Nicotine Level - This variation will show the size but not the nicotine level. 
4- 30ml, Any Nicotine Level - This variation will show the size but not the nicotine level. 

<img width="910" alt="screen shot 2018-10-03 at 11 37 20 am" src="https://user-images.githubusercontent.com/77760/46421749-d149c400-c700-11e8-8eb8-ca8e173466c6.png">
<img width="773" alt="screen shot 2018-10-03 at 11 42 52 am" src="https://user-images.githubusercontent.com/77760/46422080-8a100300-c701-11e8-97c5-75f504f2f962.png">

I had a video but it failed to upload properly. You will see that the attributes are only shown on the subscription IF you create a variation for every possible attribute. You cannot use the "Any" option and have it show the variations. 

I believe this is a bug. It works properly the first time, but not for adding to a subscription.

**Comment by thenbrent** [comment]
Thanks @SundayDriver it sounds like this is being caused by variations with no attributes set.

Variations without defined attributes can cause unexpected behaviour in a few cases. For example, [switching subscriptions](https://docs.woocommerce.com/document/subscriptions/switching-guide/#section-20). When possible, it's definitely best to setup all variations to have defined attributes, because then those attributes can be derived with just the variation IDs.

In this case, it's likely possible to support the variations without defined attributes, because we should be able to derive that from the selections on the page. I'm not sure that's something we'll do though.

@franticpsyx thoughts on this one?

**Comment by franticpsyx** [comment]
Definitely a bug on our side.

I _think_ there's a misnamed key [here](https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/modules/management/add/class-wcs-att-manage-add-product.php#L431) and then the mistake carries on [here](https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/modules/management/class-wcs-att-manage-add.php#L167) and eventually [here](https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/modules/management/class-wcs-att-manage-add.php#L418).

I love how WC works out the missing bits when it can, but no -- we didn't intentionally let this slip through. The necessary code is there in SATT, but it looks like someone's memory failed him, WC calls that key `variation`, not `variations`.

**Comment by franticpsyx** [comment]
Adding this to the queue for the next patch release.
