### ISSUE TITLE
Product Bundles Switching

### ISSUE THREAD

**Issue by TSB2019** [Prospress/woocommerce-subscribe-all-the-things#358]
Hi there, is there any update on when we will be able to offer customers switching with product bundles? We have WCS and SATT an we are unable to offer switching currently.

**Comment by thenbrent** [comment]
Hi @TSB2019 no update yet unfortunately. We're working on figuring out how to commercialise SATT at the moment so that both the teams at SomewhereWarm and Prospress can prioritise work on it in future.
