### ISSUE TITLE
'Invalid recurring shipping method.' and new WC Subscriptions v2.0.14

### ISSUE THREAD

**Issue by shadimanna** [Prospress/woocommerce-subscribe-all-the-things#36]
After upgrading to WC Subscriptions v2.0.14 we are getting this error 'Invalid recurring shipping method.' for simple products that have a subscription option using WSATT plugin.  It seems WC Subscriptions v2.0.14 adds a validation in the file 'wp-content/plugins/woocommerce-subscriptions/includes/class-wc-subscriptions-cart.php' function 'validate_recurring_shipping_methods()' that adds some sort of validation on shipping but fails on WSATT subscription products.    For now I have downgraded WC Subscriptions but a fix is preferable of course.

**Comment by franticpsyx** [comment]
@thenbrent Not sure what might be going on here after looking at Subs code a couple times. Inline doc of `class-wc-subscriptions-cart.php` is OK, but I'm missing some background that I'd need to be fully able to grasp the underlying logic.

**Comment by thenbrent** [comment]
@franticpsyx yeah, we do some pretty crazy things with recurring shipping from v2.0.12 onwards in Subscriptions, and shipping gets _really_ complicated, so I want to save you going down that rabbit hole!

I've assigned this one to me so will tackle it. For reference, it would have been introduced with https://github.com/Prospress/woocommerce-subscriptions/pull/1358

**Comment by thenbrent** [comment]
@shadimanna if you have a site you can easily test v2.0.14 on again, would you mind changing line 258 of `woocommerce-subscriptions/includes/class-wc-subscriptions-cart.php` from:

```
// Keep a record of the shipping packages so we can add them to the global packages later
self::$recurring_shipping_packages[ $recurring_cart_key ] = WC()->shipping->get_packages();
```

To:

```
// Keep a record of the shipping packages so we can add them to the global packages later
if ( 0 != $recurring_cart->next_payment_date ) {
	self::$recurring_shipping_packages[ $recurring_cart_key ] = WC()->shipping->get_packages();
}
```

And letting us know if that fixes it?

That fix is from a separate, but possible related, issue (https://github.com/Prospress/woocommerce-subscriptions/pull/1404).

**Comment by franticpsyx** [comment]
@thenbrent In case it helps, I'm also getting a `PHP Notice:  Undefined index: every_2nd_month_0 in /wp-content/plugins/woocommerce-subscriptions/includes/class-wc-subscriptions-cart.php on line 1070`

>I've assigned this one to me so will tackle it.
Ops, sorry, just noticed. Dived straight to the code as soon as I saw the notification.

**Comment by shadimanna** [comment]
@thenbrent I tried your fix but it still seems to be happening. Do you want me to give you access to the staging site so you can take a look?  If not let me know and I can test another fix.

**Comment by thenbrent** [comment]
@shadimanna that would be a great help. Please email temp admin creds to support@prospress.com. 😄

**Comment by thenbrent** [comment]
We’ve now fixed this issue in Subscriptions. The PR with the fix here: https://github.com/Prospress/woocommerce-subscriptions/pull/1404 (for those with access to the repo).

We plan to release that this week in a version 2.0.15. Closing this one now. Thanks for the report and help @shadimanna. 😄
