### ISSUE TITLE
Difficult to find "Product Data > Subscriptions"

### ISSUE THREAD

**Issue by tansaku** [Prospress/woocommerce-subscribe-all-the-things#361]
we were confused by:

> Product Subscription Options

> To add subscription options to a non-subscription product:

> 1.    Navigate to Product Data > Subscriptions.
> 2.    Click Add Option to add subscription options.

A screenshot like:

![](https://dl.dropbox.com/s/3w08xrqrv60af8p/Screenshot%202018-10-16%2011.08.32.png?dl=0)

would have been really helpful

**Comment by thenbrent** [comment]
Thanks for the feedback @tansaku, I've fixed that up with SHA: 826a22c.
