### ISSUE TITLE
Changing wording

### ISSUE THREAD

**Issue by jfinly** [Prospress/woocommerce-subscribe-all-the-things#363]
I'd like to change the wording & font sizes that are added with the plugin. I can't seem to find the file they're housed in.

**Comment by thenbrent** [comment]
@jfinly you're better off not editing the files themselves. To change wording try the free [Say What?](https://wordpress.org/plugins/say-what/) plugin. To change font sizes, you can use CSS in a child theme.

If you're not sure what one or both of those means, get in touch with a developer via http://codeable.io/ and they'll be able to help you out. 🙂

**Comment by jfinly** [comment]
@thenbrent where would I find the text string for (see image)? using the wording generated on the front end does not make any changes using say what.
![screen shot 2018-10-16 at 9 55 31 pm](https://user-images.githubusercontent.com/31748680/47061678-c1fe5800-d18f-11e8-9c6c-a0a1e9812898.png)

**Comment by jfinly** [comment]
![sub text change](https://user-images.githubusercontent.com/31748680/47061686-d3dffb00-d18f-11e8-8071-0b893bfc3ca4.jpg)

**Comment by thenbrent** [comment]
Hi @jfinly, the string you need is `subscribe and get %1$s%2$s`. e.g. http://pic.pros.pr/46f5bdc94bc6

If you need additional help customising the plugin, please find a developer via http://codeable.io/ to help you out, Subscribe all the Things is current not [officially supported](https://github.com/Prospress/woocommerce-subscribe-all-the-things#support), and the _Issues_ here are more for reporting and tracking bugs and feature development.
