### ISSUE TITLE
Remove crossed out prices

### ISSUE THREAD

**Issue by JenniferDesign** [Prospress/woocommerce-subscribe-all-the-things#364]
Hello! Love the product. Client would like to remove the crossed out prices from the two areas. I can't seem to find where that is to remove it. I appreciate your help. Thank you!

![image](https://user-images.githubusercontent.com/44215653/47053335-543b3780-d161-11e8-8161-fafb8dc6eaac.png)

**Comment by thenbrent** [comment]
Hi @JenniferDesign - you can use the `'woocommerce_format_sale_price'` filter.

Subscribe all the Things uses WooCommerce's Sale Price APIs to print that price, and that's where the strikethrough is added.
