### ISSUE TITLE
Switch for monthly/yearly prices? Composite Products

### ISSUE THREAD

**Issue by open7c** [Prospress/woocommerce-subscribe-all-the-things#368]
We got the following structure on a Product Overview Page:

Product A
- 100,-
- Amount

That 100,- is the price per month when payed **yearly**. When payed **monthly** it is ie 200,- per month

How can we setup this scenario:
* on the top of the page are 2 buttons where one can switch between monthly and yearly payment (like the bottom of the page, but this radio buttons have no effect on that page, only in the cart page)
* initial the price on the page should show **100,-**
* or should the product have a price of 1200 (100,- for 12 months) and the discount for yearly-payed would be 50% * 12 (months)? but we want to show only the monthly prices

**Comment by franticpsyx** [comment]
Hey there,

It sounds like you need some help with a specific scenario? I have to admit it's not 100% clear to me how to answer your question as it's lacking some context.

As this tracker is only meant for reporting bugs, I will go ahead and close this issue. Apologies for not being able to assist further!
