### ISSUE TITLE
NYP Compat problem #2: lacking a suggested price results in a blank scheme description

### ISSUE THREAD

**Issue by helgatheviking** [Prospress/woocommerce-subscribe-all-the-things#369]
The second radio should say "Every month" but instead it's a null string b/c NYP filters the price html to show the suggested price. But lacking a suggested price results in a null price string. And a null price string ends up returning early [here](https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/product/class-wcs-att-product-prices.php#L100) when trying to get the scheme price string.

![image](https://user-images.githubusercontent.com/507025/47329478-8275b700-d63a-11e8-8125-39077fd6fe22.png)

**Comment by helgatheviking** [comment]
Looks like I could modify the `$sub_price_html_args` [here](https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/display/class-wcs-att-display-product.php#L124) to force 

```
$sub_price_html_args['subscription_price'] = false;
$sub_price_html_args['product_price'] = false;
```

The question is do you want a product is NYP in the plugin, or do you want a filter there that NYP can hook into?

**Comment by franticpsyx** [comment]
@helgatheviking could you perhaps open a single issue for NYP compatibility and summarize everything there? Closing this one.
