### ISSUE TITLE
Different shipping options for subscribed items

### ISSUE THREAD

**Issue by ClearMarble** [Prospress/woocommerce-subscribe-all-the-things#37]
I'm loving this extension, it really fills a huge gap in Woocommerce functionality. 

I'm wondering is there any way to identify regular items that are converted to subscriptions in cart so you can apply different shipping rules?

With regular WC Subscriptions you'd have to create a whole separate subscription product and could just assign it a shipping class...but naturally that doesn't work for this.

If I wanted to have converted subscription items ship for free...would you have any idea how I might begin to approach that?

I've been playing around with checking the products in the cart and I found that  `WC_Subscriptions_Product::is_subscription()` returns false when I loop through the product id's of converted subscriptions, but oddly enough I found that `WC_Subscriptions_Cart::cart_contains_subscription()` returns true when a converted subscription is present.

Any tips or advice would be greatly appreciated!

**Comment by franticpsyx** [comment]
>I'm wondering is there any way to identify regular items that are converted to subscriptions in cart so you can apply different shipping rules?

@ClearMarble I'd say there are 3 options:

- `WCS_ATT_Schemes::get_active_subscription_scheme_id( $cart_item )`: A returned value other than `'0'` indicates that the cart item has been converted to a subscription.
- `WCS_ATT_Schemes::get_active_subscription_scheme( $cart_item )`: A result other than `false` indicates that the cart item has been converted to a subscription.
- Use `WC_Subscriptions_Product::is_subscription( $cart_item[ 'data' ] )`.

Hope this helps!

**Comment by franticpsyx** [comment]
>I've been playing around with checking the products in the cart and I found that `WC_Subscriptions_Product::is_subscription()` returns `false` when I loop through the product id's of converted subscriptions

Yes, you need to pass the entire product into the function. Using the product id alone, it's impossible to tell what the "subscription state" of the cart item is (use option 3 above). If you want to get even more specific than this and need to get the id of the active subscription scheme, use options 1/2 above.

@thenbrent
