### ISSUE TITLE
Override custom price on month based

### ISSUE THREAD

**Issue by robiul-shagor** [Prospress/woocommerce-subscribe-all-the-things#377]
Hey,
I like your extension, I want to do one thing with your extension, can it possible? 
I want to custom price every month, as like 1st month- $650, 2nd month $450, 3rd month 350.

So the user totally pays a specific amount of money on his total subscription. Right now it will allow the Total amount of money or a specific amount of money per month, But I want to make a custom amount of money per month. Is it possible? Or do you have any Idea about this?

**Comment by franticpsyx** [comment]
Hey @robiul-shagor -- in theory anything is possible, but this isn't something SATT supports out of the box. 

One possible option here would be to work with a developer and have this custom-built for you. As this repository is only meant for reporting SATT bugs/issues, I'll go ahead and close this issue, but feel free to add more details here if needed.
