### ISSUE TITLE
Subscriptions not adding to cart

### ISSUE THREAD

**Issue by banthony29** [Prospress/woocommerce-subscribe-all-the-things#378]
I noticed yesterday that when you select one of my subscriptions it only adds the basic simple or variable product to the cart. When in the cart if you select the product to repeat and hit update basket it does not change.

I have deactivated all my plugins except for; WooCommerce, woocommerce subscriptions & Woocommerce Subscribe all the Things.

I’m not sure why it’s stopped working, it was working fine when I added the plugin a few days ago. I’m have the lastest plugin version 2.1.4

**Comment by franticpsyx** [comment]
Hey @banthony29 

can't replicate this locally, I'm afraid. Here's a demo site running SATT 2.1.4 -- https://somewherewarm.net/satt/product/spicy/ -- no issues there either.

Sounds like a possible conflict with your theme. Could you perhaps try to see if everything works normally using a default WordPress theme, such as Twenty-Seventeen, or Storefront?

**Comment by banthony29** [comment]
Hi @franticpsyx 

Thanks for you super quick response. 

I have activated the Storefront theme and as you said the bug is theme related. I am using Oceanwp, any idea why it would not function correctly, or what I need to ask the developers to do?

Many thanks

**Comment by franticpsyx** [comment]
It's possible that the theme is adding products to cart via ajax -- in this case theme authors will need to make ajax add-to-cart work in a more generic way, e.g. serialize all form fields, post everything and then `parse_str` and merge the de-serialized data in `$_POST`.
