### ISSUE TITLE
Able to change "Every" for other text

### ISSUE THREAD

**Issue by alextovey** [Prospress/woocommerce-subscribe-all-the-things#381]
Hi,

Are we able to change the wording "Every Week" or "Every 2 weeks" to append "Send" before hand?

Tried to check the files but cant find the line to add an option in it.

**Comment by thenbrent** [comment]
You can try the fee _Say What_ plugin. If that isn't enough, a developer from https://codeable.io/ will be able to help you out. :)

**Comment by alextovey** [comment]
Okay this can be done by editing the "Subscription" plugins pot file and creating a po and mo file.
