### ISSUE TITLE
Question: Is it possible

### ISSUE THREAD

**Issue by alextovey** [Prospress/woocommerce-subscribe-all-the-things#382]
Is it possible to change the radio buttons to a drop down as it makes the basket massive if they have lots of products and on the mobile its stupidly long.

Also where can i add echo 'Send my order' i want it to appear above or before each option for instance if the drop down works then Send my Order (dropdown with options)
Or if not then above the options Send my order and the options below.

**Comment by thenbrent** [comment]
Hi @alextovey, a developer from https://codeable.io/ will be able to help you with these customisations.

**Comment by alextovey** [comment]
> Hi @alextovey, a developer from https://codeable.io/ will be able to help you with these customisations.

What about the dropdown because on the mobile if they are adding a few products it makes the list massive. Maybe adding it as a "Feature" would be a good idea.

**Comment by alextovey** [comment]
@franticpsyx is it possible to make the radio buttons dropdown. As on mobile google is ranking radio buttons on the next release a bad thing and moving everyone to dropdown buttons.
