### ISSUE TITLE
Problem: Discount rules not being applied on renewals

### ISSUE THREAD

**Issue by alextovey** [Prospress/woocommerce-subscribe-all-the-things#383]
Running all the lastest versions of wordpress + Woocommerce.

We use Vartech Pricing & Discounts pro and it picks up the discount fine on the initial cart but renewal it does not give the re occuring discount as it should. 

For instance we have a 3 for £10 discount so a customer add's 3 £4 items and then it discounts but is there a way to discount on the re occuring also or at least pickup on the discount?
Happy to give access to our staging site to test and confirm.

**Comment by NickGreen** [comment]
https://secure.helpscout.net/conversation/703500268/19420/

**Comment by alextovey** [comment]
:| i dont have access to that one i'm afriad.

**Comment by franticpsyx** [comment]
@alextovey just did some tests to check if native scheme discounts work as expected when renewing -- they do.

If this is only an issue with "Vartech Pricing & Discounts Pro", then I'm afraid there's little we can do here to help. 

Subscribe All The Things is already heavy on the dependencies side of things -- third-party plugins/extensions cannot be explicitly supported. Please remember that it's rarely possible to make two plugins "play nice" with each other by writing code on one side -- so a decision to introduce compatibility between two plugins usually requires opening a channel of communication between two sides and keeping it open for the foreseeable future. It's not a decision to be taken lightly.

If there's a small tweak/change we can make to make SATT compatible "Vartech Pricing & Discounts Pro", we'd be happy to consider it.

Thanks for understanding! Will close this one for now but feel free to add further details if needed.
