### ISSUE TITLE
add to cart with subscription option or update cart item with subscription option in custom page

### ISSUE THREAD

**Issue by stevechoi** [Prospress/woocommerce-subscribe-all-the-things#388]
Hi. We have Woocommerce variable product and bundle product, and want to add these products to cart with 'subscribe all the thing'`s subscription option like '2_weeks' or '3_weeks' in our custom page but I cannot find how to do that.

Is there a proper way?

I tried to do following methods.

1.  $cart_item_key = WC()->cart->add_to_cart(11121, 1, 11151);
=> Item is inserted in cart. (is there way to set subscription option in this add to cart step?)

2. WC()->cart->cart_contents[ $cart_item_key ][ 'wcsatt_data' ][ 'active_subscription_scheme' ] = '5_week'; 

=> item's subscription option in cart not changed. 

Thanks.

**Comment by franticpsyx** [comment]
The approach seems right, but is `5_week` a valid key?

See https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/class-wcs-att-cart.php#L247 and https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/product/class-wcs-att-product-schemes.php#L314
