### ISSUE TITLE
Question: Which discounts plugin works

### ISSUE THREAD

**Issue by alextovey** [Prospress/woocommerce-subscribe-all-the-things#389]
Which discount pricing plugin works with this plugin? 

Looking for plugins to do bulk discounts say 3 items @ £4 for £10 etc. Grouped by categories. :) 

Any one know which ones looking for ones i can get through code canyon if possible as i've got credits there.

**Comment by franticpsyx** [comment]
Hey @alextovey -- we have no recommendations to share here, I'm afraid. SATT is only guaranteed to work with WooCommerce Subscriptions and a small list of officially supported extensions, see https://github.com/Prospress/woocommerce-subscribe-all-the-things#woocommerce-subscribe-all-the-things

No third party discount plugins have been tested with SATT or can be supported at this time.
