### ISSUE TITLE
Simple Product, Single Sub Option, Forced Subscription

### ISSUE THREAD

**Issue by seb86** [Prospress/woocommerce-subscribe-all-the-things#39]
![Simple Product, Single Sub Option, Forced Subscription](https://cldup.com/a01tvwE-ov.png)

@franticpsyx Found another bug... I think. Could you check to see if this is correct and if you get the same?

I created a new simple product and only added one subscription option with a price override of 50 and enabled force subscription. Nothing else.

No "Add to Cart" button shows.

**Comment by franticpsyx** [comment]
@seb86 Thanks for reporting this.

It's a known issue that I've come across quite often in the past: WooCommerce products need to have a non-empty price set. There is a core limitation in the cart class where a product is checked using `is_puchasable()` before session data can be overridden. Therefore, even if we filter the output of `is_purchasable()` to avoid this issue, adding to cart will still fail.

**Comment by seb86** [comment]
@franticpsyx What if when the product is saved, if these conditions are met, then we set the regular price on the product level as zero. That way WooCommerce thinks that the original regular price of the product is free allowing the item to be added to the cart and for the price override to do its job.

![Regular Price set to Zero](https://cldup.com/KFevSPmFGN.png)

**Comment by franticpsyx** [comment]
>then we set the regular price on the product level as zero

We could consider that, yes. The `price` meta is also used to show Price Filter Widget results, so we could generalize your idea and look at the "cheapest scheme" price (there's already a function for that), then set the regular price based on that, if empty.

**Comment by seb86** [comment]
@franticpsyx Sounds like a plan.

**Comment by franticpsyx** [comment]
Leaving open. Considered as low priority.

**Comment by seb86** [comment]
@franticpsyx I have addressed this in this commit  342cf14d7a87789d3b00f4c0e9385ebb6d82bf8a

**Comment by franticpsyx** [comment]
Better open separate PRs for different things - but I'm happy to keep that in #49 for now. Thanks!

**Comment by seb86** [comment]
@franticpsyx OK
