### ISSUE TITLE
Perfomance

### ISSUE THREAD

**Issue by Camilo517** [Prospress/woocommerce-subscribe-all-the-things#390]
Hello, this loads in all the pages
http://wp-content/plugins/woocommerce-subscribe-all-the-things-master/assets/css/wcs-att-frontend.css?ver=2.1.4

In my case I only use the plugin on the cart page

I used this plugin
https://es.wordpress.org/plugins/plugin-load-filter/
  and I have configured it so that it only loads in the cart, but shows errors
![descarga 1](https://user-images.githubusercontent.com/43606394/48969560-9c6f3480-f000-11e8-8a1c-a1e68940aad0.png)

Could you add something so that it only loads when necessary? Thanks :)

**Comment by franticpsyx** [comment]
Hey @Camilo517 -- this file doesn't only include cart styles. Eventually, it might be best to split it up and load the different parts conditionally, but at this point I'm afraid you will need to dequeue it by writing custom code.

This repository is only meant for reporting bugs -- we are not able to help with customizations or modifications like this. For WordPress/WooCommerce customizations, I highly recommend <a href="https://codeable.io/">https://codeable.io/</a>. Many Codeable Developers have a spotless track record with WordPress/WooCommerce customizations of this scale.
