### ISSUE TITLE
Mix & Match not working

### ISSUE THREAD

**Issue by maddinq** [Prospress/woocommerce-subscribe-all-the-things#397]
I can't see subscriptions options on mix&Match products at all - maybe a missconfiguration or isn't it implemented with the latest Version 2.1.4?

**Comment by franticpsyx** [comment]
Hey @maddinq 

Have you by any chance enabled **Per-Item Pricing** for that MnM product?

Per-item priced MnM products are unsupported due to some MnM limitations. As a workaround, you could use Product Bundles (PB) in combination with the free [Min/Max Items](https://docs.woocommerce.com/document/bundles/bundles-mini-extensions/#section-2) mini-extension, which adds pick-and-mix functionality to Product Bundles.

**Comment by helgatheviking** [comment]
@maddinq If you submit a [support ticket](https://woocommerce.com/my-account/create-a-ticket/) I can make sure you get refunded for your purchase of MNM. And I'll be sure to improve the docu to include the per-item pricing limitation. Sorry for the confusion and disappointment.

**Comment by maddinq** [comment]
Hi Guys, 
do you see any chance that this per-item pricing plus subscription will be re-implemented again soon?

BR
Martin

**Comment by helgatheviking** [comment]
@maddinq As of Mix and Match 1.4 you can re-implement per-item pricing plus subscriptions via the bridge plugin I wrote here: https://github.com/helgatheviking/wc-mnm-satt-bridge I can't say when/if that will be rolled into SATT itself.

**Comment by maddinq** [comment]
Hi Kathy

two notes:

1) with Mix&Match for some reason I’m getting two times the single-item-price (this is not your fault)

but 
2)
The total is calculated right…unfortunately the offers for the different subscripts are static 
- any idea about this ?

**Comment by helgatheviking** [comment]
@maddinq 
1. Most likely you added the price via a custom snippet in your theme (or possibly a custom snippets plugin) as that's what was required for displaying the price in versions prior to 1.4.0. Now the price is displayed automatically for products in per-item pricing mode. So you can safely remove your custom snippet and that should resolve the duplicate price display. 

2. Can you clarify " the offers for the different subscripts are static" I'm not sure what you mean?

**Comment by maddinq** [comment]
https://nuriforbabies.de/shop/individuelle-brei-box-kopie/ <https://nuriforbabies.de/shop/individuelle-brei-box-kopie/>

Password: testonly

please add in total 9 products (quantity)… you see the total is calculated correct.
But the subscription prices is always the same (static 37,80€ (so the lowest possible price)…but it should be the 
1) total - 10%
2) total - 12%
3) total - 15%

**Comment by helgatheviking** [comment]
Ah ok. Looks like I forgot to update the plugin for the final tweaks I made to 1.4.0. I think it's resolved by the latest commit, so try pulling down the latest master (v1.0.1)
