### ISSUE TITLE
force reload page

### ISSUE THREAD

**Issue by neoseeyou** [Prospress/woocommerce-subscribe-all-the-things#399]
Hello and happy christmas/new year to you

I have a question about refreshing cart: Is it possible when you want to subscribe to the cart to reload the cart page completly (without using ajax to refresh it?) .

Thank you

**Comment by franticpsyx** [comment]
Hey @neoseeyou 

Thank you, we're happy you found SATT useful! 

This repository is only available for reporting bugs, so you might need to work with a WordPress/WooCommerce developer to build these customizations for you. For WordPress/WooCommerce customizations of this scale, we usually recommend <a href="https://codeable.io/">https://codeable.io/</a>.
