### ISSUE TITLE
Cart Subscription Options don't show up

### ISSUE THREAD

**Issue by dverma1232** [Prospress/woocommerce-subscribe-all-the-things#400]
The cart subscription options don't show up, I have followed the instructions and have setup 2 options in the settings. I'm adding a variable product to the cart.

**Comment by dverma1232** [comment]
I'm using the flatsome theme, cart and checkout are 2 seperate pages.

**Comment by treitnauer** [comment]
I'm having the same issue. Changed a few times between a WooCommerce variable subscription and SATT, and remember that it worked at the very beginning but don't see the option to subscribe to the whole cart anymore.

**Comment by franticpsyx** [comment]
Hey all, I'm not able to replicate any issue here. Sounds like a theme conflict?

* Got to https://somewherewarm.net/satt/product/cinnamon/
* Add the product to cart
* Go to the cart page
* Cart subscription options appear to work
