### ISSUE TITLE
How to hide subscription otions from category page

### ISSUE THREAD

**Issue by mauzundwauz** [Prospress/woocommerce-subscribe-all-the-things#401]
Hi there,

how can I hide the text showing "subscribe and get %1$s%2$s" in the product category overview. I just want to show it on the detail product page, but not on the product overview page.

Thx in advance,

Thomas

![03-01-_2019_16-35-55](https://user-images.githubusercontent.com/7295356/50646182-c0b21f80-0f75-11e9-8d25-836a16c42b0a.jpg)

**Comment by franticpsyx** [comment]
Hey @mauzundwauz 

This repository is only available for reporting bugs, so you might need to work with a WordPress/WooCommerce developer to build these customizations for you. For WordPress/WooCommerce customizations of this scale, we usually recommend <a href="https://codeable.io/">https://codeable.io/</a>.
