### ISSUE TITLE
Adding Subscription to Product bundles with Woo Memberships

### ISSUE THREAD

**Issue by afaqk9394** [Prospress/woocommerce-subscribe-all-the-things#403]
Hi there

I am using Subscribe All Things plugin on a Product bundle (created via Woo product bundle plugin) along with Woo subscription and membership plugins. I have two subscription options added to my product bundle, one that allows bundle purchase with 3-month and one with 6-month subscriptions.

However, I can't find a way under Woo Memberships configuration, and more specifically, under Woo Memberships -> add new membership -> Products field when adding new Memberships, an option to add Subscribe-All-Things subscriptions (i.e. 3 and 6 month options). This means that I can't tie membership to a Subscribe-All-things subscription, and assign 3 or 6 months duration depending on the actual subscription chosen by the customer at the time of purchase.

I am not sure if that is expected to work or not, but it would be awesome to add Woo Memberships integration to Subscribe-All-things so subscriptions purchases can be easily tied to respective Memberships.

**Comment by franticpsyx** [comment]
Hey @afaqk9394 -- see https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/396#issuecomment-450449326

In short, we'd love to support Memberships at some point, the "special" position of SATT forces us to be very cautious about which (and how many) extensions we work to make compatible with it. As SATT is by nature a "bridge" plugin, the onus is always going to be on _us_ to patch SATT every time a "supported" extension gets updated -- and this may quickly get out of hand. At the moment there is no schedule or ETA for Memberships support.
