### ISSUE TITLE
Product Bundles with "price individually" shows as $0 when buying once

### ISSUE THREAD

**Issue by brycehamrick** [Prospress/woocommerce-subscribe-all-the-things#404]
When the bundle itself doesn't have a price and "Price individually" is enabled on each of the bundled products, the discounted subscription price shows up accurately but the "Buy once" option shows up as $0. It appears correct in the cart, it's just on the product details page that it's wrong.

**Comment by brycehamrick** [comment]
Temporarily getting by with this filter, but it's definitely a hack. Need a more long term solution.

```
add_filter( 'wcsatt_single_product_options', 'custom_single_product_options', 99, 3);
function custom_single_product_options($options, $subscription_schemes, $product) {
  if ($product instanceof WC_Product_Bundle)
    $options[0]['description'] = 'Buy once for <span class="price"><ins><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">$</span>' . $product->get_bundle_price() . '</span></ins></span>';
  return $options;
}
```

**Comment by franticpsyx** [comment]
Hey @brycehamrick -- could you provide some more details about this? Is there a live/staging website we could look at, or maybe a screenshot or two?

I'm not able to replicate this locally -- https://cl.ly/1fcd20269a32

More specifically, the option you are referring to does not have a price -- it reads "None".
