### ISSUE TITLE
Adding Subscribe All Things to custom product types?

### ISSUE THREAD

**Issue by pat1121** [Prospress/woocommerce-subscribe-all-the-things#406]
I'm trying to use an inventory managment tool called ATUM, which creates custom product types allowing me to track my inventory. However when I switch over to the custom product type, it removes my sub all things options.

Is there an easy fix for adding product types that this will work with? The product type literally only changes my tracking in ATUM so I can track individual, case, and bundle type products to include the correct inventory items.

Thanks!

**Comment by afaqk9394** [comment]
Hi Team,

Can you please address this question? anyone home?

**Comment by franticpsyx** [comment]
Hey @pat1121 -- I'm afraid there is no generic way to add support for "any" product type predictably. FWIW, an inventory management tool probably shouldn't require/enforce a custom product type.

**Comment by pat1121** [comment]
Thanks for getting back to me. While I agree with you, it's the only tool that appears to work with our setup of many bundled / case / individual products to reliably track what we've got in our warehouses. I believe I came up with a workaround at the moment, it just isn't elegant :)
