### ISSUE TITLE
Error when trying to add cart to existing subscription (expects array, string given)

### ISSUE THREAD

**Issue by giulianorapoz** [Prospress/woocommerce-subscribe-all-the-things#407]
Hi SATT,

Testing out the add entire carts to existing subscriptions and getting this error once I select the existing subscription on the cart page and click on **Add+**?

I have created a staging site where I have deactivated all other plugins and remove all custom code, however the error is still triggering. I'm not sure how to go about debugging this now?

Using SAAT Version: Version 2.1.4
Woo Subscriptions Version: 2.4.3
Woocommerce Version: 3.5.1
Wordpress Version: 4.9.8

![image](https://user-images.githubusercontent.com/30539010/51252056-bc80fb80-1992-11e9-856f-b67b98bd98f5.png)

> **Warning**: current() expects parameter 1 to be array, string given in **/home/protein4/public_html/wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/modules/management/class-wcs-att-manage-add.php** on line **239**

> **Fatal error:** Uncaught Error: Call to a member function get_cart() on null in /home/protein4/public_html/wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/modules/management/class-wcs-att-manage-add.php:247 Stack trace: #0 /home/protein4/public_html/wp-includes/class-wp-hook.php(286): WCS_ATT_Manage_Add::add_cart_to_subscription(Object(WC_Subscription)) #1 /home/protein4/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #2 /home/protein4/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /home/protein4/public_html/wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/modules/management/add/class-wcs-att-manage-add-cart.php(253): do_action('wcsatt_add_cart...', Object(WC_Subscription)) #4 /home/protein4/public_html/wp-includes/class-wp-hook.php(286): WCS_ATT_Manage_Add_Cart::form_handler('') #5 /home/protein4/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #6 /home/protein4/public_html/wp-includes/p in **/home/protein4/public_html/wp-content/plugins/woocommerce-subscribe-all-the-things-master/includes/modules/management/class-wcs-att-manage-add.php** on line **247**

**Comment by franticpsyx** [comment]
@giulianorapoz 

Hey thanks for reporting this! This should be fixed in `master`, could you please check and confirm? Thanks!

**Comment by giulianorapoz** [comment]
Hi @franticpsyx , Thank you very much for looking into this and issuing a fix! I can confirm that it is working in latest master build 2.1.5-dev
