### ISSUE TITLE
singup fee + recurring fee

### ISSUE THREAD

**Issue by SundayDriver** [Prospress/woocommerce-subscribe-all-the-things#408]
loving this plugin but customers are taking advantage of the system. We offer a 10% discount for subscribing, but they cancel their subscription after the first order. 

How can we offer the 10% discount only to renewals?

**Comment by thenbrent** [comment]
@SundayDriver good question. You could use AutomateWoo and the [Add Coupon action](https://automatewoo.com/docs/actions/subscription-add-remove-coupon/) to create a workflow which provides the customer with the discount after they've signed-up.

Alternatively, you could get some custom code based on the [Renewal Only Coupon](https://github.com/Prospress/woocommerce-subscriptions-renewal-only-coupon) plugin that more accurately fits your use case.
