### ISSUE TITLE
Not showing extended total on Cart page

### ISSUE THREAD

**Issue by eli0086** [Prospress/woocommerce-subscribe-all-the-things#409]
I just installed Woocommerce v3.5.3 and Subscribe all the Things v2.1.4 and the extended total seems to be missing on the cart and checkout pages. When I deactivate the plugin, it shows up again.  The issue seems to be only when the option of "one time" purchase is selected.  When I select a monthly subscription, the extended price shows.  This just started happening with newest updates. 

I've also tried deactivating other plugins and testing theme issues... seems to only be when the plugin is activated.

Please see the screenshots provided:

Cart Screenshot:
https://cl.ly/d418c939faac

Checkout Screenshot:
https://cl.ly/74e750bf0741

URL this is happening:  https://www.marigoldbars.com

Any help would be greatly appreciated to be able to fix this issue.  Thanks!

**Comment by eli0086** [comment]
I have now with additional testing found that this issue is caused by a conflict with the Woocommerce Product Bundles plugin.  If the product is a product bundle, this issue occurs. As soon as I convert it to a simple product, the issue clears.  

Trying to determine what the conflict with Product Bundles could be....

**Comment by eli0086** [comment]
Perhaps this issue has been here for awhile and I just didn't catch it until now. I've tried rolling back several versions on Woocommerce, Subscribe All the Things, and Product Bundles without being able solve the issue.  Those three plugins are definitely the source, but I can't figure out where the problem is.

**Comment by eli0086** [comment]
Great, thanks for reviewing and finding the issue. Looking forward to the update and the possible new distribution model for this plugin. I wish this plugin was in the core of the Subscriptions plugin! So useful...

**Comment by franticpsyx** [comment]
Hey @eli0086 -- this should be fixed in `master`. Could you please test and confirm? Thanks!

**Comment by eli0086** [comment]
Looking good! Thank you for fixing this bug so quickly. I greatly appreciate it!
