### ISSUE TITLE
Shipping classes depending on subscription

### ISSUE THREAD

**Issue by benjaminmoquet** [Prospress/woocommerce-subscribe-all-the-things#411]
WC Subscriptions has the option to choose shipping class on each variation. In our case, we have different subscription (1, 3, 6, 9, 12 months) and we wish to offer shipment if the customer choose 6 month subscriptiokn or higher.

Could it be possible with SATT?

**Comment by benjaminmoquet** [comment]
we are trying to use SATT with product bundle.

**Comment by franticpsyx** [comment]
Hey @benjaminmoquet

I can't think of a way to do this. I would have recommended the [Conditional Shipping and Payments](https://woocommerce.com/products/conditional-shipping-and-payments/) extension for this, as it allows you to conditionally exclude Shipping Methods depending on the chosen subscription **period** -- however CSP **doesn't support intervals at the moment**.

I'm afraid I can't think of a way to do this -- you could develop a custom solution, of course, by dynamically assigning shipping classes to cart items on session load, and then set up some shipping-class-based rules in CSP.
