### ISSUE TITLE
Subscription and Subscribe to All Things - Functionality Discrepency

### ISSUE THREAD

**Issue by Goldendust20** [Prospress/woocommerce-subscribe-all-the-things#414]
Hi there! I'm using your Subscription plugin with the Subscribe To All Things extension, and so far it's doing nearly all of what we were hoping it would, thanks!

We ran into an issue with the functionality allowed in Subscriptions that isn't available in STAT extension and were curious if you could add it in.

We are using the plugin Points and Rewards for WooCommerce and would like to give people DOUBLE points if they sign up for a subscription. According to the documentation this is something we can by adding 200% points to the subscription plugin input settings (see document for section #5).

****However***** This option is not available if we use STAT like it is in the regular Subscription plugin, so while we could accomplish this using the Subscriptions plugin, we don't get a "one time purchase" option. If we use the STAT plugin to get the "one time purchase" option, we lose the ability to add a subscription points to the product item.

Is there any way you guys could add this functionality to the STAT like you have it in the Subscriptions plugin? If so (thank you!) do you have an ETA as to when we might see this?

Thank you!

How to apply double points to subscription item: https://docs.woocommerce.com/document/woocommerce-points-and-rewards/#section-5

**Comment by Goldendust20** [comment]
Oh Jeez, 
Also - I don't want the default "add to cart" button to "Add subscription product", I feel like this is going to anger customers who simply want to purchase one time. How can I set the button default for an item to just add the item to cart WITHOUT item + subscription.

Thank you.
![this-should-not-add-subscription-product-by-default](https://user-images.githubusercontent.com/13838627/51940024-856d0a00-23d6-11e9-8306-595a0fae463a.png)

**Comment by Goldendust20** [comment]
(I removed the Select Option button for now on all products to force users to the single product view page to avoid this auto subscription from happening, but would like to add it back ASAP functioning correctly as a single product being the default selection).

**Comment by franticpsyx** [comment]
Hey @Goldendust20 

> Is there any way you guys could add this functionality to the STAT like you have it in the Subscriptions plugin? If so (thank you!) do you have an ETA as to when we might see this?

Thanks for sharing this feedback with us! While I can definitely see how this would help in your case, it's not something that we can prioritize in the short term. In the last few years that the plugin has existed, we haven't received any requests for a Points & Rewards integration.

> How can I set the button default for an item to just add the item to cart WITHOUT item + subscription.

This repository is only available for reporting bugs, so you might need to work with a WordPress/WooCommerce developer to build these customizations for you. For WordPress/WooCommerce customizations of this scale, we usually recommend https://codeable.io/.

For reference, here's the part of the code that's involved with this:

https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/display/class-wcs-att-display-product.php#L42-L46
