### ISSUE TITLE
SATT Products API

### ISSUE THREAD

**Issue by franticpsyx** [Prospress/woocommerce-subscribe-all-the-things#42]
### Objective

Currently, most logic and data needed for "converting" `WC_Product` objects to subscription-enabled objects are scattered all over the place, for instance:
1. scheme data is only accessible from post meta, while 
2. the active subscription scheme id is stored only in the cart item array
3. subscription details are stored as object properties by WCS

(1) and (2), as well as all associated logic for "converting" a product to a subscription in the cart is currently implemented using static functions, simply organized in suitably named classes.

Obviously, we need a more formal, object-oriented way to: 
- manage the subscription schemes available with a WC product, 
- access its subscription status/details (regardless of its type) and 
- convert its subscription state,

not only in cart context, but in a way that's more tightly integrated with the `WC_Product` class.
### Ideal Case

Ideally, if this would all be part of WC core, the Abstract Product class would include properties and methods to handle the "Subscription Nature" of a product internally, and set any properties associated with it (billing periods, intervals, trial, prices, sign up prices, etc) when converting from/to a non-recurring billing state to a recurring one.

This would allow a product to freely switch between states, while existing methods could ideally take this into account and modify their output, for instance:
- `get_price` and other price getters could modify the returned value depending on the price(s) associated with the active scheme, if set, otherwise return the standard non-recurring (one-off) price.
- `get_price_html` could try to generate an output based on the active subscription (if set), otherwise return something meaningful based on a stored `min_price_subscription_scheme`.

From a cart perspective, this core-embedded handling would allow WC to set the active subscription scheme with the item session data, and "convert" it when instantiating the product class, similar to how products are instantiated using their `product_id` alone - only we'd have an additional `subscription_scheme_id` to pass to the constructor.

From an order perspective, `get_product_from_item` would use a similar method to instantiate the object using a `subscription_scheme_id` field stored in the line item.

This would allow products to have a _dual_ nature - the Subscription and the Product, distinct from one another but unified in the same object.

(Do we agree with this as a utopian solution to start with?)
### Possible Solutions

What's the closest we can get to our Utopia, if we agree we accept it as such?
- Somehow dynamically add properties and methods to all instantiated products on init. If PHP was JS, we would have likely intervened with the Abstract Product prototype, or appended "methods" and "properties" at some point during run time. I don't think we have this option.
- Rely on our ability to dynamically add properties to the Abstract Product (magic methods are already there). Use a separate object to manage the Subscription nature of the product, possibly embedded in every product instance as a property (we'll need a `wc_get_product` filter to do this), or follow a "hybrid" approach, with static functions under a `WCS_ATT_Product` class accepting the product as a parameter with all "Subscription"-related data stored as properties of the WC product object (much like how WC Subs does it, I think?).
- Instead of adding properties to existing WC Product objects, somehow come up with a way to "wrap" the WC Product objects into a new `WCS_ATT_Product` object on instantiation, and then 1) add all management logic on the wrapper and 2) override the behaviour of existing product methods at will, possibly depending on the type of the wrapped product. I have just started to explore the idea in https://github.com/Prospress/woocommerce-subscribe-all-the-things/tree/oop - it's far from being implemented to actually do the heavy-lifting, but the "wrapping" idea seems to be a viable workaround (unless I am missing something). There are some caveats, for instance if you have code relying on things like the `instanceof` an instantiated WC product I suspect lots of things might break. Similarly, we might have issues with cloning of such products.

The advantage of the 1st (impossible with PHP?) and 3rd solutions is that we can do away with the need to declare filters in order to change the output of WC product methods, since the wrapper object operates as a filter always firing last, which is what we want here. The `oop` branch explores this concept by embedding `get_price_html` into the wrapper object.

We are still some distance away from the Utopia, in the sense that we'll still need to "manually" call methods on our wrapper object when cart session data has loaded, in order to set the object subscription state and use `get_product_from_item` to do the same with products instantiated from order items. But overall, the "wrapper object" solution is a possible way to unify the Subscription + Product natures in a true OOP manner.
### Scheme Storage

We currently store schemes as serialized meta, which is probably far from ideal. One solution we could explore is to use a custom post type for this, possibly also using the `parent_id` db field to point to the product id that a subscription scheme belongs to. All scheme data, such as billing details, prices and other options could be stored as post meta of the new `subscription_scheme` post type.

@thenbrent

**Comment by franticpsyx** [comment]
>I have just started to explore the idea in

See https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/oop/includes/class-wcsatt-products.php and https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/oop/includes/class-wcsatt-product.php to get an idea of the concept.

>The advantage of the 1st and 3rd solutions is that [...]

No matter which method we choose, 1, 2a, 2b, or 3, we'll need to agree on an interface that our new object will implement. Not that hard, since what we need is basically a getter for the scheme data (and possible a `WCS_ATT_Subscription_Scheme` with its own methods, rather than an array), a setter for the subscription scheme id (subscription state), and a couple more things it's too early to list here.

**Comment by franticpsyx** [comment]
@thenbrent Did you have a chance to take a look?

I still find the wrapper to be an interesting idea, it seems to introduce an extra load time overhead in all pages with products, but I haven't checked XDEBUG to see exactly where it's coming from. I am suspecting that the use of magic methods in the wrapper class ( https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/oop/includes/class-wcsatt-product.php ) could be a reason, need to double check that, though.

On that note, Subscriptions is a quite heavy plugin. Disabling it seems to yield a significant improvement in page loads across the board. SATT branch `oop` seems to be a bit on the heavy side, but not to the point where I'd treat it as a major issue, at least not with PHP 7 in the horizon.

**Comment by thenbrent** [comment]
@franticpsyx sorry not yet. I'll try to make some time next week or the week after. It's still on my todo-list, but final Subscriptions v2.1 todos are getting priority atm.

> On that note, Subscriptions is a quite heavy plugin. Disabling it seems to yield a significant improvement in page loads across the board.

Yeah, we've doing a lot of work on performance the last few months (some improvements already released, some not coming until v2.1, and some possibly not coming until v2.2 or maybe never, see: https://github.com/prospress/woocommerce-subscriptions/issues?utf8=%E2%9C%93&q=label%3Aperformance%20)

**Comment by thenbrent** [comment]
Hey @franticpsyx, I've finally made some time to review/think about this, especially the changes in the OOP branch: https://github.com/Prospress/woocommerce-subscribe-all-the-things/compare/oop

The concept of forcing all products to be instantiated via `WCS_ATT_Product` is equal parts brilliance and madness. 😆 

I like the concept of being able to control the objects used for all products, but I imagine this type of black magic would break so many different things with 3rd party code. For example, any check on `is_a( $product, 'WC_Product' )` would fail if SATT was active. A [quick search of GitHub](https://github.com/search?q=is_a%28+%24product%2C+%27WC_Product%27+%29&ref=simplesearch&type=Code&utf8=%E2%9C%93) shows that check is not uncommon.

Similarly, SATT would be incompatible with any code that instantiates products directly (e.g. `$product = new WC_Product($post_id)`) rather than through the `wc_get_product()` function.

The final issue that jumps out is that it really introduces a finality for the product code by doing this. We still honour the product's methods etc. (which is the brilliant), but there's no way for 3rd party code to work with SATT on the instantiated class, we just say it's going to use ours and too bad if you wanted to do something else (that may never matter given that it honours the product class originally, but it's still something to keep in mind).

You'd probably know better than me what other impact this could have, having worked so extensively with products for Bundles etc. But to me, those are three big issues that immediately jump out as reasons not to use that approach.

I'm not sure I'd continue down that road. It's perilous to say the least.

> Objective

> Currently, most logic and data needed for "converting" WC_Product objects to subscription-enabled objects are scattered all over the place, for instance:

Unifying the logic is part of the objective. It can be achieved without OO though, for example, we could just split some of the classes up into smaller classes, like having a `WCS_ATT_Schemes` base class which has `WCS_ATT_Schemes_Cart` and `WCS_ATT_Schemes_Product` children. 

But another major objective for this was to try to come up with a way to get access to all of a subscription product's features, like one-time shipping, synchronised renewal dates, limiting etc., without having to rebuild UIs etc. to add those to SATT schemes/products.

I can't really see a clear way to achieve that through re-architecting SATT. It may instead involve refactoring a lot of code in Subscriptions itself to make those features more reusable.

We have talked a little internally about making some of features use a base class, or at least an interface, which may help, because then SATT could leverage that uniformity. But I'm really not sure how that would look.

> Scheme Storage

> We currently store schemes as serialized meta, which is probably far from ideal.

Yeah this is a tough one, especially given the above consideration of trying to make sure however we store things connects to how additional features work in Subscriptions. I'm not sure a CPT really fits, given we'd probably end up just using it for an ID to link post meta too. It is possible to use a customer table, but again, ideally, we'd use something that is shared across both Subscriptions and SATT (although it would be a pretty hard justification to make subscription products use a custom table rather than just post meta).

I think that is actually the root of the issue: we're trying to unify two disparate systems. One is the use of subscription products, one if the application of subscription meta to _any_ product. They sound similar but in practice are very different.

A fairly crazy idea that would solve the disparity: perhaps we should make subscription schemes core behaviour in a future version of Subscriptions (i.e. v3.0), and remove the concept of subscription product types altogether. We could easily replace existing simple subscription, variable subscription and subscription variation product types, with equivalent WC core product types with an appropriate subscription scheme. Then we'd just have to update the other subscription features to work like that, and they'd also apply to all other product types.

For now, that makes the most sense to me to address these issues.

**Comment by franticpsyx** [comment]
>You'd probably know better than me what other impact this could have, having worked so extensively with products for Bundles etc. But to me, those are three big issues that immediately jump out as reasons not to use that approach.

Good points against that approach. My thinking was the all the issues *could* be weighted against the benefits to consider this as a possible solution, especially, since I couldn't find any obvious issues with WC core and Subs.

>Unifying the logic is part of the objective. It can be achieved without OO though, for example, we could just split some of the classes up into smaller classes, like having a `WCS_ATT_Schemes` base class which has `WCS_ATT_Schemes_Cart` and `WCS_ATT_Schemes_Product` children.

My main point was to outline that at the very least, I would like us to have a way to maintain the Sub state of a `WC_Product` in every instance. The problem right now is that a "bare" product instance has no subscription state, which means that we need to know in which context it was instantiated (cart? order? other?) and then attempt to get its subscription state from somewhere else (cart item, order item...), which I find rather frustrating.

This would allow us to pass only the product instance into the "sub scheme/state" methods - so, for example, we'd have a single `WCSATT::get_active_subscription_scheme_id( $product )` instead of having cart & order versions of it.

Currently, `WCS_ATT_Schemes` is littered with `get_post_meta` calls, and if you have a look at the different functions and args, you'll see that some of them are meant to operate on cart items, and some on products. I think I'd rather modify those to accept product instances as their args, to allow using the `WCS_ATT_Schemes` API in cart, product, and order context.

The then sub state can be set on every instance. In the cart, this could take place during session load, while `get_product_from_item` would be a good place to set the sub state of a product instance based on saved order item meta.

>Unifying the logic is part of the objective. It can be achieved without OO though, for example, we could just split some of the classes up into smaller classes, like having a `WCS_ATT_Schemes` base class which has `WCS_ATT_Schemes_Cart` and `WCS_ATT_Schemes_Product` children.

How would this splitting-up help? 
Im my mind, the sub state of a product is a property that we set:

- either in "purchasing" context (cart, order)
- or in "probing" context when there is no known/final sub state to speak of.

So the context doesn't (shouldn't) really matter. The sub state is either **set** or **undefined** and a product either has or doesn't have subscription options attached to it: 

In all cases we have some methods dependent on the sub state (id) whose output needs to vary in response to that. Examples:

- `get_price`
- `get_price_html`
- `WC_Subscriptions_Product::get_trial_length`
- `WC_Subscriptions_Product::get_interval`
- ...

>I think that is actually the root of the issue: we're trying to unify two disparate systems. One is the use of subscription products, one if the application of subscription meta to any product. They sound similar but in practice are very different.

>A fairly crazy idea that would solve the disparity: perhaps we should make subscription schemes core behaviour in a future version of Subscriptions (i.e. v3.0), and remove the concept of subscription product types altogether. We could easily replace existing simple subscription, variable subscription and subscription variation product types, with equivalent WC core product types with an appropriate subscription scheme.

+1, especially since Subs v2+ doesn't really enforce a strong coupling between product types and subscription objects.

If you think about it, WCS is now saving the subscription state as a bunch of product properties, assuming that a product **is** or **is not** a subscription product at all times. If it is one, the properties are set on the object:

https://github.com/Prospress/woocommerce-subscriptions/blob/master/includes/class-wc-subscriptions-product.php#L21

SATT is an extension of this: 

Every product can have one (or none) of multiple available subscription states, which are indexed in a `->subscription_schemes` property by an id. The current state is represented by another property, perhaps `->active_subscription_scheme_id`. Each scheme may have a different trial period, set up fee, interval options, etc, but a different **price** as well.

The product type is not relevant anymore.

A WCS refactor could remove this product-type coupling completely. `WC_Subscriptions_Product::is_subscription` would then simply check for a non-empty `->active_subscription_scheme_id`, and keep the type check for back-compat, perhaps as a way to permanently associate a product instance with a specific `->active_subscription_scheme_id`.

I am not sure, but perhaps I could use the existing filters in `WC_Subscriptions_Product` to do all of this on the SATT side.

**Comment by franticpsyx** [comment]
@thenbrent Modified the issue title into something more tangible. 

If you agree about the idea of storing scheme + sub state data in product instances, then it might make sense to start refactoring SATT and see if there is anything in WCS that prevents this concept from working:

>I am not sure, but perhaps I could use the existing filters in `WC_Subscriptions_Product` to do all of this on the SATT side.

We can postpone the WCS refactor discussion until when we have a SATT codebase that we are happy to use as a base for borrowing/porting logic into WCS.

**Comment by franticpsyx** [comment]
>But another major objective for this was to try to come up with a way to get access to all of a subscription product's features, like one-time shipping, synchronised renewal dates, limiting etc., without having to rebuild UIs etc. to add those to SATT schemes/products.

>I can't really see a clear way to achieve that through re-architecting SATT. It may instead involve refactoring a lot of code in Subscriptions itself to make those features more reusable.

Regarding these, I couldn't agree more, of course.

I don't see a way to re-use logic for admin UIs at the moment, but I can live with that for now.

What I **hope** is that I can use WCS filters to avoid setting a bunch object properties explicitly whenever I want to "apply" a sub scheme -- and instead rely on setting a single state id to change how WCS sees all these subscription product features/settings.

So instead of having to modify the SATT code in 10 different places in order to add support for a WCS feature, I can simply rely on adding a filter in one place.

**Comment by franticpsyx** [comment]
Plan:

1. Write an interface for getting/setting subscription data on a product object (passed as parameter). Interface will try to borrow from current WCS Product API as much as possible.

Subscription data consists of:

- Scheme data and other options, currently stored as post meta, which are _stateless_. Note that under WC 2.7 scheme data will be on the object already (as `WC_Data` meta).
- Data with state that define the actual scheme that is active on a product object: This would be the scheme ID, which we can store on the object as well.
- Data that are set on the object as a consequence of its active scheme, such as: subscription interval, period & length props, price data, etc.

Storing the subscription state _on_ the product object will make it possible to use this API in different contexts -- in cart context the data will be set on session load while in order context the data can be set when calling `WC_Order::get_product_from_item`, or `WC_Order_Item_Product::get_product` in WC 2.7. 

Note that at the moment, the active scheme ID in cart context is stored in the cart item array. WC 2.8 will represent cart items as objects, as well.

Before implementing all this, let's look at the interface with @thenbrent .

2. Implement the interface.

3. Refactor existing code to use the SATT Product API.

**Comment by franticpsyx** [comment]
See progress so far in https://github.com/Prospress/woocommerce-subscribe-all-the-things/compare/master...2.0
