### ISSUE TITLE
Subscription API can only show 100 entites per page

### ISSUE THREAD

**Issue by Didi95** [Prospress/woocommerce-subscribe-all-the-things#420]
i currently try to fetch all the active subscriptions but discovered that this is limited for 100 items per page. Is there a chance to increase this limit?

**Comment by thenbrent** [comment]
Hi @Didi95 this repository is for issues with _Subscribe All the Things_, not the main _Subscriptions_ plugin or any other plugin sold via WooCommerce.com.

To get help with REST API issues, please submit a ticket to WooCommerce.com support system here: http://woocommerce.com/my-account/create-a-ticket/

The short answer to your question is that limits are important to avoid overloading the request and having a timeout or similar issue.
