### ISSUE TITLE
subscription billing length

### ISSUE THREAD

**Issue by benjaminmoquet** [Prospress/woocommerce-subscribe-all-the-things#421]
Hello,

maximum subscription lenght is 24 months. How could we increase the maximum lenght? for instance to 60 months .. we are a leasing company.

**Comment by benjaminmoquet** [comment]
thanks 
ben

**Comment by thenbrent** [comment]
Hi @benjaminmoquet, it requires custom code, but there is some available in the answer to this question here: https://docs.woocommerce.com/document/subscriptions/faq/#section-60

**Comment by benjaminmoquet** [comment]
thanks! Indeed this code works great but when i add it in my function.php, it throws the error below : _cannot send session cache limiter - headers already sent_

however i didn't let any blank space in my function.php.

Any idea?
