### ISSUE TITLE
One time shipping fee option is not working V2

### ISSUE THREAD

**Issue by zisispaparidis** [Prospress/woocommerce-subscribe-all-the-things#423]
Hello,
I have the same problem actuallz with issue#231. Variable subscription Product, checked the checkbox for one time shipping fee but the shipping is being charged annually (the subscription is annual)

**Comment by franticpsyx** [comment]
@thenbrent could you please have a look at https://github.com/Prospress/woocommerce-subscriptions/pull/3197 ?

Closing as duplicate

**Comment by zisispaparidis** [comment]
I can't follow the posted link...

**Comment by franticpsyx** [comment]
@zisispaparidis this requires a patch in Subscriptions 🙂 The link points to that patch.

**Comment by zisispaparidis** [comment]
But I still can't open the url :/. It gives me a 404 error. Or am I missing something?

**Comment by glagonikas** [comment]
The link points to a private repository and people without access get a 404 error.

GitHub should differentiate between 404 and 403 but they don't...

**Comment by zisispaparidis** [comment]
Ai caramba.... Ok. Is this patch included in the latest version of the woocommerce-subscriptions plugin or when can I get my hands on it? Where can I find it?

**Comment by zisispaparidis** [comment]
Hi guys, if the patch is integrated in the latest version of the plugin tell me so that I will renew my license and download it. Thanks.

**Comment by glagonikas** [comment]
It's still under "Pending review" and hasn't been merged yet, so it might not make it to the next release.

As this ticket is now closed, you should probably follow https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/357 and wait until that's marked as resolved.

**Comment by zisispaparidis** [comment]
Ok, thanks!
