### ISSUE TITLE
Add product to existing subscription - shortcode function

### ISSUE THREAD

**Issue by giulianorapoz** [Prospress/woocommerce-subscribe-all-the-things#425]
HI SATT,

Is it possible to please direct me towards the name of the function which triggers the **"Add Product To Existing Subscription?"** I would like to try and call this via ShortCode.

**Scenario:**
Instead of Single Product Pages, my products open in a quick view popup modal. Therefore I would like to Shortcode the "Add Product To Existing Subscription" so that I may display this (highlighted in red) within the popup. I'm hoping this is possible?

![image](https://user-images.githubusercontent.com/30539010/52752672-8c596680-2feb-11e9-9390-6a541d7f6b21.png)

Thanks for your help.
-Giuliano

**Comment by franticpsyx** [comment]
See https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/modules/management/add/class-wcs-att-manage-add-product.php#L176

You will probably need to copy some of the logic there, as the method is intended to be an ajax handler. I would advise against running this on every page load though, as the query can get a bit heavy.

**Comment by giulianorapoz** [comment]
Great. thanks @franticpsyx and appreciate the advice about the query performance.
