### ISSUE TITLE
Stock reduced when signing up to subscriptions

### ISSUE THREAD

**Issue by lippekaffe** [Prospress/woocommerce-subscribe-all-the-things#426]
When signing up to a Subscription of a Simple product (i.e. every week on Friday), stock is reduced for this product in the parent order even though the stock should not be reduced before the order is renewed (each Friday).  This means the stock will be reduced twice for the first delivery. 

This issue describes the opposite to be a problem (which, as the author mentioned, is actually not a problem): https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/268

**Comment by franticpsyx** [comment]
@thenbrent does WCS include any special handling for this?

**Comment by lippekaffe** [comment]
Just double checked now with WCS, and stock IS NOT reduced on sign up: 

Order Note: 
Stock reduced: test subscription (testabo-1) 10→10

I gues the 10→10 is an indication on how it is solved in WCS.

**Comment by thenbrent** [comment]
> stock is reduced for this product in the parent order even though the stock should not be reduced before the order is renewed (each Friday).

It sounds like maybe the subscription product is synchronised to Fridays, is that correct?

If so, there might be an issue with Syncing on the SATT product.

@franticpsyx the code that avoids reducing stock for sync'd subscription products is in `WC_Subscriptions_Synchroniser::maybe_do_not_reduce_stock()`. 

Do you see anything in there that wouldn't be compatible with SATT? 

It all looks like it should be compatible to me.

**Comment by lippekaffe** [comment]
Yes, in this example the subscription is synchronized to Fridays.  In case it was not syncronised, the parent order would also be the first delivery order, and then a reduction in stock is correct.

**Comment by franticpsyx** [comment]
This is next on my list, folks. Thanks for being patient 👍

**Comment by franticpsyx** [comment]
Hey @lippekaffe 

This is going to require some compatibility tweaks in WCS. 
We've already come up with a patch and are currently reviewing the changes. Will keep you updated once we have more to share.

Thanks for reporting this!

**Comment by lippekaffe** [comment]
Now it looks like we have the opposite problem in the case of a mixed cart with regular simple product and an uncynchronised SATT product. The stock of the regular product is reduced on the initial order, but not the SATT product.
