### ISSUE TITLE
Existing Subscription Display Issue When Using Composite Products

### ISSUE THREAD

**Issue by cyclops26** [Prospress/woocommerce-subscribe-all-the-things#427]
This may not not be the best location for this issue as it is a combination of WCS/SATT/Composite Products/Product Bundles - but figured it was the place to start...

If a customer subscribes to a Composite Product/Product Bundle and then goes to their "Account" section and goes to their "Subscriptions" and opens the subscription with the composite product, they will see raw HTML.

This is due to line 48 in `woocommerce-subscriptions/templates/myaccount/subscription-totals.php`
`echo esc_html_x( apply_filters( 'woocommerce_order_item_name', $item['name'], $item, false ) );`

Composite Products/Product Bundles appears to store the composite/bundle details in the `$item['name']`. For now, I'm patching `esc_html_x` to `__` after every update for readability by customers.

Example `$item['name']` value:
`<dl class="component"><dt class="component-PartA">Part A:</dt>`
`	<dd class="component-PartA">`
`               <p>Tech Board 1<strong class="composited_product_quantity"> × 1</strong></p>`
`         </dd>`
`</dl>`

Obviously, that isn't the greatest from a "safety" standpoint, but it gets the job done for now.

Just wanted to get an issue in for this so that others are aware and if easily resolvable in future it can be.

SATT team, please let me know if you would rather I drop this in as a ticket over on the WCS/Composite/Bundles side.

**Comment by franticpsyx** [comment]
Possibly related: https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/419

**Comment by franticpsyx** [comment]
### Steps to Replicate

1. Create  a Simple product.
2. Set its **Catalog Visibility** to Hidden in Catalog/Search.
3. Create a Composite Product.
4. Add a Component.
5. Add the Simple Product you created in Step 1 as its (only) **Component Option**.
6. Add some Subscription Plans to it.
7. Purchase it.

**Checkout > Thank you** page:

https://cl.ly/1e4be0537194

**My Account > Subscriptions > Subscription** page: 

https://cl.ly/e0bd38e4167f

### Cause

HTML is escaped at: 

https://github.com/Prospress/woocommerce-subscriptions/blob/master/templates/myaccount/subscription-totals.php#L48

**Comment by franticpsyx** [comment]
Opened https://github.com/Prospress/woocommerce-subscriptions/issues/3223

@cyclops26 thanks for the detailed description! Awesome :)

I've opened an issue in the WCS repository -- https://github.com/Prospress/woocommerce-subscriptions/issues/3223

CC @thenbrent for a rough estimate on when we can expect a patch in WCS 🥇

**Comment by cyclops26** [comment]
Thanks @franticpsyx. On a somewhat similar note - since WCS is a private repo and I can't comment there, I am in need of subscription switching for Composite Products and Bundle Products (i.e. allowing a change of which components/bundle items they contain and the quantities thereof). Is this something you are working on? If not, I'm more than willing to take a swing at it on my side and if all goes well, I can share the code back with you all so that you can merge with WCS if you deem appropriate.

**Comment by franticpsyx** [comment]
Hey @cyclops26 a fix for this is currently in the WCS pipeline. It should arrive in the next point release of WCS, most likely within the next couple weeks.

> I am in need of subscription switching for Composite Products and Bundle Products

Definitely top priorities, but see https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/57#issuecomment-454778552

The most likely scenario right now is that SATT will be released on WooCommerce.com under a different name. Then we'll start prioritizing the tasks we have on the SATT roadmap. I'm afraid I don't have an ETA to share at the moment, though!

**Comment by franticpsyx** [comment]
Closing here.
