### ISSUE TITLE
Lowest Price is not showing first in Product Meta

### ISSUE THREAD

**Issue by seb86** [Prospress/woocommerce-subscribe-all-the-things#43]
@thenbrent and @franticpsyx I thought the whole point of the price in the product meta data is suppose to be starting **from** the lowest price available. This is not showing the lowest price or am I missing something?

![Lowest Price is not First](https://cldup.com/eXp627EENP.png)
> Screenshot is from a demo product using a new extension I'm working on for [this extension](https://github.com/seb86/woocommerce-subscribe-to-all-the-things-signup-trial-add-on).

**Comment by franticpsyx** [comment]
@seb86 Are you working with latest `master` branch?

**Comment by seb86** [comment]
@franticpsyx Yes. v1.1.0

**Comment by seb86** [comment]
@franticpsyx It seemed to be that Git did not pull all the changes 100% at the time. I have refreshed and now appears to be working fine.
