### ISSUE TITLE
FROM PRICE under product title display the most expensive one

### ISSUE THREAD

**Issue by benjaminmoquet** [Prospress/woocommerce-subscribe-all-the-things#432]
Hello,
I have a bundle product with different subscription options : 
10€ for 6 months
8€ for 12 months
6€ for 18 months

On my product page under the title, SATT display "from 10€ for 6 months". 

The first subscription option is  my shortest one (so the most expensive one), the last my longest subscription (so the most cheapest one).

How could i display "FROM 6€ for 18 months" ?

Thanks a lot,

**Comment by benjaminmoquet** [comment]
one precision, changing order would not be logical even if it works...

6€ for 18 months
8€ for 12 months
10€ for 6 months

**Comment by franticpsyx** [comment]
SATT uses the first plan as reference for calculating price strings.

Your assumption that prices should be ordered based on the "total amount paid" over the lifecycle of the subscription might make a lot of sense in your case -- however, it doesn't really apply to all use cases: It assumes that the **total value being delivered over the lifecycle of the subscription is the same in all cases**, which is not always true.

This is a typical example of functionality that needs to be customized based on domain-specific knowledge. To change the "base/reference" scheme used for price string calculations, use [this filter](https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/f07faf2ba37157ad8edf532c59335d65f556f5ab/includes/product/class-wcs-att-product-schemes.php#L303).
