### ISSUE TITLE
8 Month Subscription Option, Applying Discounts Incorrectly (Possibly another Plugin Issue)

### ISSUE THREAD

**Issue by particlemarketing** [Prospress/woocommerce-subscribe-all-the-things#433]
Hey!

So I love your plugin but I've run into two issues. (The site is www.activebotanicalco.com and you can see examples of the issues on this product page: https://activebotanicalco.com/product/energy-formulation-6000mg-tincture/ ).

Issue #1: One of our products renews every 8 months. Is there a way to add this into the code to be an option?

Issue #2: I have a site wide discount applied via another plugin (XL Plugins - Finale). That plugin is set to take 20% off site wide, and we want to offer an additional 10% off if they subscribe to re-order for a total of 30% off. Currently, the 10% offer to sign up just relays the already 20% marked off price instead of taking another 10% off. When I disable the Finale plugin, the discounts are calculated correctly.

I am aware this is an open source project with volunteers, is there a way I can donate to your cause to get this issue fixed faster? This site is set to launch this Friday and this is one of the last things we are working on. I humbly ask for your help as this is far beyond what I am capable of coding. Thanks in advance!

**Comment by franticpsyx** [comment]
Hey @particlemarketing 

> Issue #1: One of our products renews every 8 months. Is there a way to add this into the code to be an option?

SATT is only getting the available period/interval options from WC Subscriptions itself. This might be possible to customize in WCS, but I'm afraid I don't have any prior experience with this myself.

> Issue #2: I have a site wide discount applied via another plugin (XL Plugins - Finale). That plugin is set to take 20% off site wide, and we want to offer an additional 10% off if they subscribe to re-order for a total of 30% off. Currently, the 10% offer to sign up just relays the already 20% marked off price instead of taking another 10% off. When I disable the Finale plugin, the discounts are calculated correctly.

SATT calculates discounted price off the regular price by default, but you can make it take any existing discounts or sale prices into account using this filter:

`add_filter( 'wcsatt_discount_from_regular', '__return_true' );`
