### ISSUE TITLE
Ajax "add to cart" from single product page doesn't pass SATT scheme data

### ISSUE THREAD

**Issue by studioleland** [Prospress/woocommerce-subscribe-all-the-things#434]
Using the traditional page reload add to cart button everything works nicely but when I go to ajax add to cart method the subscription data is not passed to the cart with the product items (only quantity and product id).  Can anyone help with direction here?

**Comment by franticpsyx** [comment]
Hey @studioleland I assume this is a feature implemented by your theme, as WooCommerce doesn't offer any option to enable "ajax-add-to-cart" functionality in single-product pages.

Your theme author(s) will need to make sure that all form data is posted when clicking the ajax add-to-cart button, possibly by:

* serializing all form fields; and then 
* writing them to the `$_POST` variable on the back-end side of things when handling the request.

In principle, this doesn't only affect SATT but any extension/plugin that adds custom fields.
