### ISSUE TITLE
Preselect Subscription for Cart

### ISSUE THREAD

**Issue by aloco** [Prospress/woocommerce-subscribe-all-the-things#435]
Hi,

thank you for your efforts in developing this plugin. I am using subscriptions only for the entire  cart. I want to give customers the option to select between "no subscription", "every week" and "every month" - I was able to set everything up and it´s working as intended. The only issue I have is, that I am not able to preselect "every week" on cart level. I know, there is an option to preselect a subscription scheme on product level, but I can´t find this on cart level. 

Do you know which filter I might use to just preselect the corresponding radiobox on the cart page? 

Thank you in advance

**Comment by limist** [comment]
+1 would also like to know how to do this, thanks.

**Comment by franticpsyx** [comment]
Hey all,

You can use this filter to enable the first cart subscription scheme by default:

`add_filter( 'wcsatt_enable_cart_subscription_by_default', '__return_true' );`
