### ISSUE TITLE
Possibility to add Product Bundle to Cart via URL??

### ISSUE THREAD

**Issue by fcponline** [Prospress/woocommerce-subscribe-all-the-things#44]
Hello,

We are using Subscribe to All Things successfully with Product Bundles. We can create Bundles and Subscription levels.  Now we are trying to add a Product Bundle / Subscription via a URL string.

We can get the Parent Product and Total price in the Cart, but not the Child Products.

Here are a few of our attempts...

https://www.staging5.website.com/?post_type=product&add-to-cart=4089&bundled_items=1979,148&quantity=2,3

https://www.staging5.website.com/?post_type=product&add-to-cart=4089&variation_id=1979&quantity=1&&variation_id=148&quantity=2

Is this possible?  

If not how can we do this via a button on our site?

Thanks

FCP

**Comment by fcponline** [comment]
We have also tried to follow the format of Group Products but it does not work....

http://yourdomain.com/?add-to-cart=3111&quantity[1803]=5&quantity[1903]=2

Any ideas how we could make this work?

Thanks

FCP

**Comment by franticpsyx** [comment]
@fcponline This is definitely possible with Product Bundles, however this is not a place to get PB support - please open a support ticket at WooThemes helpdesk, asking for input from an extension dev if necessary.
