### ISSUE TITLE
Confusion with frequency setting

### ISSUE THREAD

**Issue by thenbrent** [Prospress/woocommerce-subscribe-all-the-things#46]
From @buckneri on https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/1#issuecomment-227572523

> The frequency setting for monthly/daily/yearly doesn't make sense.

> When you set Monthly it tallies the price and sets it to a monthly payment.
> Yearly should do the same and multiply by 12 instead it just charges the same amount once per year.

> This may be the designed functionality, but i'm at a loss for what product you would sell for $50/month but give the customer the option to only pay $50 per year($5/month) for the same thing. (services for example, would be monthly but give a discount for annual payment, but that annual payment would not be less than monthly it would be monthly x 12 - discount)

**Comment by thenbrent** [comment]
> When you set Monthly it tallies the price and sets it to a monthly payment.

I'm not sure what you mean here. Neither Subscriptions nor SATT "tallies the price". They will both display whatever price is set for whatever billing period the store manager chooses for that price.

Can you share a screenshot to explain the issue?

**Comment by franticpsyx** [comment]
>but i'm at a loss for what product you would sell for $50/month but give the customer the option to only pay $50 per year($5/month) for the same thing

SATT allows customers to purchase products on a recurring basis - in the most thorough possible way. For instance, if a customer wishes to purchase a bottle of milk on a recurring basis, they will need to pay the same bottle price, regardless of whether they choose to receive it once every month or once every day.

If, on the other hand, you wish to offer multiple subscription options for a product whose price changes according to the time of use (services), you can simply define a different product price with every subscription option - example: $5 per month, $50 per year, etc.

Closing until further notice.
