### ISSUE TITLE
Calling WCS_ATT_Cart::convert_to_sub() by itself throws fatal error

### ISSUE THREAD

**Issue by pmgarman** [Prospress/woocommerce-subscribe-all-the-things#48]
`WCS_ATT_Cart::convert_to_sub( 'cart_item_key' );`

```
Fatal error: Cannot use string offset as an array in /site/wp-content/plugins/woocommerce-subscribe-all-the-things/includes/class-wcsatt-cart.php on line 168. Output triggered in /site/wp-content/plugins/query-monitor/collectors/php_errors.php on line 137
```

**Comment by franticpsyx** [comment]
@pmgarman 

`convert_to_sub` accepts a single `array` argument (see doc block). Can you explain how you are attempting to use it?

**Comment by franticpsyx** [comment]
Closing after our chat on Skype.

@pmgarman have you resolved that issue with variable products? I wasn't able to replicate.
