### ISSUE TITLE
JavaScript triggers for third party extensions

### ISSUE THREAD

**Issue by seb86** [Prospress/woocommerce-subscribe-all-the-things#49]
@thenbrent @franticpsyx It would be great if we could have some triggers put in place so third party extensions could integrate as well. Would this be possible before the release of v1.1?

**Comment by seb86** [comment]
I'm still learning Javascript so would this trigger work if placed after [line 207](https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/assets/js/wcsatt-single-add-to-cart.js#L207)?

`this.trigger( 'wcsatt-update-composite-price', [ scheme_price_html, scheme ] );`

**Comment by seb86** [comment]
Same trigger for product bundles.

`this.trigger( 'wcsatt-update-bundle-price', [ scheme_price_html, scheme ] );`

**Comment by franticpsyx** [comment]
@seb86 We can definitely add a couple triggers in there. Just a word of caution, though - we are discussing plugins... of a beta mini-extension... of an extension... of a WP plugin. :)

**Comment by franticpsyx** [comment]
...oh and this specific script is actually plugging into the script of another extension (PB).

**Comment by seb86** [comment]
@franticpsyx Considered me warned but it should still work... right?

**Comment by franticpsyx** [comment]
Hehe -- right! 

But being at the end of a chain that includes "experimental" or "beta" parts is definitely not for the faint hearted :)

**Comment by seb86** [comment]
... and then something like this can be used.

```
;( function ( $, window, document, undefined ) {
    var selector = ''; // This would be the selector we want to apply the function to when triggered. e.g. .subscription-price-shortcode

    $( 'body' ).on( 'wcsatt-update-composite-price', seclector, function( e, scheme_price_html, scheme ){

    } );

} ) ( jQuery, window, document );
```

**Comment by seb86** [comment]
@franticpsyx Sorry if I held you back with the release because of my sudden absence. I had yet to get around to testing my idea and was busy with a client. Thanks for pushing this.
