### ISSUE TITLE
Integration with Bundles, Composites and MnM (ongoing)

### ISSUE THREAD

**Issue by franticpsyx** [Prospress/woocommerce-subscribe-all-the-things#5]
- [x] Bundled items should inherit any subscription schemes defined at container level (even when they have their own product-level schemes).
- [x] Bundled items that are sub-type products should prevent any subs schemes at container level from working. If a bundle contains a sub-type product, it shouldn't be possible to define subs options at container level.
- [ ] Show a notice when attempting to create container-level subs options and the bundle contains sub-type products.
- [x] When subs options are defined at container-level, do not display options at bundled-item-level.
- [x] Fix totals shown in product-details subscription options when bundle has price overrides ( #20 ).
- [ ] Ideally, support SATT products in Bundles, Composites, etc.

**Comment by Whoweez** [comment]
I'd love to see this integrate with WC Composites

**Comment by franticpsyx** [comment]
Closing in favor of working with specific issues in the SATT - PB/CP/MnM integrations, which is being revamped in 2.0.
