### ISSUE TITLE
Integration with Variable Products

### ISSUE THREAD

**Issue by davidcubecities** [Prospress/woocommerce-subscribe-all-the-things#51]
I know integration with Variable Products has been brought up before.
Was just wondering if it's possible yet, or not?
I know there is a "Variable Subscription" option, but we want to be able to have a variable product with a standard price, and also a subscription option.

Thanks in advance.

**Comment by thenbrent** [comment]
Hi @davidcubecities we have added code to allow Variable level subscription options. It was added in https://github.com/Prospress/woocommerce-subscribe-all-the-things/pull/35 There is some info explaining how it has been implemented on that page.

I don't think that is in a tagged version yet, but it is in the `master` branch if you want to play around.

We're holding off on adding variation level subscription schemes for now for reasons discussed on https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/2

**Comment by seb86** [comment]
@davidcubecities I actually started working on adding support to allow subscription options on the variation level but I have yet to complete it and from previous feedback it would be best to make it available as a seperate extension as it doubles the amount of the code base.

Would you like to discuss further privately?

**Comment by davidcubecities** [comment]
Thanks for the quick replies guys. 
Yeah sure, feel free to send me an email at david@strategiesforsuccess.ca

**Comment by franticpsyx** [comment]
>I know there is a "Variable Subscription" option, but we want to be able to have a variable product with a standard price, and also a subscription option.

Just download the `master` branch or https://github.com/Prospress/woocommerce-subscribe-all-the-things/releases/tag/v1.1.0-RC1 

v1.1.0 will be tagged once we close #49 - probably within the next couple days :)

**Comment by seb86** [comment]
@davidcubecities I have  :e-mail: you.
