### ISSUE TITLE
Support One Time Shipping

### ISSUE THREAD

**Issue by seb86** [Prospress/woocommerce-subscribe-all-the-things#53]
How comes this is not yet available and what is needed to support it?

I assume we would put it in the same place as the default subscription product types under "Shipping" as it would apply to all subscription schemes.

![One Time Shipping](https://cldup.com/EUke3MoDiR.png)

To me, I see the schemes are only for the pricing and billing conditions.

@thenbrent @franticpsyx Do you both agree?

**Comment by seb86** [comment]
Here is my pull request. https://github.com/Prospress/woocommerce-subscribe-all-the-things/pull/54

**Comment by franticpsyx** [comment]
@seb86 The long-term goal is to have all subscription product-type options available in every subscription scheme. We'll be pushing for this once we have dealt with #42 

I'd like to clean up the scheme logic before building new features into it, but you are right that this is one of the things that needs to be looked into.

**Comment by seb86** [comment]
@franticpsyx I think what I have done for now works great as a temporary measure and one that is needed now even if we don't add any other features for a while until you have refactored how the product subscription scheme data is saved. What do you think?

**Comment by franticpsyx** [comment]
@seb86 It's really a matter of prioritization - no matter how big or small, I'd rather avoid adding a feature until we have a clear idea of what API changes need to go into v1.2 or v2.

**Comment by seb86** [comment]
@franticpsyx OK that's fine. I just did it quickly because a client is using this extension for composite products and emailed me to say the standard subscription option for shipping one time was not there which I thought it was already.
