### ISSUE TITLE
Coupons not working properly

### ISSUE THREAD

**Issue by glagonikas** [Prospress/woocommerce-subscribe-all-the-things#55]
I've noticed coupons don't appear to work when SATT is combined with Composite Products (not sure if that affects other product types also).

I've tried the options including "Basket % Discount" and "Recurring Product % Discount" and they both appear to have different issues.

# Case 1
## Setup
1. Create a composite product with price X. On Shipping options select an option that incurs a shipping cost. On subscription options set "subscription price" to "override product" and set a price (the other option produces the same results). Set the "Free Trial" option to something.
2. Create a coupon of type "Basket % Discount". Set coupon amount to 0 or 100 (doesn't make a difference on the actual result). Select the "grant free shipping" option.
3. On WooCommerce shipping options ensure the free shipping option is enabled and the "require a valid coupon" is selected,
4. Go to the product page, add it to cart and go to checkout to apply the coupon.
5. The total is 0 + shipping cost (due to free trial). The recurring total is X.
6. Apply the coupon

## Expected Result
Once the coupon is applied, the free shipping option should be enabled.

## Actual Result
An error is shown with the message "Sorry, this coupon is only valid for an initial payment and the cart does not require an initial payment."

## Notes
1. If you remove the subscription options from the product and try to buy it as one-off, the same coupon can be applied normally.
2. The coupon value doesn't seem to affect the end result.
3. I would imagine that if you set coupon value to 100% and remove the free shipping option, you would still end up with free shipping, but might be wrong on this.

# Case 2
## Setup
1. Duplicate the product of Case 1.
2. Create a coupon of type "Recurring Product % Discount". Set a value.
3. Go to the product page, add it to cart and go to checkout to apply the coupon.
4. The total is 0 + shipping cost (due to free trial). The recurring total is X.
5. Apply the coupon.

## Expected Result
Once the coupon is applied, the recurring price should be updated depending on the discount of the coupon.

## Actual Result
The coupon is applied, but the recurring price remains the same (X).

Am i wrong on my configuration and expectations or is this a bug?

**Comment by thenbrent** [comment]
Hi @glagonikas, thanks for the thorough report! It helps a lot.

I think this relates closely to #33 (though the scope of this issue is greater than that in #33).

That might provide you with an answer, even though it's likely not the answer you want. 😞 

Otherwise, I'll let @franticpsyx answer as he's the Composite Products guru. 😄

**Comment by franticpsyx** [comment]
Hey @glagonikas - thanks for the report!

**Case 1**

>Create a composite product with price X. On Shipping options select an option that incurs a shipping cost. On subscription options set "subscription price" to "override product" and set a price (the other option produces the same results). Set the "Free Trial" option to something.

SATT doesn't provide a "Free Trial" option under the "Subscriptions" tab. Are you using a 3rd party plugin/extension to add it?

**Case 2**

I think that the Recurring Discount options are added by WCS ( @thenbrent ? ) , so perhaps there is an incompatibility between the way these specific coupons are handled and SATT.

However, again note that SATT technically doesn't support Free Trials, Set-up Fees or Synced Renewals, so if you are using a 3rd party plugin to add support for these in SATT, I would suggest deactivating it to see how that changes things.

**Comment by seb86** [comment]
@franticpsyx I have not tested coupons with SATT yet but I would have thought the coupons would be unaffected. I have linked below what @glagonikas is using with SATT.

Sign-up and Trial for SATT is supported [here](https://github.com/seb86/woocommerce-subscribe-to-all-the-things-signup-trial-add-on).
Shipping fee is forced on the initial order on subscriptions that have a free trial using [this filter](https://github.com/seb86/Charge-Shipping-Fee-for-Free-Trials).

Maybe you can take a look and see how to improve the support for these additional SATT features before it is added to the core of SATT.

I would test just the sign-up and free trials and ignore the filter plugin for now.

**Comment by franticpsyx** [comment]
>Sign-up and Trial for SATT is supported here.
>Shipping fee is forced on the initial order on subscriptions that have a free trial using this filter.

@seb86 SATT is already quite fragile/complex to start with, so I'm afraid I won't be able to look into anything that includes other dependencies. I hope this is understandable!

Once we officially add support for Free Trials and other WC Subs features, I'll be happy to look into any associated issue.
