### ISSUE TITLE
Product Data panel - No Subscriptions Tab

### ISSUE THREAD

**Issue by cte2087** [Prospress/woocommerce-subscribe-all-the-things#58]
Hello and Thank You for this mini plugin!
I have been trying to accomplish this the long way by linking and grouping.
I have uploaded and activated the the plugin, but I am not seeing the same options as shown in your set-up screenshots. I have Woo Subscriptions current version over the required 2.0. Woo is also current and up to date. Is there something I might have missed in my set up....or possibly I did not download the most current version of the mini plugin.(I used the large button link at the top right.) I have a Subscriptions "checkbox" along the top and I also have "subscriptions simple" and "subscriptions variable" in the product type drop down. I am not sure if this will help in identifying the issue.
This will be an amazing addition for my client, but if you view the screenshot attached, I do not have the same options as others. Any advice is greatly appreciated.
![heirloom-subscription-screenshot](https://cloud.githubusercontent.com/assets/20936977/17555962/991ad7ee-5edf-11e6-90c0-cc27524fed2b.jpg)

**Comment by seb86** [comment]
This extension does not add a checkbox to show the subscriptions tab section. Not sure how you have got that.

**Comment by franticpsyx** [comment]
Closing since I can't replicate.

**Comment by fdolin** [comment]
Hi there, I have the exact same issue : no additionnal "subscriptions" tabs on products, whereas  I have Woo Subscriptions current version over the required 2.0. Woo is also current and up to date...

Any idea why this tab is missing ?

thanks in advance

**Comment by seb86** [comment]
@fdolin Are you using SATT version 2.0?

**Comment by fdolin** [comment]
hi @seb86 , actually i'm not sure what you mean by SATT version 2.0 ?

**Comment by seb86** [comment]
@fdolin The version of Subscribe all The Things. Are you using version 2.0 that is currently in development?

**Comment by fdolin** [comment]
@seb86 the installed version is Version 1.1.2.Is there a more uptodate version?

**Comment by fdolin** [comment]
the website is on Woocommerce 3.0.6, could this be the reason for this ?

**Comment by seb86** [comment]
@fdolin A lot of improvements have been made and is compatible with all the latest updates.

[Read the new readme file](https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/2.0-readme/README.md) for details and [download SATT 2.0](https://github.com/Prospress/woocommerce-subscribe-all-the-things/archive/2.0.zip).

That should solve your issue.

**Comment by fdolin** [comment]
thank you. I've updated the extension to the 2.0., but still have the same issue : subscriptions tab is not displayed on the product backoffice page...
Any idea on why ?

**Comment by seb86** [comment]
@fdolin I personally dont have this issue. Which version of WooCommerce Subscriptions do you have active?

**Comment by fdolin** [comment]
woocommerce subscriptions Version 2.2.7

**Comment by fdolin** [comment]
Actually after further tests : 
when choosing the "product bundle" product type, i have the subscriptions tab displayed
when choosing the "mix n match" product type, the subscriptions tab is not displayed : 

![capture d ecran 2017-06-14 a 17 10 55](https://user-images.githubusercontent.com/4179819/27139923-8ad02b98-5124-11e7-9c26-3ce7dddae65e.png)
![capture d ecran 2017-06-14 a 17 10 43](https://user-images.githubusercontent.com/4179819/27139924-8ad2cd80-5124-11e7-90cd-9c4d963912b7.png)

any idea how to get it on the "mix n match" product type ?

thanks

**Comment by seb86** [comment]
@fdolin What version of Mix n Match are you using?

**Comment by fdolin** [comment]
WooCommerce Mix and Match Version 1.2.3

**Comment by seb86** [comment]
Strange. I'm getting the Subscriptions tab just fine. I wonder if there is a conflict with another extension that hides the tab.

**Comment by seb86** [comment]
@franticpsyx Any thoughts?

**Comment by fdolin** [comment]
I've found the origin of the conflict : the bug appears when the plugin YITH WooCommerce Product Bundles is activated.

**Comment by seb86** [comment]
Ah. SATT only supports Product Bundles from WooCommerce.com

**Comment by franticpsyx** [comment]
Hey @seb86 -- you rock, thanks for handling this! Closing.
