### ISSUE TITLE
Can't Save Options

### ISSUE THREAD

**Issue by Multicade** [Prospress/woocommerce-subscribe-all-the-things#59]
Seems to be an amazing plugin! I can't seem to save the options on cart based or individual. Everything seems to function, (dropdown options etc.) but when I save, the page reloads as if it saved but nothing happens. It defaults to "array" 

Any help would be greatly appreciated

**Comment by seb86** [comment]
@Multicade Perhaps you could give a little more information than just "Can't Save Options".

**Comment by Multicade** [comment]
Hi thanks for the quick reply,

Here are the plugins im using: https://gyazo.com/02b2304342e93e7ba40d5d69265afb88

Here is the setting that won't save: https://gyazo.com/754a46bcf48fe6c158b8445df8f2800a

When I hit save at the bottom of the page here: https://gyazo.com/d1c224e51a35d1c55a1ad5ddaf266370

The page refreshes as if it saved, but still shows this: https://gyazo.com/754a46bcf48fe6c158b8445df8f2800a

**Comment by seb86** [comment]
You might want to update WooCommerce and WooCommerce Subscriptions. See if that helps. Not sure why you are getting an `Array` on the third select field.

**Comment by Multicade** [comment]
Okay sounds good.. I will do that an let you know if that fixes the problem.

Thanks again


SCOTT MCDONALD
OWNER | DESIGNER
OFFICE: 209.479.7600
CELL:     209.423.5824
scott@monsterdesignstudios.com
www.monsterdesignstudios.com



This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system.





On Tue, Aug 16, 2016 at 10:39 AM, Sébastien Dumont <notifications@github.com

**Comment by Multicade** [comment]
It worked! Just updated woocommerce to current and solved the issue..

Thanks!

SCOTT MCDONALD
OWNER | DESIGNER
OFFICE: 209.479.7600
CELL:     209.423.5824
scott@monsterdesignstudios.com
www.monsterdesignstudios.com



This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system.
