### ISSUE TITLE
Quantity update in cart fails

### ISSUE THREAD

**Issue by seb86** [Prospress/woocommerce-subscribe-all-the-things#60]
I noticed that you can not update the quantity of an item unless you change the subscription scheme as well.

I'm not sure if this is affected by having more than one subscription scheme option for the product or not but simply changing the quantity does not work on a simple product with subscription scheme options.

**Comment by fcponline** [comment]
We have not seen this particular problem but we have lost the quantity fields when we choose product bundles as the product type.  Subscriptions are fine but the quantity fields disappear completely.

**Comment by javorszky** [comment]
Hm, how are you doing this?

I tried recreating this on my local dev site, and I could do it without a problem. I have a simple product setup, and STATT has 4 schemes (every week, every 2 weeks, every 3 weeks, every 4 weeks) attached to it.

I add one of the schemes (weekly) to the cart with a qty of 1. I visit the cart page.

* I can change the qty to 4 without changing the scheme.
* I can change the scheme to every 2 weeks with the qty still being 4
* I can change the qty to 2 with the scheme being every 2 weeks still.

**Comment by seb86** [comment]
@javorszky I will have to get back to you on that as I can't remember the setup now.

**Comment by seb86** [comment]
I think it was when trying to lower the qty only. The product had 1 subscription scheme and forced subscription enabled with the price inherited.

**Comment by franticpsyx** [comment]
Closing as I wasn't able to replicate. Feel free to update this ticket with more information if you think that the issue actually persists.
