### ISSUE TITLE
Cart doesn't differentiate between StAtT products on different schemes

### ISSUE THREAD

**Issue by javorszky** [Prospress/woocommerce-subscribe-all-the-things#62]
Setup:

* product with 2 different schemes: "every week" and "every 4 weeks"
* add 1 x product with "every week" to the cart
* add 1 x product with "every 4 weeks" to the cart

Expected:

* 1 x "every week" product
* 1 x "every 4 weeks" product

Actual:

* in the cart, see that it is 2 x "every week"

**Comment by franticpsyx** [comment]
Thanks for catching this, @javorszky 👍 

Not sure why I used the `woocommerce_add_cart_item` filter there - using this can't result in unique cart ids being generated.

Committed a fix straight to `master`.
