### ISSUE TITLE
Possibility of Subscribe Cart applied only to certain Category or Products

### ISSUE THREAD

**Issue by fcponline** [Prospress/woocommerce-subscribe-all-the-things#63]
Hello,

This is a radical idea / issue that we are faced with that we are solving 60% with WCSAT plugin and the Subscribe Cart feature.

Due to the fact that our custom coded payment gateway subscription plugin / and really all others, cannot manage multiple subscriptions created by the WCSAT applied to Product Bundles without a major upgrade to WC Subscriptions 2.0 and reworking your payment gateway we have come up with the following...

We use the Subscribe Cart feature to combine all our Subscription products in the Cart under one Subscription and Recurring value.  We even apply discounts using WC Coupons and custom code. It works great --- except now ANY and ALL products get a subscription discount.  The same subscr / discount that we apply to our subscription products.

The standard WC Subscr plugin controls to turn on / off Mixed Content no longer work. It looks like WCSAT plugin negates it.

We have now have subscription products and non-subscr products that need 2 separate carts or sessions to control the actual costs of the products.

Question???

Is there a way to make the WC Subscrib Mixed Content controls work again? What code in the WCSAT plugin is making this void?

Is there a way to apply Subscribe Cart to only a specific Category of Products?

Any and all thoughts / comments are welcomed.

Thanks,

-fcp

**Comment by franticpsyx** [comment]
>Due to the fact that our custom coded payment gateway subscription plugin / and really all others, cannot manage multiple subscriptions created by the WCSAT applied to Product Bundles without a major upgrade to WC Subscriptions 2.0 and reworking your payment gateway we have come up with the following...

Unless you are working with Subscriptions v2.0+, we cannot provide any kind of support or look into any sort of issue.

Are you trying to use SATT with something else?
