### ISSUE TITLE
Issue when adding to cart

### ISSUE THREAD

**Issue by anthonysbrown** [Prospress/woocommerce-subscribe-all-the-things#66]
Hey guys, hows it going. first off just want to say thank you. this is exactly what we needed. I'm just having one issue. When choosing the one time purchase as default and adding to the cart it actually defaults to subscription. The odd thing is when i reverse it and set the subscription to be default then when adding to the cart it works as it should. Has anyone else had an issue like this? You can see that happen here

[https://goo.gl/Kd9tLF](https://goo.gl/Kd9tLF)

Thanks!

**Comment by anthonysbrown** [comment]
As a work around I set it to the single product as default and used javascript to change it onload


```
jQuery(function($) {
			
			
			$('.wcsatt-options-product input[type="radio"]').last().prop('checked', true);

});
```

**Comment by franticpsyx** [comment]
Hey @anthonysbrown - Can't replicate. Perhaps a 3rd party plugin is causing a conflict?

This looks too obvious to miss -- if it was an issue I'd guess we would have more reports by now.
