### ISSUE TITLE
Item option descriptions in cart are not escaped

### ISSUE THREAD

**Issue by javorszky** [Prospress/woocommerce-subscribe-all-the-things#67]
It's missing an `esc_html` or a `wp_kses`.

The description by default depends on the price of the product / scheme which does not allow arbitrary input on the back end, however there's the `wcsatt_cart_item_options` filter which can be used to change any of the descriptions to contain unsafe JS stuff.

That would be printed without escaping. To test, add this to your functions:

```
add_filter( 'wcsatt_cart_item_options', '_test_foo_thingies', 10 );

function _test_foo_thingies( $options ) {
	foreach ($options as $key => $option) {
		$options[$key]['description'] .= '<script>alert("foo");</script>';
	}
	return $options;
}
```

**Comment by franticpsyx** [comment]
@javorszky Not sure what's considered as best practice, but if a plugin with an intent to do unsafe stuff can be installed and activated in the first place, the last thing it will want to do is hook into a SATT filter (?).

**Comment by javorszky** [comment]
Every string that gets `echo`d, `printf`d or displayed some other way should run through and `esc_XXX` function. See https://codex.wordpress.org/Validating_Sanitizing_and_Escaping_User_Data, about Escaping: Securing data. I appreciate that in this particular case the data comes from within plugin itself.

That said I'm still of the opinion that it should be escaped. PR up in a few minutes.

**Comment by franticpsyx** [comment]
@javorszky Agreed - still I'd rather use something like `wp_kses_post` to allow some basic flexibility with rendering html tags. Thoughts?

**Comment by javorszky** [comment]
Yes, that seems fair. Lemme rework that.

**Comment by javorszky** [comment]
Done, commit added

**Comment by franticpsyx** [comment]
Thanks @javorszky 👍
