### ISSUE TITLE
Restrict by user roll

### ISSUE THREAD

**Issue by ash-f** [Prospress/woocommerce-subscribe-all-the-things#72]
I want to disable subscription product for user with certain user roll.
Is it possible?

**Comment by ash-f** [comment]
I've put following code on the first line of plugins_loaded()
`$user = wp_get_current_user(); if(in_array('wholesale_customer',(array)$user->roles)){ return; }`

It would be nice if I can set through a hook.

**Comment by franticpsyx** [comment]
Hi @ash-f - this sounds possible using the available filters - unfortunately we cannot provide assistance with customizations: Please remember this is a bug tracker.
