### ISSUE TITLE
Getting a 502 error when going to Wp-admin-->Woocommerce-->products

### ISSUE THREAD

**Issue by GoodGuyTaj** [Prospress/woocommerce-subscribe-all-the-things#75]
Hi,

I am hosted on WP-engine. I get a 502 error with subscribe-all-things installed. My error log shows the following.

purge_varnish_cache() failed for: (localhost) #^(algaebarnllc\\.staging\\.wpengine\\.com)$# #((.*)?post_type=scheduled-action&p=5428)#, referer: http://algaebarnllc.staging.wpengine.com/wp-cron.php?doing_wp_cron=1478376036.0824160575866699218750

If I disable the subscribe-all-things plugin, the issue disappears. I am running the most current system of wordpress/woocommerce/etc.

Any thoughts? Any other data I can provide to help?

**Comment by thenbrent** [comment]
@GoodGuyTaj that error seems unrelated to both the **WooCommerce > Products** page and the SaTT plugin... are you sure it's the related error?

The `purge_varnish_cache()` is most likely a WP Engine function (it's not in any plugins I know of and sounds very hosting related) so if you haven't already, please contact WP Engine support to request help diagnosing it.

**Comment by franticpsyx** [comment]
...closing for now as I can't replicate.
