### ISSUE TITLE
why is there a "Free!" added to my "none?"

### ISSUE THREAD

**Issue by rickamos** [Prospress/woocommerce-subscribe-all-the-things#77]
This plugin saved my life.
Everything works well with my "simple" pages. (I swapped "Just a single donation" for "None" in the CSS "display."
https://eurasiapartners.org/projects/coaching/women/
However when I tried to make a "variable" page, I got a random "- Free!" added to the end of "Just a single donation"
https://eurasiapartners.org/projects/coaching/women-two/
(click on any amount to see the recurring option)
How can I get rid of the "- Free!"

**Comment by pprotschka** [comment]
@rickamos 
have you by change added/changed these filters:
woocommerce_subscriptions_product_price_string_inclusions
woocommerce_subscription_price_string

i had customized the price string and had the same issue.
clear your custom filters and see if the problems persists.
