### ISSUE TITLE
Coupon discount is not applied to "Recurring Total"

### ISSUE THREAD

**Issue by ash-f** [Prospress/woocommerce-subscribe-all-the-things#78]
it's applied to only "Total" which is first charge of the subscription.

**Comment by thenbrent** [comment]
@ash-f sounds like you might be describing the expected behaviour of coupons: https://docs.woocommerce.com/document/subscriptions/store-manager-guide/#section-2

If not, please reopen and provide more details of the type of coupon and product (screenshots will help a lot).
