### ISSUE TITLE
Coupon discount is not applied to "Recurring Total" #2

### ISSUE THREAD

**Issue by ash-f** [Prospress/woocommerce-subscribe-all-the-things#79]
I was expecting coupon discount will be applied to both total(first payment & recurring payment)

When I set coupon discount type to "Cart discount"
http://imgur.com/a/5G5f7
Discount is applied to only first payment.
But this is normal behavior according to this page above, right?
https://docs.woocommerce.com/document/subscriptions/store-manager-guide/#section-2

When I set coupon discount type to "Recurring discount"
http://imgur.com/a/izcLS
I don't see any discount. Is this normal?

**Comment by thenbrent** [comment]
> When I set coupon discount type to "Recurring discount"
> I don't see any discount. Is this normal?

Has the coupon been applied? There doesn't appear to be any coupon applied to that cart.

**Comment by ash-f** [comment]
Sorry some filter was interfering.
