### ISSUE TITLE
Template Structure Unclear - Override not working

### ISSUE THREAD

**Issue by pprotschka** [Prospress/woocommerce-subscribe-all-the-things#81]
v1.1.1  
I tried putting satt-cart-item-options.php with my changes into:
child-theme/woocommerce/cart/satt-cart-item-options.php
child-theme/woocommerce/satt-cart-item-options.php
also tried
child-theme/woocommerce/cart/cart-item-options.php
child-theme/woocommerce/satt-item-options.php

none of these options worked.

fromt the comments in file:
 * Override this template by copying it to 'yourtheme/woocommerce**/cart-item-options.php'.** file name here is different than actual template file name..why?

**Comment by franticpsyx** [comment]
Hey - thanks for reporting this.

Should be fixed in `master` now. We have updated the template file headers, too. 
Apologies for the confusion!
