### ISSUE TITLE
Ajax update on cart breaks native "ajax update cart" functionality.

### ISSUE THREAD

**Issue by pprotschka** [Prospress/woocommerce-subscribe-all-the-things#82]
1.) goto cart with a  couple of items.
2.) change quantity of some products ..hit update (ajax updates) everything is fine.
3.) now change to a subscription option defined with SATT.
4.) satt ajax update happens everything fine - great.
5.) now go back and change product quantity one more time. and hit update - ajax upadtes and refreshes empty/white page.

i have trace it down to the following:
the satt ajax change the hidden input _wp_http_referer to some satt ajax url. This breaks the native ajax update function.
this little js snippet fixes it by setting the referer back to the /cart/ url. This is a temp solution as /cart/ will vary depending on what page WC has defined as cart...

`jQuery(document.body).on('wcsatt_updated_cart', function() { 
	jQuery("input[name='_wp_http_referer']").val("/cart/");

});`

**Comment by franticpsyx** [comment]
No luck trying to replicate this one, I'm afraid. I followed steps 1-5 exactly, no issues.
@thenbrent can you have a look? Am I missing something obvious here?

**Comment by pprotschka** [comment]
@franticpsyx  try it out in my playbox:

http://dev.fitmeal.at/index.php/product/wochenbox/
add to cart-> goto cart.

maybe i wasn't clear or it's a local issue but it happens on my production site and a "new almost no changes" test site.

![image](https://cloud.githubusercontent.com/assets/20007453/20758467/2d0dcaa0-b71a-11e6-9d1a-55829fd7d28d.png)

result:
![image](https://cloud.githubusercontent.com/assets/20007453/20758511/5286eed8-b71a-11e6-8439-b7f502efa77e.png)

**Comment by franticpsyx** [comment]
Got it now, thanks -- you are referring to cart subscription options, not the inline cart item subscription options. Will try to replicate and look into it later.

**Comment by franticpsyx** [comment]
@thenbrent Can you take a look at this?

**Comment by vuongtng** [comment]
I've also ran into the issue. Basically when updating the cart without Subscribe to Cart, everything is fine. But if you select a Subscribe to Cart option and attempt to update a product you run into a blank page (in my case I had a -1 when increasing or decreasing quantity of a simple product). The Address bar shows "/cart/?wc-ajax=wcsatt_update_cart_option"
