### ISSUE TITLE
issue with composite product

### ISSUE THREAD

**Issue by Mylittlebigweb** [Prospress/woocommerce-subscribe-all-the-things#83]
Hello

I created 3 simple product with subscription attach to them, and then create a composite product with those 3 but it doesn't work.

getting the error: This product cannot be purchased at the moment.

**Comment by franticpsyx** [comment]
Products converted to subscriptions using SATT will not work in composites/bundles/mix-and-match products.

You can only use SATT to define subscription options for the entire composite/bundle.
