### ISSUE TITLE
Cart subtotals for bundle subscription plans are incorrect

### ISSUE THREAD

**Issue by allison-beh** [Prospress/woocommerce-subscribe-all-the-things#84]
Hi,

I've configured a product bundle to have the 2 subscription options with following settings:

- Override product; every month for 3 months, regular price $75
- Override product; every month for 6 months, regular price $70

Here's the subscription page: http://staging.basaotea.com/subscription/

For some reason, when the subscription is added to the cart, the cart subtotals are incorrect, and I find that it's always a multiply of 3 to the regular price (please see screenshot).

![screen shot 2016-12-04 at 6 39 01 pm](https://cloud.githubusercontent.com/assets/18515716/20865641/69ec2850-ba52-11e6-8ea4-c38dbf199b33.png)
 
This error is seen on all subscription options. I've tried with various regular price and period, still the same miscalculation. 

Have I missed anything in the configuration?

Thanks,
--
Allison

**Comment by franticpsyx** [comment]
Hi @allison-beh -- could you please share:

- the pricing settings of your bundle (General tab)
- the configuration of the bundle (Bundled Products tab, both Basic and Advanced settings)
- Product Bundles extension version

Thanks!

**Comment by allison-beh** [comment]
Hi @franticpsyx ,

I figured out where the number comes from. 

Here are the screenshots:

![screen shot 2016-12-05 at 5 19 40 pm](https://cloud.githubusercontent.com/assets/18515716/20879579/7cd40538-bb0f-11e6-9bf1-047e25060359.png)

![screen shot 2016-12-05 at 5 20 14 pm](https://cloud.githubusercontent.com/assets/18515716/20879899/c69a3a6a-bb10-11e6-84fa-901c0527e0b7.png)

![screen shot 2016-12-05 at 5 29 02 pm](https://cloud.githubusercontent.com/assets/18515716/20879949/05946c22-bb11-11e6-9444-3d4b7bdfc614.png)

It turns out that when I chose **Override Product** a the Subscription Price, the extension would automatically set the individual price for each item in the bundle to the same as the overridden regular price - So it became regular price of Subscription $70 + Product A $70 + Product B $70 = $210.

I tried to check the **Price Individually** under each product and set the discount to 100% but the discount was ignored once I chose **Override Product**. I ended up had to choose **Inherit from Product** like what is shown in the screenshot. 

Is there a way for me to choose **Override Product** and yet without adding individual item price to the final subscription price?

Thanks for replying!

**Comment by franticpsyx** [comment]
Hey @allison-beh -- thanks for the details!

Can you download and test this version - https://github.com/Prospress/woocommerce-subscribe-all-the-things/tree/issue-84 from branch `issue-84`?

It should fix this issue.

**Comment by allison-beh** [comment]
Hi @franticpsyx ,

Yes! It's perfect now, thanks for the quick fix! Thanks for correcting the styling at the Subscriptions metabox too. :)

Thank you for creating this super handy extension for the community! 👍 👍

--
Allison

**Comment by franticpsyx** [comment]
Great news - closing!
