### ISSUE TITLE
Sync. renewal date for Subscribe all things

### ISSUE THREAD

**Issue by GAPP99** [Prospress/woocommerce-subscribe-all-the-things#88]
I've read the documentations very carefully for these Extensions, and it seems the possibility of selecting a sync. renewal day for a Subscription Mix 'N Match product is not possible, as it is if a simple subscription is selected.

Could you please add this for the next update?

**Comment by seb86** [comment]
@GAPP99 I actually started working on the sync option for a client for Mix and Match Products but then the client changed their mind. What I have so far is on the repository below. You are welcome to try it out and report feedback.

> Please note that the code has not been updated over the past **3 months** and may not work with the current changes in **Subscribe All the Things** that have been made over the past couple of weeks.

Try [WooCommerce Subscribe All the Things - Sync Add-on](https://github.com/seb86/woocommerce-subscribe-all-the-things-sync-add-on)

**Comment by GAPP99** [comment]
@seb86 Thank you. I've successfully installed the plugin, and it seems to be working still. I'll test it out and give you some feedback.

**Comment by franticpsyx** [comment]
Already discussed in https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/1 -- closing since this is already on our radar.

@seb86 -- thanks for chiming in!
