### ISSUE TITLE
Switching Mix 'n Match subscription products

### ISSUE THREAD

**Issue by GAPP99** [Prospress/woocommerce-subscribe-all-the-things#89]
I would like customers to be able to switch out their Mix 'n Match products of the subscription they have, but I can't find out how and where this can be done. Is this achievable?

**Comment by franticpsyx** [comment]
See #12

**Comment by fdolin** [comment]
hi, i'm also interested in this service. I've seen the thread #12 is about it, however this is locked and limited to collaborators. 
Could i be added to this thread ? thank you

**Comment by fdolin** [comment]
@franticpsyx @GAPP99  i'm very interested in a way to switch out my customers  Mix 'n Match products of the subscription they have, do you know where i could find more help on this ? thank you in advance,

**Comment by GAPP99** [comment]
Hi @fdolin. It's not possible currently, but it's on the roadmap for SATT 2.0+, so your best bet would be just to wait a few months. If you can't wait, I suggest you talk to @seb86, he might be able to build a custom system for you.

**Comment by fdolin** [comment]
ok @GAPP99, thanks for the quick answer !

**Comment by seb86** [comment]
@GAPP99 @fdolin I literally sneezed when I got mentioned on this issue. How can I help? 😄
