### ISSUE TITLE
What happens when a product is out of stock?

### ISSUE THREAD

**Issue by martinmansson** [Prospress/woocommerce-subscribe-all-the-things#93]
What happens if a customer have subscribed to a product and the product goes out of stock? Will the renewal fail? 
If a user has subscribed to multiple products and one is of them is out of stock, what will then happen?

Thanks,
Martin

**Comment by thenbrent** [comment]
Hi Martin, this question is answered here: https://docs.woocommerce.com/document/subscriptions/faq/#section-17 :)
