### ISSUE TITLE
SATT won't process recurring orders correctly

### ISSUE THREAD

**Issue by GAPP99** [Prospress/woocommerce-subscribe-all-the-things#94]
Hello,

I first wrote WooCommerce support, who after a few  messages back and forward asked me to direct my question directly to you, as the developers of SATT.

So these are the plugins I use: 
WooCommerce Subscriptions version 2.1.2
WooCommerce Mix 'n Match version 1.1.8
WooCommerce Subscribe All The Things version 1.1.2

Everything seems to be working fine and dandy together with Stripe, and the payments are processed correctly every time. There's just one small problem.

Whenever the recurring order goes through and is processed by Stripe, the status will change to "Processing", instead of "Complete" on the actual order, which prompts me to do manual work to fix it. Please note, that the payment actually is gone through. Here's a screenshot(even though it's in danish): http://prntscr.com/drsvzr

So let me explain fully how the setup works:

I use a Mix 'n Match product, with a container limit at 7. For this I've activated the "Force Subscription with "Subscribe All The Things".

Then I've added various simple products, and after that's been done, I include them in the Mix 'n Match, so I'm actually able to select them.

I've noticed, that if I remove the Mix 'n Match variations inside MyAccount, and only the actual "container" is left, then it will say "Complete" instead of "Processing".

So my question is, how can I fix this issue?

**Comment by pprotschka** [comment]
this is default behaviour of WC. This has nothing todo with SATT i think. a paid for order will have status "processing" implying a payment has been received and you need to "process the order" ;)

you will need to find the right "hook"  and set order status to complete after the order status updates.
if you dont what a hook is i would into hiring a developer.

also given the coming WC release the real brains behind this plugin are busy upgrading their commercial plugins i assume. So dont count on help or a fix anytime soon. 
IMHO your setup is way to complex for SATT at this stage. (id call it experimental...) so compatibility is untested and should not be expected.
@franticpsyx suggest close.

**Comment by GAPP99** [comment]
@pprotschka Thank you for your answer. Forgive me for not mentioning. I already use an autocomplete hook, which can be found here: https://docs.woocommerce.com/document/automatically-complete-orders/

The problem does not exist, if I run a normal subscription, only with Mix 'n Match + SATT.

**Comment by pprotschka** [comment]
this hook only runs on checkout. not on automatic order processing.
again. you need to find the right hook ...something like 
"woocommerce_order_status_processing" but for renewal orders

http://squelchdesign.com/web-design-newbury/woocommerce-detecting-order-complete-on-order-completion/

**Comment by GAPP99** [comment]
I found this plugin: https://woocommerce.com/products/woocommerce-order-status-control/

I think it might actually do the job, for a guy without any coding background. Thank you for guiding me on the right path.

**Comment by pprotschka** [comment]
@GAPP99 unless it says its compatible with woocommerce subscriptions i'm afraid it wont. HERE is the hook you are looking for: woocommerce_renewal_order_payment_complete

**Comment by pprotschka** [comment]
so add this to functions.php
add_action( 'woocommerce_renewal_order_payment_complete', 'custom_woocommerce_auto_complete_order' );

**Comment by GAPP99** [comment]
@pprotschka Thank you very much!

**Comment by franticpsyx** [comment]
@pprotschka thanks for jumping in here -- and kudos for the spot on tips.

>Also given the coming WC release the real brains behind this plugin are busy upgrading their commercial plugins i assume. So dont count on help or a fix anytime soon.

That's accurate. Due to the number of dependencies and its non-commercial nature, SATT will be the last to be updated. This will happen after (or while) any compatibility issues with WC 2.7 are ironed out, so there's a chance that WC 2.7 might be released before SATT is fully compatible with it.

Regarding the actual issue, only WC orders with Downloadable + Virtual items auto-complete. Any other desired behavior needs to be custom-developed.
