### ISSUE TITLE
Subscription interval/period labels hiding respective fields

### ISSUE THREAD

**Issue by dmseaton** [Prospress/woocommerce-subscribe-all-the-things#98]
Aesthetics aside, it's consequently difficult to access the interval field with click.

![screen shot 2017-01-31 at 13 43 35](https://cloud.githubusercontent.com/assets/8384343/22467205/9adf9172-e7bb-11e6-95bc-69d1b435597b.png)

Tested in Firefox 51.0.1 and Chrome 55.0.2883.95

**Comment by franticpsyx** [comment]
Thanks for the report @dmseaton -- can you share version numbers for SATT and WC Subscriptions?

This affects SATT 1.1.1 when used with Subscriptions 2.1. However, it should be fixed in 1.1.2 -- https://github.com/Prospress/woocommerce-subscribe-all-the-things/releases/tag/1.1.2

**Comment by dmseaton** [comment]
Currently SATT 1.1.2 and Subscriptions 2.0.19, so the latter might explain it. I'll get Subscriptions updated and give it a go. Thank you!

**Comment by dmseaton** [comment]
Can confirm that this resolved the issue. Appreciate the quick response and advice!
