### ISSUE TITLE
Synchronisation + Switching

### ISSUE THREAD

**Issue by filipeaparicio** [Prospress/woocommerce-subscribe-all-the-things#99]
Are there any plans to implement the synchronisation feature for subscriptions? This is a must to help payments / shipping being processed all on the same day.

Also, although the switching option seems to be "working" for composite products after a subscription has been activated, it doesn't allow users to replace products. It only allows them to remove elements completely. Are there any plans for this as well?

**Comment by seb86** [comment]
Yes there is. Please read [this issue](https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/1) for more information.

**Comment by thenbrent** [comment]
Closing as duplicate of https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/1 & https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/12

@filipeaparicio please have a read over those to understand the issues. 🙂

We also have a new, draft wiki article explaining the plans to address these types of features more generally: https://github.com/Prospress/woocommerce-subscribe-all-the-things/wiki/Future-of-Subscribe-All-the-Things
